import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../../api';

type Tab='executive'|'subscriptions'|'billing'|'plans'|'integrations'|'support';
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(c)||0)/100);
const box='bg-[#121414] border border-[#333] p-4';
const btn='px-3 py-2 border border-[#444] text-[10px] font-black hover:border-[#DFFF00]';
const get=async(path:string)=>{const r=await fetch(`/api${path}`,{credentials:'include'});let d:any={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Erro ${r.status}`);return d};
const Stat=({label,value,sub}:{label:string;value:any;sub?:string})=><div className={box}><div className="text-[9px] uppercase text-gray-500">{label}</div><b className="text-2xl text-[#DFFF00]">{value}</b>{sub&&<div className="text-[9px] text-gray-600 mt-1">{sub}</div>}</div>;
const Flag=({label,ok}:{label:string;ok:boolean})=><div className={`${box} ${ok?'border-green-900':'border-yellow-800'}`}><div className="text-[9px] uppercase text-gray-500">{label}</div><b className={ok?'text-green-400':'text-yellow-400'}>{ok?'ATIVO':'PENDENTE'}</b></div>;

export const AdminMasterCenter:React.FC=()=>{
 const [tab,setTab]=useState<Tab>('executive'),[coaches,setCoaches]=useState<any[]>([]),[billing,setBilling]=useState<any>({summary:{},events:[]}),[master,setMaster]=useState<any>({}),[ops,setOps]=useState<any>({settings:{},readiness:{},risks:{}}),[settings,setSettings]=useState<any>({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const load=async()=>{try{const [c,b,m,o,s]=await Promise.all([get('/admin/master/coaches'),get('/admin/master/billing').catch(()=>({summary:{},events:[]})),api.adminMasterMetrics(),get('/admin/master/overview'),api.adminSettings()]);setCoaches(c.coaches||[]);setBilling(b);setMaster(m.metrics||{});setOps(o);const map:any={};(s.settings||[]).forEach((x:any)=>map[x.key]=x.value);setSettings(map)}catch(e:any){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 const saveSettings=async()=>{setBusy(true);setMsg('');try{await api.updateAdminSettings(settings);setMsg('Configurações comerciais atualizadas.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const setPlan=async(id:any,plan:string,status:string)=>{setBusy(true);setMsg('');try{await api.updateCoachPlan(id,plan,status);setMsg('Plano/assinatura atualizado.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const impersonate=async(id:any)=>{try{await api.impersonate(id);window.location.reload()}catch(e:any){setMsg(e.message)}};
 const filtered=useMemo(()=>coaches.filter((c:any)=>!search||`${c.name} ${c.email} ${c.planCode} ${c.subscriptionStatus}`.toLowerCase().includes(search.toLowerCase())),[coaches,search]);
 const tabs:[Tab,string][]=[['executive','Executivo'],['subscriptions','Assinaturas'],['billing','Financeiro SaaS'],['plans','Planos & Limites'],['integrations','Integrações'],['support','Suporte']];
 const r=ops.readiness||{},risk=ops.risks||{};
 return <section className="space-y-4">{msg&&<div className="bg-black border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}<div className="bg-[#0e1010] border border-[#DFFF00]/30 p-5"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4"><div><div className="text-[10px] font-mono text-[#DFFF00]">// ADMIN MASTER CONTROL CENTER</div><h2 className="font-anybody text-3xl font-black uppercase text-white">Controle total do SaaS</h2><p className="text-xs text-gray-500 mt-1">Assinaturas, faturamento, preços, limites, integrações e suporte.</p></div><div className="flex flex-wrap gap-2">{tabs.map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 text-[10px] border ${tab===id?'bg-[#DFFF00] text-black border-[#DFFF00]':'border-[#333] text-gray-300'}`}>{l}</button>)}</div></div></div>
 {tab==='executive'&&<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-2"><Stat label="Treinadores" value={master.coachesTotal||0}/><Stat label="Alunos" value={master.studentsTotal||0}/><Stat label="Assinaturas pagas" value={master.paidSubscriptions||0}/><Stat label="Trials" value={master.trials||0}/><Stat label="Receita 30d" value={money(master.paidCents30d||0)}/><Stat label="Pendências" value={money(master.pendingCents||0)}/></div><div className="grid grid-cols-2 md:grid-cols-5 gap-2"><Stat label="Sem treino 7d" value={risk.inactive7d||0}/><Stat label="Inadimplentes" value={risk.overduePayments||0}/><Stat label="Dor alta" value={risk.highPain||0}/><Stat label="Fadiga alta" value={risk.highFatigue||0}/><Stat label="Baixa energia" value={risk.lowEnergy||0}/></div></div>}
 {tab==='subscriptions'&&<div className="space-y-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar treinador, plano ou status..." className="w-full bg-black border border-[#333] p-3 text-xs"/><div className="space-y-2">{filtered.map((c:any)=><div key={c.id} className={`${box} flex flex-col xl:flex-row xl:items-center gap-3`}><div className="flex-1"><b className="text-white">{c.name}</b><div className="text-[10px] text-gray-500">{c.email} • {c.studentsCount}/{c.studentLimit} alunos • {c.workouts30d||0} treinos 30d</div><div className="text-[10px] mt-1"><span className="text-[#DFFF00]">{String(c.planCode).toUpperCase()}</span> • <span className={c.subscriptionStatus==='active'?'text-green-400':c.subscriptionStatus==='past_due'?'text-red-400':'text-yellow-400'}>{c.subscriptionStatus}</span> • {c.billingGateway||'sem gateway'} {c.trialEndsAt&&`• trial até ${new Date(c.trialEndsAt).toLocaleDateString('pt-BR')}`}</div></div><select value={c.planCode||'trial'} onChange={e=>setPlan(c.id,e.target.value,e.target.value==='trial'?'trialing':'active')} disabled={busy} className="bg-black border border-[#444] p-2 text-xs"><option value="trial">TRIAL</option><option value="basic">BÁSICO</option><option value="pro">PRO</option><option value="business">BUSINESS</option></select><select value={c.subscriptionStatus||'trialing'} onChange={e=>setPlan(c.id,c.planCode||'trial',e.target.value)} disabled={busy} className="bg-black border border-[#444] p-2 text-xs"><option value="trialing">TRIAL</option><option value="active">ATIVA</option><option value="past_due">INADIMPLENTE</option><option value="cancelled">CANCELADA</option><option value="expired">EXPIRADA</option></select><button onClick={()=>impersonate(c.id)} className={btn}>VISUALIZAR COMO</button></div>)}</div></div>}
 {tab==='billing'&&<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 gap-2"><Stat label="Eventos" value={billing.summary?.eventsTotal||0}/><Stat label="Eventos 30d" value={billing.summary?.created30d||0}/><Stat label="Ativas" value={billing.summary?.activeSubscriptions||0}/><Stat label="Past due" value={billing.summary?.pastDue||0}/></div><div className={box}><h3 className="font-anybody font-black uppercase text-white mb-3">Eventos recentes de cobrança</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="text-gray-500"><tr><th className="text-left p-2">Treinador</th><th className="text-left p-2">Gateway</th><th className="text-left p-2">Status</th><th className="text-left p-2">Valor</th><th className="text-left p-2">Data</th></tr></thead><tbody>{(billing.events||[]).map((e:any)=><tr key={e.id} className="border-t border-[#222]"><td className="p-2 text-white">{e.coachName}</td><td className="p-2">{e.gateway}</td><td className="p-2">{e.status}</td><td className="p-2">{e.amountCents?money(e.amountCents):'-'}</td><td className="p-2">{new Date(e.createdAt).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div></div></div>}
 {tab==='plans'&&<div className="grid lg:grid-cols-2 gap-3"><div className={`${box} space-y-3`}><h3 className="font-anybody font-black uppercase text-white">Trial</h3><Field label="Dias de trial" value={settings['trial.days']||'7'} onChange={v=>setSettings({...settings,'trial.days':v})}/><h3 className="font-anybody font-black uppercase text-white pt-2">Limites de alunos</h3><Field label="Trial" value={settings['plan.trial.limit']||'5'} onChange={v=>setSettings({...settings,'plan.trial.limit':v})}/><Field label="Básico" value={settings['plan.basic.limit']||'20'} onChange={v=>setSettings({...settings,'plan.basic.limit':v})}/><Field label="Pro" value={settings['plan.pro.limit']||'100'} onChange={v=>setSettings({...settings,'plan.pro.limit':v})}/><Field label="Business" value={settings['plan.business.limit']||'500'} onChange={v=>setSettings({...settings,'plan.business.limit':v})}/></div><div className={`${box} space-y-3`}><h3 className="font-anybody font-black uppercase text-white">Preços mensais</h3><Field label="Básico (centavos)" value={settings['plan.basic.price_cents']||'4900'} onChange={v=>setSettings({...settings,'plan.basic.price_cents':v})}/><Field label="Pro (centavos)" value={settings['plan.pro.price_cents']||'9900'} onChange={v=>setSettings({...settings,'plan.pro.price_cents':v})}/><Field label="Business (centavos)" value={settings['plan.business.price_cents']||'19900'} onChange={v=>setSettings({...settings,'plan.business.price_cents':v})}/><div className="text-[10px] text-gray-500">Ex.: 9900 = R$ 99,00.</div><button disabled={busy} onClick={saveSettings} className="w-full bg-[#DFFF00] text-black p-3 text-xs font-black">SALVAR PLANOS E LIMITES</button></div></div>}
 {tab==='integrations'&&<div className="grid grid-cols-2 md:grid-cols-4 gap-2"><Flag label="HTTPS" ok={!!r.https}/><Flag label="Mercado Pago" ok={!!r.mercadoPago}/><Flag label="Webhook Mercado Pago" ok={!!r.mercadoPagoWebhook}/><Flag label="Stripe" ok={!!r.stripe}/><Flag label="Webhook Stripe" ok={!!r.stripeWebhook}/><Flag label="Gemini" ok={!!r.gemini}/><Flag label="Web Push / VAPID" ok={!!r.vapid}/><Flag label="Backup" ok={!!ops.backup}/></div>}
 {tab==='support'&&<div className="grid lg:grid-cols-2 gap-3"><div className={box}><h3 className="font-anybody font-black uppercase text-white mb-2">Acesso de suporte</h3><p className="text-xs text-gray-500 mb-4">Use “Visualizar como” na aba Assinaturas para entrar na conta de um treinador sem conhecer a senha. A ação é auditada e pode ser encerrada pela barra superior.</p><div className="text-[10px] text-yellow-400">Não use impersonação para alterar dados sem solicitação do cliente.</div></div><div className={box}><h3 className="font-anybody font-black uppercase text-white mb-2">Gestão de contas</h3><p className="text-xs text-gray-500">Criação, reset de senha, arquivamento, restauração e exclusão definitiva continuam na área “Administração PulseFit” logo abaixo. O histórico de todas as ações fica em Auditoria.</p></div></div>}
 </section>;
};
const Field=({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void})=><label className="block"><span className="text-[9px] uppercase text-gray-500">{label}</span><input type="number" value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full bg-black border border-[#333] p-3 text-xs text-white"/></label>;
