import React,{useEffect,useState} from 'react';
import {api} from '../../api';

const input='w-full bg-black border border-[#333] p-3 text-xs text-white outline-none focus:border-[#DFFF00]';
const btn='px-3 py-2 border border-[#444] text-[10px] font-black hover:border-[#DFFF00]';

async function setCredentials(coachId:string|number,email:string,password:string,forceChangePassword:boolean){
  const me=await fetch('/api/auth/me',{credentials:'include'});const session=await me.json();
  if(!me.ok)throw new Error(session?.error||'Sessão inválida.');
  const r=await fetch(`/api/admin/coaches/${coachId}/credentials`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf||''},body:JSON.stringify({email,password,forceChangePassword})});
  const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||`Erro ${r.status}`);return data;
}

export const AdminCoachCredentialsPanel:React.FC=()=>{
 const [coaches,setCoaches]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[showPasswords,setShowPasswords]=useState(false);
 const [form,setForm]=useState({name:'',email:'',password:'',cref:'',specialty:'',unit:'',forceChangePassword:false});
 const [edit,setEdit]=useState<Record<string,{email:string,password:string,forceChangePassword:boolean}>>({});
 const load=async()=>{try{const r=await api.coaches();setCoaches(r.coaches||[])}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const create=async()=>{if(!form.name.trim()||!form.email.trim()||form.password.length<12){setMsg('Informe nome, login/e-mail e uma senha com pelo menos 12 caracteres.');return}setBusy(true);setMsg('');try{const r=await api.createCoach({name:form.name,email:form.email,password:form.password,cref:form.cref,specialty:form.specialty,unit:form.unit});await setCredentials(r.id,form.email,form.password,form.forceChangePassword);setMsg(`Treinador criado. Login: ${form.email} • senha definida por você.`);setForm({name:'',email:'',password:'',cref:'',specialty:'',unit:'',forceChangePassword:false});await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const save=async(c:any)=>{const f=edit[String(c.id)]||{email:c.email,password:'',forceChangePassword:false};if(!f.email.trim()){setMsg('Informe o login/e-mail.');return}if(f.password&&f.password.length<12){setMsg('A nova senha precisa ter pelo menos 12 caracteres.');return}setBusy(true);setMsg('');try{await setCredentials(c.id,f.email,f.password,f.forceChangePassword);setMsg(`Credenciais de ${c.name} atualizadas.`);setEdit(p=>({...p,[String(c.id)]:{email:f.email,password:'',forceChangePassword:f.forceChangePassword}}));await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const generate=()=>{const p=`Pf!${crypto.getRandomValues(new Uint32Array(2)).join('').slice(0,12)}Aa9`;setForm(f=>({...f,password:p}));};
 return <section className="bg-[#101212] border border-[#DFFF00]/30 p-5 space-y-4">
  <div><div className="text-[10px] font-mono text-[#DFFF00]">// ACESSO DOS TREINADORES</div><h2 className="font-anybody text-2xl font-black uppercase text-white">Login e senha para testes</h2><p className="text-xs text-gray-500 mt-1">Crie uma conta com credenciais conhecidas ou altere o acesso de um treinador existente. Senhas nunca são exibidas depois de salvas.</p></div>
  {msg&&<div className="bg-black border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}
  <div className="grid xl:grid-cols-[360px_1fr] gap-4">
   <div className="bg-[#121414] border border-[#333] p-4 space-y-2"><h3 className="font-anybody font-black uppercase text-white">Criar treinador de teste</h3><input className={input} placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={input} type="email" placeholder="Login / e-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><div className="flex gap-2"><input className={input} type={showPasswords?'text':'password'} placeholder="Senha (mín. 12 caracteres)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={generate} className={btn}>GERAR</button></div><input className={input} placeholder="CREF (opcional)" value={form.cref} onChange={e=>setForm({...form,cref:e.target.value})}/><input className={input} placeholder="Especialidade" value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}/><input className={input} placeholder="Unidade" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><label className="flex gap-2 items-center text-[10px] text-gray-400"><input type="checkbox" checked={form.forceChangePassword} onChange={e=>setForm({...form,forceChangePassword:e.target.checked})}/> Exigir troca da senha no primeiro acesso</label><label className="flex gap-2 items-center text-[10px] text-gray-500"><input type="checkbox" checked={showPasswords} onChange={e=>setShowPasswords(e.target.checked)}/> Mostrar senha enquanto digito</label><button disabled={busy} onClick={create} className="w-full bg-[#DFFF00] text-black p-3 text-xs font-black disabled:opacity-50">CRIAR COM ESTE LOGIN E SENHA</button></div>
   <div className="bg-[#121414] border border-[#333] p-4"><h3 className="font-anybody font-black uppercase text-white mb-3">Alterar credenciais existentes</h3><div className="space-y-2 max-h-[560px] overflow-auto">{coaches.map(c=>{const f=edit[String(c.id)]||{email:c.email||'',password:'',forceChangePassword:false};return <div key={c.id} className="bg-black border border-[#292929] p-3 grid lg:grid-cols-[1fr_220px_220px_auto] gap-2 items-center"><div><b className="text-white text-sm">{c.name}</b><div className="text-[9px] text-gray-500">{c.cref||'Sem CREF'} • {c.studentsCount||0} aluno(s)</div></div><input className={input} value={f.email} onChange={e=>setEdit(p=>({...p,[String(c.id)]:{...f,email:e.target.value}}))} placeholder="Login/e-mail"/><input className={input} type={showPasswords?'text':'password'} value={f.password} onChange={e=>setEdit(p=>({...p,[String(c.id)]:{...f,password:e.target.value}}))} placeholder="Nova senha (opcional)"/><div className="flex flex-col gap-1"><button disabled={busy} onClick={()=>save(c)} className="px-3 py-2 bg-[#DFFF00] text-black text-[9px] font-black">SALVAR ACESSO</button><label className="text-[8px] text-gray-500 whitespace-nowrap"><input type="checkbox" checked={f.forceChangePassword} onChange={e=>setEdit(p=>({...p,[String(c.id)]:{...f,forceChangePassword:e.target.checked}}))}/> exigir troca</label></div></div>})}{!coaches.length&&<div className="text-xs text-gray-500">Nenhum treinador cadastrado.</div>}</div></div>
  </div>
 </section>;
};
