import React,{useEffect,useMemo,useState} from 'react';
import {ScreenView,Student} from '../../types';
import {api,normalizeStudent} from '../../api';
type Tab='overview'|'admins'|'coaches'|'students'|'archived'|'audit'|'backup';
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((c||0)/100);
const input='bg-black border border-[#333] p-2.5 text-xs text-white outline-none focus:border-[#DFFF00]';
export const AdminDashboardScreen:React.FC<{onNavigate:(s:ScreenView)=>void;onSelectStudent:(s:Student)=>void}>=({onNavigate,onSelectStudent})=>{
 const [tab,setTab]=useState<Tab>('overview'),[coaches,setCoaches]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[admins,setAdmins]=useState<any[]>([]),[archived,setArchived]=useState<any>({students:[],coaches:[]}),[overview,setOverview]=useState<any>({}),[logs,setLogs]=useState<any[]>([]),[backups,setBackups]=useState<any[]>([]),[alerts,setAlerts]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[status,setStatus]=useState(''),[coachFilter,setCoachFilter]=useState(''),[financial,setFinancial]=useState(''),[workout,setWorkout]=useState('');
 const [newAdmin,setNewAdmin]=useState({name:'',email:'',password:'',adminLevel:'read_only'}),[newCoach,setNewCoach]=useState({name:'',email:'',cref:'',specialty:'',unit:'',password:''}),[newStudent,setNewStudent]=useState({name:'',email:'',coachId:'',programName:'Programa inicial',phase:'Fase 1',planName:'',password:''});
 const load=async()=>{try{const [c,s,a,o,l,b,al,as,ac]=await Promise.all([api.coaches(),api.students(),api.admins(),api.adminOverview(),api.auditLogs(),api.backups().catch(()=>({backups:[]})),api.alerts(),api.archivedStudents(),api.archivedCoaches()]);setCoaches(c.coaches||[]);setStudents((s.students||[]).map(normalizeStudent));setAdmins(a.admins||[]);setOverview(o.overview||{});setLogs(l.logs||[]);setBackups(b.backups||[]);setAlerts(al.alerts||[]);setArchived({students:as.students||[],coaches:ac.coaches||[]})}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const act=async(fn:()=>Promise<any>,ok='Concluído.')=>{setBusy(true);setMsg('');try{const r=await fn();setMsg(r?.temporaryPassword?`${ok} Senha temporária: ${r.temporaryPassword}`:ok);await load();return r}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const filtered=useMemo(()=>students.filter((s:any)=>(!q||`${s.name} ${s.email} ${s.programName}`.toLowerCase().includes(q.toLowerCase()))&&(!status||s.status===status)&&(!coachFilter||String(s.assignedCoachId)===coachFilter)&&(!financial||financial!=='overdue'||s.hasOverduePayment)&&(!workout||workout!=='late'||s.workoutLate)),[students,q,status,coachFilter,financial,workout]);
 const openStudent=(s:any)=>{onSelectStudent(normalizeStudent(s) as Student);onNavigate('student_detail')};
 const viewCoach=async(id:any)=>{try{await api.impersonate(id);window.location.reload()}catch(e:any){setMsg(e.message)}};
 const viewStudent=async(id:any)=>{try{const d=await api.studentFull(id);await api.impersonate(d.student.user_id);window.location.reload()}catch(e:any){setMsg(e.message)}};
 const setPlan=(id:any,planCode:string)=>act(()=>api.updateCoachPlan(id,planCode,planCode==='trial'?'trialing':'active'),'Plano atualizado.');
 const tabs:[Tab,string][]=[['overview','Visão geral'],['admins','Administradores'],['coaches','Treinadores'],['students','Alunos'],['archived','Arquivados'],['audit','Histórico'],['backup','Backups']];
 return <div className="space-y-5">{msg&&<div className="sticky top-16 z-30 bg-black border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}<div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4"><div><div className="text-[10px] font-mono text-[#DFFF00]">// SAAS MASTER CONTROL</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Administração PulseFit</h1></div><div className="flex flex-wrap gap-2">{tabs.map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 text-[10px] border ${tab===id?'bg-[#DFFF00] text-black border-[#DFFF00]':'border-[#333]'}`}>{l}</button>)}</div></div>
 {tab==='overview'&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{[['Treinadores ativos',overview.activeCoaches||0],['Alunos ativos',overview.activeStudents||0],['Sessões 30 dias',overview.sessions30d||0],['Pendente',money(overview.pendingCents||0)]].map(([l,v])=><Card key={String(l)} label={String(l)} value={v}/>)}</div><section className="bg-[#121414] border border-[#333] p-4"><h2 className="font-anybody font-black uppercase text-white mb-3">Alertas inteligentes</h2><div className="grid md:grid-cols-2 gap-2">{alerts.slice(0,20).map((a:any,i)=><button key={i} onClick={()=>{const s=students.find((x:any)=>String(x.id)===String(a.studentId));if(s)openStudent(s)}} className="text-left bg-black border border-[#333] p-3 text-xs hover:border-[#DFFF00]"><b className={a.severity==='critical'?'text-red-400':'text-[#DFFF00]'}>{a.studentName}</b><div className="text-gray-400">{a.message}</div></button>)}{!alerts.length&&<div className="text-xs text-gray-500">Nenhum alerta operacional.</div>}</div></section></>}
 {tab==='admins'&&<div className="grid xl:grid-cols-[360px_1fr] gap-4"><Form title="Novo administrador"><input className={input} placeholder="Nome" value={newAdmin.name} onChange={e=>setNewAdmin({...newAdmin,name:e.target.value})}/><input className={input} placeholder="E-mail" value={newAdmin.email} onChange={e=>setNewAdmin({...newAdmin,email:e.target.value})}/><input className={input} type="password" placeholder="Senha inicial (opcional)" value={newAdmin.password} onChange={e=>setNewAdmin({...newAdmin,password:e.target.value})}/><select className={input} value={newAdmin.adminLevel} onChange={e=>setNewAdmin({...newAdmin,adminLevel:e.target.value})}><option value="super_admin">Super Admin</option><option value="support">Suporte</option><option value="finance">Financeiro</option><option value="read_only">Somente leitura</option></select><button disabled={busy} onClick={()=>act(()=>api.createAdmin({...newAdmin,password:newAdmin.password||undefined}),'Administrador criado.')} className="btn">CRIAR ADMIN</button></Form><List>{admins.map((a:any)=><Row key={a.id} title={a.name} sub={`${a.email} • ${a.adminLevel}`}><button onClick={()=>act(()=>api.resetAdminAccess(a.id),'Senha redefinida.')} className="small">RESETAR SENHA</button></Row>)}</List></div>}
 {tab==='coaches'&&<div className="grid xl:grid-cols-[360px_1fr] gap-4"><Form title="Novo treinador">{[['name','Nome'],['email','E-mail'],['cref','CREF'],['specialty','Especialidade'],['unit','Unidade'],['password','Senha inicial (opcional)']].map(([k,l])=><input key={k} className={input} type={k==='password'?'password':'text'} placeholder={l} value={(newCoach as any)[k]} onChange={e=>setNewCoach({...newCoach,[k]:e.target.value})}/>)}<button onClick={()=>act(()=>api.createCoach({...newCoach,password:newCoach.password||undefined}),'Treinador criado.')} className="btn">CRIAR TREINADOR</button></Form><List>{coaches.map((c:any)=><Row key={c.id} title={c.name} sub={`${c.email} • ${c.studentsCount||0} alunos • ${c.status}`}><select defaultValue="" onChange={e=>e.target.value&&setPlan(c.id,e.target.value)} className="small bg-black"><option value="">PLANO...</option><option value="trial">TRIAL</option><option value="basic">BÁSICO</option><option value="pro">PRO</option><option value="business">BUSINESS</option></select><button onClick={()=>viewCoach(c.id)} className="small hi">VISUALIZAR COMO</button><button onClick={()=>act(()=>api.resetCoachAccess(c.id),'Senha redefinida.')} className="small">RESETAR</button><button onClick={()=>confirm('Arquivar treinador?')&&act(()=>api.archiveCoach(c.id),'Treinador arquivado.')} className="small">ARQUIVAR</button></Row>)}</List></div>}
 {tab==='students'&&<><div className="grid md:grid-cols-5 gap-2 bg-[#121414] border border-[#333] p-3"><input className={input} placeholder="Buscar aluno..." value={q} onChange={e=>setQ(e.target.value)}/><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos status</option><option value="active">Ativos</option><option value="expired">Inativos</option></select><select className={input} value={coachFilter} onChange={e=>setCoachFilter(e.target.value)}><option value="">Todos treinadores</option>{coaches.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select className={input} value={financial} onChange={e=>setFinancial(e.target.value)}><option value="">Financeiro</option><option value="overdue">Inadimplentes</option></select><select className={input} value={workout} onChange={e=>setWorkout(e.target.value)}><option value="">Treinos</option><option value="late">Treino atrasado</option></select></div><div className="grid xl:grid-cols-[360px_1fr] gap-4"><Form title="Novo aluno"><input className={input} placeholder="Nome" value={newStudent.name} onChange={e=>setNewStudent({...newStudent,name:e.target.value})}/><input className={input} placeholder="E-mail" value={newStudent.email} onChange={e=>setNewStudent({...newStudent,email:e.target.value})}/><select className={input} value={newStudent.coachId} onChange={e=>setNewStudent({...newStudent,coachId:e.target.value})}><option value="">Treinador responsável</option>{coaches.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className={input} placeholder="Programa" value={newStudent.programName} onChange={e=>setNewStudent({...newStudent,programName:e.target.value})}/><input className={input} type="password" placeholder="Senha inicial (opcional)" value={newStudent.password} onChange={e=>setNewStudent({...newStudent,password:e.target.value})}/><button onClick={()=>act(()=>api.createStudent({...newStudent,coachId:Number(newStudent.coachId),password:newStudent.password||undefined}),'Aluno criado.')} className="btn">CRIAR ALUNO</button></Form><List>{filtered.map((s:any)=><Row key={s.id} title={s.name} sub={`${s.assignedCoachName} • ${s.programName} • ${s.hasOverduePayment?'INADIMPLENTE':'financeiro ok'} • ${s.workoutLate?'treino atrasado':'treino ok'}`}><button onClick={()=>openStudent(s)} className="small hi">ABRIR FICHA</button><button onClick={()=>viewStudent(s.id)} className="small hi">VISUALIZAR COMO</button><button onClick={()=>act(()=>api.resetStudentAccess(s.id),'Senha redefinida.')} className="small">RESETAR</button><button onClick={()=>confirm('Arquivar aluno?')&&act(()=>api.archiveStudent(s.id),'Aluno arquivado.')} className="small">ARQUIVAR</button></Row>)}</List></div></>}
 {tab==='archived'&&<div className="grid lg:grid-cols-2 gap-4"><List title="Alunos arquivados">{archived.students.map((s:any)=><Row key={s.id} title={s.name} sub={s.email}><button onClick={()=>act(()=>api.restoreStudent(s.id),'Aluno restaurado.')} className="small hi">RESTAURAR</button><button onClick={()=>confirm('EXCLUIR DEFINITIVAMENTE? Esta ação não pode ser desfeita.')&&act(()=>api.purgeStudent(s.id),'Aluno excluído definitivamente.')} className="danger">EXCLUIR DEFINITIVO</button></Row>)}</List><List title="Treinadores arquivados">{archived.coaches.map((c:any)=><Row key={c.id} title={c.name} sub={c.email}><button onClick={()=>act(()=>api.restoreCoach(c.id),'Treinador restaurado.')} className="small hi">RESTAURAR</button><button onClick={()=>confirm('EXCLUIR DEFINITIVAMENTE?')&&act(()=>api.purgeCoach(c.id),'Treinador excluído definitivamente.')} className="danger">EXCLUIR DEFINITIVO</button></Row>)}</List></div>}
 {tab==='audit'&&<List title="Histórico administrativo">{logs.map((l:any)=><Row key={l.id} title={`${l.actorName} • ${l.action}`} sub={`${l.entityType} #${l.entityId||'-'} • ${new Date(l.createdAt).toLocaleString('pt-BR')} • ${l.details||''}`}/>)}</List>}
 {tab==='backup'&&<div className="space-y-4"><button disabled={busy} onClick={()=>act(()=>api.createBackup(),'Backup gerado.')} className="btn px-5">GERAR BACKUP AGORA</button><List title="Backups disponíveis">{backups.map((b:any)=><Row key={b.name} title={b.name} sub={`${(Number(b.size)/1024/1024).toFixed(2)} MB • ${new Date(b.createdAt).toLocaleString('pt-BR')}`}/>)}</List></div>}
 </div>;
};
const Card=({label,value}:{label:string;value:any})=><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[9px] text-gray-500 uppercase">{label}</div><b className="text-3xl text-[#DFFF00]">{value}</b></div>;
const Form=({title,children}:{title:string;children:React.ReactNode})=><section className="bg-[#121414] border border-[#333] p-4 space-y-2 h-fit"><h2 className="font-anybody font-black uppercase text-white mb-2">{title}</h2>{children}</section>;
const List=({title,children}:{title?:string;children:React.ReactNode})=><section className="bg-[#121414] border border-[#333] p-4 space-y-2">{title&&<h2 className="font-anybody font-black uppercase text-white mb-2">{title}</h2>}{children}</section>;
const Row=({title,sub,children}:{title:string;sub:string;children?:React.ReactNode})=><div className="bg-black border border-[#2a2a2a] p-3 flex flex-col xl:flex-row xl:items-center gap-2"><div className="flex-1"><b className="text-white text-sm">{title}</b><div className="text-[10px] text-gray-500 break-all">{sub}</div></div><div className="flex flex-wrap gap-1">{children}</div></div>;
