import React,{useEffect,useState} from 'react';
import {ScreenView,UserRole} from '../../types';
import {api} from '../../api';

export const AssinaturaScreen:React.FC<{onNavigate:(s:ScreenView)=>void;userRole?:UserRole}>=({userRole='student'})=>{
 const [payments,setPayments]=useState<any[]>([]),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const load=()=>api.payments().then(r=>setPayments(r.payments||[])).catch((e:any)=>setError(e.message));useEffect(()=>{load()},[]);
 const pending=payments.filter(p=>p.status==='pending').reduce((a,p)=>a+Number(p.amountCents||0),0);const paid=payments.filter(p=>p.status==='paid').reduce((a,p)=>a+Number(p.amountCents||0),0);
 const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
 const setStatus=async(id:any,status:'paid'|'pending'|'cancelled')=>{try{await api.updatePaymentStatus(id,status);setMsg('Cobrança atualizada.');await load()}catch(e:any){setError(e.message)}};
 return <div className="space-y-6">{error&&<div className="border border-red-500/40 p-3 text-red-300 text-xs">{error}</div>}{msg&&<div className="border border-[#DFFF00]/40 p-3 text-[#DFFF00] text-xs">{msg}</div>}<div><div className="text-[10px] font-mono text-[#DFFF00]">// FINANCEIRO</div><h1 className="font-anybody text-3xl font-black uppercase text-white">{userRole==='student'?'Minha Assinatura & Cobranças':'Financeiro & Cobranças'}</h1><p className="text-xs text-gray-500 mt-1">{userRole==='student'?'Acompanhe seus lançamentos e vencimentos.':'Acompanhe e dê baixa nos pagamentos dos alunos.'}</p></div><div className="grid sm:grid-cols-3 gap-3"><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] text-gray-500 font-mono">LANÇAMENTOS</div><b className="text-3xl text-white">{payments.length}</b></div><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] text-gray-500 font-mono">PENDENTE</div><b className="text-2xl text-[#DFFF00]">{money(pending)}</b></div><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] text-gray-500 font-mono">PAGO</div><b className="text-2xl text-green-400">{money(paid)}</b></div></div><div className="bg-[#121414] border border-[#333] p-5 space-y-2">{payments.length===0?<div className="text-xs font-mono text-gray-500">Nenhuma cobrança cadastrada.</div>:payments.map(p=><div key={p.id} className="grid grid-cols-2 lg:grid-cols-[1.2fr_1.6fr_1fr_1fr_1fr_auto] gap-2 items-center border-b border-[#222] py-3 text-xs font-mono"><span className="text-white">{p.studentName||'Minha cobrança'}</span><span>{p.description||'Mensalidade'}</span><span>{money(Number(p.amountCents||0))}</span><span>{p.dueDate}</span><span className={p.status==='paid'?'text-green-400':p.status==='cancelled'?'text-red-400':'text-[#DFFF00]'}>{p.status==='paid'?'PAGO':p.status==='cancelled'?'CANCELADO':'PENDENTE'}</span>{userRole!=='student'&&<div className="flex gap-1">{p.status!=='paid'&&<button onClick={()=>setStatus(p.id,'paid')} className="px-2 py-1 border border-green-700 text-green-400 text-[9px]">PAGO</button>}{p.status!=='cancelled'&&<button onClick={()=>setStatus(p.id,'cancelled')} className="px-2 py-1 border border-red-900 text-red-400 text-[9px]">CANCELAR</button>}</div>}</div>)}</div></div>;
};
