import React,{useEffect,useState} from 'react';
import {ScreenView,UserRole} from '../../types';
import {api} from '../../api';

export const AssinaturaScreen:React.FC<{onNavigate:(s:ScreenView)=>void;userRole?:UserRole}>=({userRole='student'})=>{
 const [payments,setPayments]=useState<any[]>([]),[commercial,setCommercial]=useState<any>({}),[error,setError]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([api.payments(),api.commercialStatus()]).then(([r,c])=>{setPayments(r.payments||[]);setCommercial(c.status||{})}).catch((e:any)=>setError(e.message));useEffect(()=>{load()},[]);
 const pending=payments.filter(p=>p.status==='pending').reduce((a,p)=>a+Number(p.amountCents||0),0);const paid=payments.filter(p=>p.status==='paid').reduce((a,p)=>a+Number(p.amountCents||0),0);
 const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
 const setStatus=async(id:any,status:'paid'|'pending'|'cancelled')=>{try{await api.updatePaymentStatus(id,status);setMsg('Cobrança atualizada.');await load()}catch(e:any){setError(e.message)}};
 const checkout=async(gateway:'mercadopago'|'stripe',plan:'basic'|'pro'|'business')=>{setBusy(true);setError('');try{const r=await api.createBillingCheckout(gateway,plan);if(r.checkoutUrl)window.location.href=r.checkoutUrl}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const trialText=commercial.trialEndsAt?new Date(commercial.trialEndsAt).toLocaleDateString('pt-BR'):'-';
 return <div className="space-y-6">{error&&<div className="border border-red-500/40 p-3 text-red-300 text-xs">{error}</div>}{msg&&<div className="border border-[#DFFF00]/40 p-3 text-[#DFFF00] text-xs">{msg}</div>}<div><div className="text-[10px] font-mono text-[#DFFF00]">// FINANCEIRO</div><h1 className="font-anybody text-3xl font-black uppercase text-white">{userRole==='student'?'Minha Assinatura & Cobranças':'Financeiro & Cobranças'}</h1><p className="text-xs text-gray-500 mt-1">{userRole==='student'?'Acompanhe seus lançamentos e vencimentos.':'Acompanhe o plano do SaaS e as cobranças dos alunos.'}</p></div>
 {userRole==='coach'&&<section className="bg-[#121414] border border-[#333] p-5 space-y-4"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="text-[10px] font-mono text-gray-500">PLANO ATUAL</div><div className="font-anybody text-2xl font-black uppercase text-white">{commercial.planCode||'trial'} <span className="text-sm text-[#DFFF00]">{commercial.subscriptionStatus||'trialing'}</span></div><div className="text-[10px] font-mono text-gray-500">{commercial.studentsCount||0}/{commercial.studentLimit||0} alunos • trial até {trialText}</div></div>{commercial.trialExpired&&<span className="border border-red-700 text-red-400 px-3 py-2 text-[10px] font-mono">TRIAL EXPIRADO</span>}</div><div className="grid md:grid-cols-3 gap-3">{([['basic','Básico','20 alunos'],['pro','Pro','100 alunos'],['business','Business','500 alunos']] as const).map(([p,n,l])=><div key={p} className="bg-black border border-[#333] p-4"><b className="font-anybody uppercase text-white">{n}</b><div className="text-[10px] text-gray-500 mb-3">{l}</div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>checkout('mercadopago',p)} className="px-3 py-2 bg-[#DFFF00] text-black text-[10px] font-black">MERCADO PAGO</button><button disabled={busy} onClick={()=>checkout('stripe',p)} className="px-3 py-2 border border-[#555] text-white text-[10px]">STRIPE</button></div></div>)}</div><p className="text-[9px] font-mono text-gray-600">O checkout só é liberado quando a credencial do gateway estiver configurada com segurança na VPS.</p></section>}
 <div className="grid sm:grid-cols-3 gap-3"><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] text-gray-500 font-mono">LANÇAMENTOS</div><b className="text-3xl text-white">{payments.length}</b></div><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] text-gray-500 font-mono">PENDENTE</div><b className="text-2xl text-[#DFFF00]">{money(pending)}</b></div><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] text-gray-500 font-mono">PAGO</div><b className="text-2xl text-green-400">{money(paid)}</b></div></div><div className="bg-[#121414] border border-[#333] p-5 space-y-2">{payments.length===0?<div className="text-xs font-mono text-gray-500">Nenhuma cobrança cadastrada.</div>:payments.map(p=><div key={p.id} className="grid grid-cols-2 lg:grid-cols-[1.2fr_1.6fr_1fr_1fr_1fr_auto] gap-2 items-center border-b border-[#222] py-3 text-xs font-mono"><span className="text-white">{p.studentName||'Minha cobrança'}</span><span>{p.description||'Mensalidade'}</span><span>{money(Number(p.amountCents||0))}</span><span>{p.dueDate}</span><span className={p.status==='paid'?'text-green-400':p.status==='cancelled'?'text-red-400':'text-[#DFFF00]'}>{p.status==='paid'?'PAGO':p.status==='cancelled'?'CANCELADO':'PENDENTE'}</span>{userRole!=='student'&&<div className="flex gap-1">{p.status!=='paid'&&<button onClick={()=>setStatus(p.id,'paid')} className="px-2 py-1 border border-green-700 text-green-400 text-[9px]">PAGO</button>}{p.status!=='cancelled'&&<button onClick={()=>setStatus(p.id,'cancelled')} className="px-2 py-1 border border-red-900 text-red-400 text-[9px]">CANCELAR</button>}</div>}</div>)}</div></div>;
};
