import React,{useEffect,useState} from 'react';
import {ScreenView} from '../../types';
import {api,ApiUser} from '../../api';

export const AuthLoginScreen:React.FC<{onNavigate:(s:ScreenView)=>void;onLoginSuccess:(u:ApiUser)=>void}>=({onNavigate,onLoginSuccess})=>{
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[forgot,setForgot]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(location.search);const token=p.get('reset');if(token)setMsg('Link de redefinição detectado. A redefinição de senha será concluída pelo fluxo de recuperação.')},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setMsg('');try{const r=await api.login(email,password);onLoginSuccess(r.user)}catch(e:any){setMsg(e.message||'Falha no login.')}finally{setLoading(false)}};
 const recover=async()=>{try{await api.forgotPassword(email);setMsg('Se a conta existir e for administrador/treinador, enviaremos o link de recuperação.')}catch(e:any){setMsg(e.message)}};
 return <div className="min-h-[calc(100vh-4rem)] grid lg:grid-cols-2 bg-[#0A0A0A]"><div className="hidden lg:flex bg-grid-pattern border-r border-[#222] p-12 flex-col justify-between"><div><div className="text-[10px] font-mono text-[#DFFF00]">// SECURE ACCESS NODE</div><h1 className="font-anybody text-6xl font-black uppercase text-white leading-[.9] mt-5">Performance<br/><span className="text-[#DFFF00]">sem ruído.</span></h1><p className="mt-6 max-w-md text-gray-500">Uma única página de acesso. O servidor identifica automaticamente se a conta é de administrador, treinador ou aluno e libera apenas o painel permitido.</p></div><div className="font-mono text-[10px] text-gray-600 space-y-1"><div>AUTH // SERVER SIDE</div><div>SESSION // HTTPONLY</div><div>DATABASE // SQLITE</div></div></div><div className="flex items-center justify-center p-5 sm:p-10"><form onSubmit={submit} className="w-full max-w-md bg-[#121414] border border-[#333] p-6 sm:p-8 space-y-5"><div><button type="button" onClick={()=>onNavigate('landing')} className="text-[10px] font-mono text-gray-500 hover:text-white">← VOLTAR</button><h2 className="font-anybody text-3xl font-black uppercase text-white mt-4">Acessar PulseFit</h2><p className="text-xs text-gray-500 mt-1">Use o e-mail e a senha da sua conta.</p></div>{msg&&<div className="border border-[#DFFF00]/40 bg-black p-3 text-xs font-mono text-[#DFFF00]">{msg}</div>}<label className="block text-[10px] font-mono text-gray-500 uppercase">E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="mt-2 w-full bg-black border border-[#333] p-3 text-white outline-none focus:border-[#DFFF00]"/></label>{!forgot&&<label className="block text-[10px] font-mono text-gray-500 uppercase">Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required className="mt-2 w-full bg-black border border-[#333] p-3 text-white outline-none focus:border-[#DFFF00]"/></label>}{forgot?<><button type="button" onClick={recover} className="w-full py-4 bg-[#DFFF00] text-black font-anybody font-black uppercase">Enviar recuperação</button><button type="button" onClick={()=>setForgot(false)} className="w-full text-xs text-gray-500">Voltar para login</button></>:<><button disabled={loading} className="w-full py-4 bg-[#DFFF00] text-black font-anybody font-black uppercase shadow-[3px_3px_0_#fff]">{loading?'Autenticando...':'Entrar'}</button><button type="button" onClick={()=>setForgot(true)} className="w-full text-xs font-mono text-gray-500 hover:text-[#DFFF00]">Esqueci minha senha (treinador/admin)</button></>}</form></div></div>;
};
