import React,{useEffect,useState} from 'react';
import {ScreenView} from '../../types';
import {api} from '../../api';
const input='w-full bg-black border border-[#333] p-3 text-xs text-white outline-none focus:border-[#DFFF00]';
export const BrandKitScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=({onNavigate})=>{
 const [b,setB]=useState<any>({brandName:'',logoUrl:'',bannerUrl:'',primaryColor:'#DFFF00',secondaryColor:'#121414',accentColor:'#FFFFFF',theme:'dark',slogan:'',whatsapp:'',instagram:'',website:''}),[csrf,setCsrf]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([fetch('/api/coach/brand-kit',{credentials:'include'}).then(r=>r.json()),api.me()]).then(([r,m])=>{if(r.brand)setB({...b,...r.brand});setCsrf(m.csrf||'')}).catch((e:any)=>setMsg(e.message))},[]);
 const upload=async(file:File|undefined,key:'logoUrl'|'bannerUrl')=>{if(!file)return;setBusy(true);try{const r=await api.uploadMedia(file);setB((x:any)=>({...x,[key]:r.url}));setMsg('Imagem enviada. Clique em SALVAR BRAND KIT.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);setMsg('');try{const r=await fetch('/api/coach/brand-kit',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(b)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao salvar.');setB(d.brand);setMsg('Identidade visual salva e aplicada ao ambiente dos seus alunos.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const primary=b.primaryColor||'#DFFF00';
 return <div className="space-y-5">{msg&&<div className="border border-[#DFFF00]/40 bg-black p-3 text-xs text-[#DFFF00]">{msg}</div>}<div><div className="text-[10px] font-mono text-[#DFFF00]">// MINHA MARCA</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Brand Kit do Treinador</h1><p className="text-xs text-gray-500 mt-1">Personalize o ambiente do aluno sem perder a estrutura e a usabilidade do PulseFit.</p></div>
 <div className="grid xl:grid-cols-[1fr_420px] gap-5"><section className="bg-[#121414] border border-[#333] p-5 space-y-4"><div className="grid md:grid-cols-2 gap-3"><label className="text-[10px] text-gray-500">NOME DA MARCA<input className={input} value={b.brandName||''} onChange={e=>setB({...b,brandName:e.target.value})} placeholder="Ex.: MTFIT"/></label><label className="text-[10px] text-gray-500">SLOGAN<input className={input} value={b.slogan||''} onChange={e=>setB({...b,slogan:e.target.value})} placeholder="Ex.: Treino que transforma"/></label></div><div className="grid md:grid-cols-3 gap-3">{[['primaryColor','COR PRINCIPAL'],['secondaryColor','COR SECUNDÁRIA'],['accentColor','COR DE APOIO']].map(([k,l])=><label key={k} className="text-[10px] text-gray-500">{l}<div className="flex gap-2 mt-1"><input type="color" value={b[k]||'#000000'} onChange={e=>setB({...b,[k]:e.target.value.toUpperCase()})} className="w-14 h-11 bg-black border border-[#333]"/><input className={input} value={b[k]||''} onChange={e=>setB({...b,[k]:e.target.value})}/></div></label>)}</div><div className="grid md:grid-cols-2 gap-3"><label className="text-[10px] text-gray-500">LOGO<label className="mt-1 block border border-dashed border-[#444] p-4 text-center cursor-pointer hover:border-[#DFFF00]">{b.logoUrl?'TROCAR LOGO':'ENVIAR LOGO'}<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0],'logoUrl')}/></label></label><label className="text-[10px] text-gray-500">BANNER / CAPA<label className="mt-1 block border border-dashed border-[#444] p-4 text-center cursor-pointer hover:border-[#DFFF00]">{b.bannerUrl?'TROCAR BANNER':'ENVIAR BANNER'}<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0],'bannerUrl')}/></label></label></div><div className="grid md:grid-cols-3 gap-3"><input className={input} value={b.whatsapp||''} onChange={e=>setB({...b,whatsapp:e.target.value})} placeholder="WhatsApp"/><input className={input} value={b.instagram||''} onChange={e=>setB({...b,instagram:e.target.value})} placeholder="Instagram"/><input className={input} value={b.website||''} onChange={e=>setB({...b,website:e.target.value})} placeholder="Site"/></div><div className="flex gap-2"><button disabled={busy} onClick={save} className="px-5 py-3 bg-[#DFFF00] text-black text-xs font-black">SALVAR BRAND KIT</button><button onClick={()=>onNavigate('coach_dashboard')} className="px-5 py-3 border border-[#444] text-xs">VOLTAR</button></div></section>
 <aside className="bg-[#0a0a0a] border border-[#333] overflow-hidden"><div className="h-36 bg-[#181818] bg-cover bg-center" style={{backgroundImage:b.bannerUrl?`url(${b.bannerUrl})`:undefined}}/><div className="p-5 -mt-10 relative"><div className="w-20 h-20 bg-black border-2 grid place-items-center overflow-hidden" style={{borderColor:primary}}>{b.logoUrl?<img src={b.logoUrl} className="w-full h-full object-contain"/>:<b style={{color:primary}}>LOGO</b>}</div><h3 className="font-anybody text-2xl font-black uppercase text-white mt-3">{b.brandName||'SUA MARCA'}</h3><p className="text-xs text-gray-400">{b.slogan||'Sua identidade no ambiente do aluno.'}</p><button className="w-full py-3 mt-5 text-black font-black text-xs" style={{backgroundColor:primary}}>EXEMPLO DE BOTÃO</button></div></aside></div></div>;
};
