import React,{useEffect,useMemo,useState} from 'react';
import {ScreenView,Student} from '../../types';
import {api,normalizeStudent} from '../../api';
const input='bg-black border border-[#333] p-2.5 text-xs text-white outline-none focus:border-[#DFFF00]';
export const CoachDashboardScreen:React.FC<{onNavigate:(s:ScreenView)=>void;onSelectStudent:(s:Student)=>void}>=({onNavigate,onSelectStudent})=>{
 const [students,setStudents]=useState<Student[]>([]),[dash,setDash]=useState<any>({}),[alerts,setAlerts]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]),[library,setLibrary]=useState<any[]>([]),[commercial,setCommercial]=useState<any>({}),[q,setQ]=useState(''),[status,setStatus]=useState(''),[financial,setFinancial]=useState(''),[workout,setWorkout]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[showNew,setShowNew]=useState(false),[showTemplate,setShowTemplate]=useState(false);
 const [form,setForm]=useState<any>({name:'',email:'',programName:'Programa inicial',phase:'Fase 1',planName:'',password:''});const [template,setTemplate]=useState<any>({name:'',description:'',exerciseId:''});
 const load=async()=>{try{const [s,d,a,t,l,c]=await Promise.all([api.students(),api.dashboard(),api.alerts(),api.workoutTemplates(),api.exerciseLibrary(),api.commercialStatus()]);setStudents((s.students||[]).map(normalizeStudent));setDash(d);setAlerts(a.alerts||[]);setTemplates(t.templates||[]);setLibrary(l.exercises||[]);setCommercial(c.status||{})}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const act=async(fn:()=>Promise<any>,ok='Concluído.')=>{setBusy(true);setMsg('');try{const r=await fn();setMsg(r?.temporaryPassword?`${ok} Senha temporária: ${r.temporaryPassword}`:ok);await load();return r}catch(e:any){setMsg(e.message);return null}finally{setBusy(false)}};
 const filtered=useMemo(()=>students.filter((s:any)=>(!q||`${s.name} ${s.email} ${s.programName}`.toLowerCase().includes(q.toLowerCase()))&&(!status||s.status===status)&&(!financial||financial!=='overdue'||s.hasOverduePayment)&&(!workout||workout!=='late'||s.workoutLate)),[students,q,status,financial,workout]);
 const open=(s:Student,screen:ScreenView)=>{onSelectStudent(s);onNavigate(screen)};
 const createTemplate=async()=>{const ex=library.find((x:any)=>String(x.id)===String(template.exerciseId));if(!ex){setMsg('Escolha ao menos um exercício para o modelo.');return}const r=await act(()=>api.createWorkoutTemplate({name:template.name,description:template.description,exercises:[ex]}),'Modelo criado.');if(r)setTemplate({name:'',description:'',exerciseId:''})};
 const createStudent=async()=>{const r=await act(()=>api.createStudent({...form,password:form.password||undefined}),'Aluno criado.');if(!r?.ok&&!r?.id)return;setForm({name:'',email:'',programName:'Programa inicial',phase:'Fase 1',planName:'',password:''});setShowNew(false)};
 const steps=['Complete seu perfil profissional','Cadastre seu primeiro aluno','Crie ou revise sua biblioteca','Monte a primeira prescrição','Configure agenda e financeiro'];const current=Math.min(Number(commercial.onboardingStep||0),steps.length);
 const advance=()=>act(()=>api.updateOnboarding(Math.min(current+1,5),current+1>=5),current+1>=5?'Onboarding concluído.':'Etapa concluída.');
 return <div className="space-y-5">{msg&&<div className="sticky top-16 z-20 bg-black border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}<div className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><div className="text-[10px] font-mono text-[#DFFF00]">// COACH COMMAND CENTER</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Dashboard do Treinador</h1><div className="text-[10px] font-mono text-gray-500 mt-1">Plano {String(commercial.planCode||'trial').toUpperCase()} • {commercial.studentsCount||0}/{commercial.studentLimit||0} alunos {commercial.trialEndsAt&&`• trial até ${new Date(commercial.trialEndsAt).toLocaleDateString('pt-BR')}`}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowNew(!showNew)} className="px-4 py-3 border border-[#DFFF00] text-[#DFFF00] text-xs font-bold">+ NOVO ALUNO</button><button onClick={()=>setShowTemplate(!showTemplate)} className="px-4 py-3 border border-[#333] text-xs">MODELOS</button><button onClick={()=>onNavigate('prescription')} className="px-4 py-3 bg-[#DFFF00] text-black text-xs font-black">NOVA PRESCRIÇÃO</button></div></div>
 {!commercial.onboardingCompletedAt&&<section className="bg-[#121414] border border-[#DFFF00]/40 p-4"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="text-[10px] font-mono text-[#DFFF00]">ONBOARDING {current}/5</div><h2 className="font-anybody font-black uppercase text-white">{steps[current]||'Tudo pronto'}</h2><div className="w-full max-w-lg h-1 bg-[#222] mt-3"><div className="h-1 bg-[#DFFF00]" style={{width:`${current*20}%`}}/></div></div><button disabled={busy} onClick={advance} className="px-4 py-3 bg-[#DFFF00] text-black text-xs font-black">{current>=4?'CONCLUIR':'CONCLUIR ETAPA'}</button></div></section>}
 {commercial.trialExpired&&<div className="border border-red-700 bg-red-950/20 p-4 text-red-300 text-xs">Seu período de teste expirou. A criação de novos alunos fica bloqueada até ativar um plano. <button onClick={()=>onNavigate('assinatura')} className="ml-2 underline font-bold">Ver planos</button></div>}
 <div className="grid sm:grid-cols-3 gap-3"><Card l="Alunos ativos" v={dash.activeStudents||0}/><Card l="Total alunos" v={dash.totalStudents||students.length}/><Card l="Alertas" v={alerts.length}/></div>
 {alerts.length>0&&<section className="bg-[#121414] border border-[#333] p-4"><h2 className="font-anybody font-black uppercase text-white mb-3">Alertas inteligentes</h2><div className="grid md:grid-cols-2 gap-2">{alerts.slice(0,12).map((a:any,i)=><button key={i} onClick={()=>{const s=students.find(x=>String(x.id)===String(a.studentId));if(s)open(s,'student_detail')}} className="text-left bg-black border border-[#333] p-3 hover:border-[#DFFF00] text-xs"><b className={a.severity==='critical'?'text-red-400':'text-[#DFFF00]'}>{a.studentName}</b><div className="text-gray-400">{a.message}</div></button>)}</div></section>}
 {showNew&&<section className="bg-[#121414] border-2 border-[#DFFF00] p-4 grid md:grid-cols-3 gap-2"><input className={input} placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={input} placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className={input} placeholder="Programa" value={form.programName} onChange={e=>setForm({...form,programName:e.target.value})}/><input className={input} placeholder="Fase" value={form.phase} onChange={e=>setForm({...form,phase:e.target.value})}/><input className={input} placeholder="Plano" value={form.planName} onChange={e=>setForm({...form,planName:e.target.value})}/><input className={input} type="password" placeholder="Senha inicial (opcional)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button disabled={busy} onClick={createStudent} className="md:col-span-3 bg-[#DFFF00] text-black p-3 text-xs font-black">{busy?'CRIANDO...':'CRIAR ALUNO'}</button></section>}
 {showTemplate&&<section className="bg-[#121414] border border-[#333] p-4 space-y-3"><div className="flex items-center justify-between"><h2 className="font-anybody font-black uppercase text-white">Modelos de treino</h2><span className="text-[10px] text-gray-500">Crie uma vez e aplique em vários alunos</span></div><div className="grid md:grid-cols-4 gap-2"><input className={input} placeholder="Nome do modelo" value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/><input className={input} placeholder="Descrição" value={template.description} onChange={e=>setTemplate({...template,description:e.target.value})}/><select className={input} value={template.exerciseId} onChange={e=>setTemplate({...template,exerciseId:e.target.value})}><option value="">Exercício base</option>{library.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={createTemplate} className="bg-[#DFFF00] text-black text-xs font-bold">CRIAR MODELO</button></div><div className="space-y-2">{templates.map((t:any)=><div key={t.id} className="bg-black border border-[#333] p-3 flex flex-col lg:flex-row lg:items-center gap-2"><div className="flex-1"><b>{t.name}</b><div className="text-[10px] text-gray-500">{t.description||'Sem descrição'} • {t.exercises?.length||0} exercício(s)</div></div><select defaultValue="" onChange={e=>e.target.value&&act(()=>api.applyWorkoutTemplate(t.id,e.target.value),'Modelo aplicado como rascunho.')} className={input}><option value="">APLICAR AO ALUNO...</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={()=>confirm('Excluir modelo?')&&act(()=>api.deleteWorkoutTemplate(t.id),'Modelo excluído.')} className="px-3 py-2 border border-red-900 text-red-400 text-[10px]">EXCLUIR</button></div>)}{!templates.length&&<div className="text-xs text-gray-500">Nenhum modelo ainda.</div>}</div></section>}
 <div className="grid md:grid-cols-4 gap-2 bg-[#121414] border border-[#333] p-3"><input className={input} placeholder="Buscar aluno..." value={q} onChange={e=>setQ(e.target.value)}/><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos status</option><option value="active">Ativos</option><option value="expired">Inativos</option></select><select className={input} value={financial} onChange={e=>setFinancial(e.target.value)}><option value="">Financeiro</option><option value="overdue">Inadimplentes</option></select><select className={input} value={workout} onChange={e=>setWorkout(e.target.value)}><option value="">Treinos</option><option value="late">Treino atrasado</option></select></div>
 <section className="bg-[#121414] border border-[#333] p-4 space-y-2"><h2 className="font-anybody font-black uppercase text-white">Meus alunos</h2>{filtered.map((s:any)=><div key={s.id} className="bg-black border border-[#2a2a2a] p-3 flex flex-col xl:flex-row xl:items-center gap-2"><div className="flex-1"><b className="text-white">{s.name}</b><div className="text-[10px] text-gray-500">{s.programName} • {s.phase} • {s.hasOverduePayment?'pagamento vencido':'financeiro ok'} • {s.workoutLate?'treino atrasado':'treino em dia'} • {s.checkinPending?'check-in pendente':'check-in ok'}</div></div><div className="flex flex-wrap gap-1"><button onClick={()=>open(s,'student_detail')} className="px-3 py-2 bg-[#DFFF00] text-black text-[10px] font-bold">ABRIR FICHA</button><button onClick={()=>open(s,'prescription')} className="px-3 py-2 border border-[#333] text-[10px]">PRESCREVER</button><button onClick={()=>act(()=>api.resetStudentAccess(s.id),'Senha redefinida.')} className="px-3 py-2 border border-[#333] text-[10px]">RESETAR SENHA</button><button onClick={()=>confirm('Arquivar aluno?')&&act(()=>api.archiveStudent(s.id),'Aluno arquivado.')} className="px-3 py-2 border border-[#333] text-[10px]">ARQUIVAR</button></div></div>)}{!filtered.length&&<div className="p-8 text-center text-xs text-gray-500">Nenhum aluno encontrado.</div>}</section></div>;
};
const Card=({l,v}:{l:string;v:any})=><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[9px] text-gray-500 uppercase">{l}</div><b className="text-3xl text-[#DFFF00]">{v}</b></div>;
