import React,{useEffect,useState} from 'react';
import {ScreenView,UserRole} from '../../types';
import {api} from '../../api';
const box='bg-[#121414] border border-[#333] p-4';
export const GamificationRankingScreen:React.FC<{onNavigate:(s:ScreenView)=>void;userRole:UserRole}>=({userRole})=>{
 const [data,setData]=useState<any>({enabled:false,metric:'xp',ranking:[]}),[enabled,setEnabled]=useState(false),[metric,setMetric]=useState('xp'),[csrf,setCsrf]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{try{const r=await fetch('/api/ranking',{credentials:'include'});if(r.ok){const d=await r.json();setData(d);setEnabled(!!d.enabled);setMetric(d.metric||'xp')}}catch{}};
 useEffect(()=>{api.me().then(r=>setCsrf(r.csrf||''));load()},[]);
 const save=async()=>{const r=await fetch('/api/ranking/settings',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({enabled,metric})});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||'Falha ao salvar.');return}setMsg('Configuração do ranking atualizada.');load()};
 const label=(m:string)=>m==='frequency'?'Frequência':m==='tonnage'?'Tonelagem':'XP';
 return <div className="space-y-5"><div><div className="text-[10px] font-mono text-[#DFFF00]">// GAMIFICAÇÃO</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Ranking & Conquistas</h1><p className="text-xs text-gray-500">Ranking opcional por treinador, sem expor dados de outras equipes.</p></div>{msg&&<div className="border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}{userRole==='coach'&&<section className={`${box} flex flex-col lg:flex-row lg:items-end gap-3`}><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Ativar ranking para meus alunos</label><select value={metric} onChange={e=>setMetric(e.target.value)} className="bg-black border border-[#333] p-3 text-xs"><option value="xp">XP</option><option value="frequency">Frequência</option><option value="tonnage">Tonelagem</option></select><button onClick={save} className="bg-[#DFFF00] text-black px-5 py-3 text-xs font-black">SALVAR</button></section>}<section className={box}><div className="flex justify-between gap-3 mb-4"><div><h2 className="font-anybody font-black uppercase text-white">Classificação 30 dias</h2><div className="text-[10px] text-gray-500">Critério: {label(data.metric||metric)}</div></div><span className={data.enabled?'text-green-400 text-xs':'text-yellow-400 text-xs'}>{data.enabled?'ATIVO':'DESATIVADO'}</span></div>{!data.enabled&&userRole==='student'?<div className="text-xs text-gray-500">Seu treinador não ativou o ranking.</div>:<div className="space-y-2">{(data.ranking||[]).map((x:any,i:number)=><div key={x.id} className="bg-black border border-[#333] p-4 flex items-center gap-4"><div className={`w-10 h-10 grid place-items-center font-black ${i<3?'bg-[#DFFF00] text-black':'border border-[#444] text-gray-400'}`}>{i+1}</div><div className="flex-1"><b className="text-white">{x.name}</b><div className="text-[10px] text-gray-500">{x.sessions} treinos • {Math.round(Number(x.volume||0))} kg de volume</div></div><b className="text-[#DFFF00]">{data.metric==='frequency'?`${x.sessions} treinos`:data.metric==='tonnage'?`${Math.round(Number(x.volume||0))} kg`:`${Math.round(Number(x.xp||0))} XP`}</b></div>)}{!(data.ranking||[]).length&&<div className="text-xs text-gray-600">Ainda não há dados suficientes para o ranking.</div>}</div>}</section></div>;
};