import React,{useEffect,useState} from 'react';
import {ScreenView} from '../../types';
import {api} from '../../api';
const input='w-full bg-black border border-[#333] p-3 text-xs text-white outline-none focus:border-[#DFFF00]';
export const GrowthScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=()=>{
 const [profile,setProfile]=useState<any>({slug:'',headline:'',bio:'',photoUrl:'',whatsapp:'',city:'',state:'',services:[],publicEnabled:false}),[leads,setLeads]=useState<any[]>([]),[insights,setInsights]=useState<any>({}),[pwa,setPwa]=useState<any>({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [p,l,i,w]=await Promise.all([api.coachPublicProfile(),api.coachLeads(),api.coachInsights(),api.pwaStatus()]);setProfile((x:any)=>({...x,...(p.profile||{})}));setLeads(l.leads||[]);setInsights(i||{});setPwa(w||{})}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const save=async()=>{setBusy(true);setMsg('');try{const r=await api.saveCoachPublicProfile({...profile,services:Array.isArray(profile.services)?profile.services:String(profile.services||'').split(',').map((x:string)=>x.trim()).filter(Boolean)});setProfile((x:any)=>({...x,slug:r.slug}));setMsg('Perfil público atualizado.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const updateLead=async(id:any,status:string)=>{try{await api.updateLead(id,{status});setMsg('Lead atualizado.');await load()}catch(e:any){setMsg(e.message)}};
 const convert=async(l:any)=>{if(!l.email){setMsg('Este lead precisa de um e-mail válido antes da conversão.');return}if(!confirm(`Converter ${l.name} em aluno?`))return;setBusy(true);setMsg('');try{const r=await api.convertLead(l.id,{programName:'Acompanhamento',phase:'Fase 1'});setMsg(`Lead convertido em aluno. Senha temporária: ${r.temporaryPassword}${r.emailSent?' • e-mail enviado':''}`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const publicLink=profile.slug?`${window.location.origin}/?coach=${encodeURIComponent(profile.slug)}`:'';
 return <div className="space-y-5">{msg&&<div className="border border-[#DFFF00]/40 bg-black p-3 text-xs text-[#DFFF00]">{msg}</div>}<div><div className="text-[10px] font-mono text-[#DFFF00]">// GROWTH & CRM</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Crescimento do Treinador</h1><p className="text-xs text-gray-500 mt-1">Página pública, leads e indicadores comerciais do seu acompanhamento.</p></div>
 <div className="grid sm:grid-cols-4 gap-3"><Card l="Alunos" v={insights.totalStudents||0}/><Card l="Treinaram 7d" v={insights.trainedThisWeek||0}/><Card l="Alcance semanal" v={`${insights.weeklyReach||0}%`}/><Card l="Vencidos" v={insights.overduePayments||0}/></div>
 <div className="grid xl:grid-cols-[420px_1fr] gap-5"><section className="bg-[#121414] border border-[#333] p-5 space-y-3"><div className="flex justify-between gap-3"><h2 className="font-anybody font-black uppercase text-white">Página pública</h2><label className="text-[10px] text-gray-400 flex items-center gap-2"><input type="checkbox" checked={!!profile.publicEnabled} onChange={e=>setProfile({...profile,publicEnabled:e.target.checked})}/> PUBLICADA</label></div><input className={input} placeholder="Slug / endereço" value={profile.slug||''} onChange={e=>setProfile({...profile,slug:e.target.value})}/><input className={input} placeholder="Título profissional" value={profile.headline||''} onChange={e=>setProfile({...profile,headline:e.target.value})}/><textarea className={`${input} min-h-28`} placeholder="Bio profissional" value={profile.bio||''} onChange={e=>setProfile({...profile,bio:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className={input} placeholder="Cidade" value={profile.city||''} onChange={e=>setProfile({...profile,city:e.target.value})}/><input className={input} placeholder="UF" value={profile.state||''} onChange={e=>setProfile({...profile,state:e.target.value})}/></div><input className={input} placeholder="WhatsApp" value={profile.whatsapp||''} onChange={e=>setProfile({...profile,whatsapp:e.target.value})}/><input className={input} placeholder="Serviços, separados por vírgula" value={Array.isArray(profile.services)?profile.services.join(', '):profile.services||''} onChange={e=>setProfile({...profile,services:e.target.value})}/><button disabled={busy} onClick={save} className="w-full bg-[#DFFF00] text-black py-3 font-anybody font-black text-xs">{busy?'SALVANDO...':'SALVAR PÁGINA PÚBLICA'}</button>{publicLink&&<div className="bg-black border border-[#333] p-3 text-[10px] break-all"><div className="text-gray-500 mb-1">LINK PÚBLICO</div><button onClick={()=>navigator.clipboard?.writeText(publicLink).then(()=>setMsg('Link copiado.'))} className="text-[#DFFF00] text-left">{publicLink}</button></div>}<div className="text-[10px] text-gray-600">PWA instalável: {pwa.installable?'sim':'não'} • Push configurado: {pwa.pushConfigured?'sim':'não'} • HTTPS necessário para push.</div></section>
 <section className="bg-[#121414] border border-[#333] p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-anybody font-black uppercase text-white">CRM de Leads</h2><span className="text-[10px] text-[#DFFF00]">{leads.length} LEADS</span></div><div className="space-y-2">{leads.length===0?<div className="border border-dashed border-[#333] p-10 text-center text-xs text-gray-500">Nenhum lead ainda. Publique seu perfil para começar a captar.</div>:leads.map((l:any)=><div key={l.id} className="bg-black border border-[#333] p-4 flex flex-col lg:flex-row lg:items-center gap-3"><div className="flex-1"><b className="text-white">{l.name}</b><div className="text-[10px] text-gray-500">{l.email||'-'} • {l.phone||'-'} • {l.source}</div><div className="text-xs text-gray-400 mt-1">{l.goal||'Objetivo não informado'}</div>{l.convertedStudentId&&<div className="text-[9px] text-green-400 mt-1">CONVERTIDO EM ALUNO #{l.convertedStudentId}</div>}</div><div className="flex gap-2"><select className="bg-black border border-[#333] p-2 text-[10px] text-white" value={l.status} onChange={e=>updateLead(l.id,e.target.value)}><option value="new">NOVO</option><option value="contacted">CONTATADO</option><option value="qualified">QUALIFICADO</option><option value="won">GANHO</option><option value="lost">PERDIDO</option></select>{!l.convertedStudentId&&<button disabled={busy} onClick={()=>convert(l)} className="px-3 py-2 bg-[#DFFF00] text-black text-[10px] font-black">CONVERTER EM ALUNO</button>}</div></div>)}</div></section></div></div>;
};
const Card=({l,v}:{l:string;v:any})=><div className="bg-[#121414] border border-[#333] p-4"><div className="text-[9px] text-gray-500 uppercase">{l}</div><b className="text-2xl text-[#DFFF00]">{v}</b></div>;