import React from 'react';
import { ScreenView } from '../../types';
import { APP_IMAGES } from '../../data/mockData';

export const LandingScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=({onNavigate})=>
<div className="min-h-[calc(100vh-4rem)] bg-[#0A0A0A]">
  <section className="relative overflow-hidden border-b border-[#222] bg-grid-pattern">
    <div className="max-w-7xl mx-auto px-5 sm:px-8 py-16 lg:py-24 grid lg:grid-cols-2 gap-10 items-center">
      <div className="space-y-7"><div className="inline-flex items-center gap-2 border border-[#DFFF00] px-3 py-1 text-[10px] font-mono font-bold text-[#DFFF00] uppercase">● Sistema de performance para treinadores</div><h1 className="font-anybody text-5xl sm:text-6xl xl:text-7xl font-black uppercase leading-[.9] text-white">Treino.<br/><span className="text-[#DFFF00]">Dados.</span><br/>Evolução.</h1><p className="max-w-xl text-gray-400 text-base leading-relaxed">Prescrição visual, biblioteca de exercícios, execução de séries, evolução física, anamnese, chat, agenda e gestão em uma única plataforma.</p><div className="flex flex-wrap gap-3"><button onClick={()=>onNavigate('auth_login')} className="btn-brutal-primary px-7 py-4 font-anybody uppercase text-sm">Entrar no PulseFit</button></div><div className="grid grid-cols-3 gap-3 pt-5 border-t border-[#222]"><div><b className="text-2xl text-white font-anybody">100%</b><span className="block text-[9px] font-mono text-gray-500 uppercase">Dados reais</span></div><div><b className="text-2xl text-white font-anybody">React</b><span className="block text-[9px] font-mono text-gray-500 uppercase">Frontend</span></div><div><b className="text-2xl text-[#DFFF00] font-anybody">SQLite</b><span className="block text-[9px] font-mono text-gray-500 uppercase">Persistência</span></div></div></div>
      <div className="relative"><div className="absolute -inset-3 border border-[#DFFF00]/20 translate-x-3 translate-y-3"></div><div className="relative bg-[#121414] border border-[#333] p-3"><img src={APP_IMAGES.landingCoach} alt="PulseFit" className="w-full aspect-[4/5] object-cover grayscale contrast-110"/><div className="absolute bottom-7 left-7 right-7 bg-black/90 border-l-4 border-[#DFFF00] p-4"><div className="text-[10px] font-mono text-[#DFFF00]">PULSEFIT // PERFORMANCE OS</div><div className="font-anybody font-black uppercase text-2xl text-white">Seu método. Sua marca. Seus alunos.</div></div></div></div>
    </div>
  </section>
  <section className="max-w-7xl mx-auto px-5 sm:px-8 py-16"><div className="mb-8"><div className="text-[10px] font-mono text-[#DFFF00]">// ECOSSISTEMA COMPLETO</div><h2 className="font-anybody text-3xl sm:text-4xl font-black uppercase text-white">Do planejamento à execução</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[['fitness_center','Biblioteca','Exercícios com foto, GIF ou vídeo e cadastro personalizado.'],['edit_note','Prescrição','Ficha visual com séries, reps, carga, descanso, RPE e tempo.'],['monitoring','Evolução','Métricas, fotos, volume e histórico de treinos.'],['forum','Relacionamento','Chat, agenda, notificações, anamnese e cobranças.']].map(([i,t,d])=><div key={t} className="bg-[#121414] border border-[#333] p-5 hover:border-[#DFFF00] transition-colors"><span className="material-symbols-outlined text-[#DFFF00] text-3xl">{i}</span><h3 className="font-anybody font-black uppercase text-white mt-4">{t}</h3><p className="text-xs text-gray-500 mt-2 leading-relaxed">{d}</p></div>)}</div></section>
</div>;
