import React,{useEffect,useMemo,useState} from 'react';
import {ScreenView,Student,UserRole} from '../../types';
import {api} from '../../api';
import {PosturalBody3D} from '../PosturalBody3D';
const box='bg-[#121414] border border-[#333] p-4';
const input='w-full bg-black border border-[#333] p-2.5 text-xs text-white outline-none focus:border-[#DFFF00]';
type Angles={headTiltDeg:number;shoulderTiltDeg:number;pelvicTiltDeg:number;trunkLeanDeg:number;kneeAlignmentLeftDeg:number;kneeAlignmentRightDeg:number};
const EMPTY:Angles={headTiltDeg:0,shoulderTiltDeg:0,pelvicTiltDeg:0,trunkLeanDeg:0,kneeAlignmentLeftDeg:0,kneeAlignmentRightDeg:0};
const labels:Record<keyof Angles,string>={headTiltDeg:'Inclinação da cabeça',shoulderTiltDeg:'Inclinação dos ombros',pelvicTiltDeg:'Inclinação pélvica',trunkLeanDeg:'Inclinação do tronco',kneeAlignmentLeftDeg:'Alinhamento joelho E',kneeAlignmentRightDeg:'Alinhamento joelho D'};
export const PosturalAssessmentScreen:React.FC<{onNavigate:(s:ScreenView)=>void;selectedStudent:Student;userRole:UserRole}>=({selectedStudent,userRole})=>{
 const [view,setView]=useState('global'),[score,setScore]=useState(80),[notes,setNotes]=useState(''),[plan,setPlan]=useState(''),[finding,setFinding]=useState(''),[findings,setFindings]=useState<string[]>([]),[angles,setAngles]=useState<Angles>(EMPTY),[history,setHistory]=useState<any[]>([]),[csrf,setCsrf]=useState(''),[msg,setMsg]=useState('');
 const sid=userRole==='coach'?selectedStudent.id:undefined;
 const load=async()=>{try{const q=sid?`?studentId=${encodeURIComponent(String(sid))}`:'';const r=await fetch(`/api/postural-assessments${q}`,{credentials:'include'});if(r.ok){const d=await r.json();setHistory(d.assessments||[])}}catch{}};
 useEffect(()=>{api.me().then(r=>setCsrf(r.csrf||''));load()},[selectedStudent.id]);
 useEffect(()=>{setAngles(EMPTY);setFindings([]);setNotes('');setPlan('');setScore(80)},[selectedStudent.id]);
 const add=()=>{const f=finding.trim();if(f){setFindings(v=>[...v,f]);setFinding('')}};
 const save=async()=>{if(userRole!=='coach'||!sid)return;const r=await fetch('/api/postural-assessments',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({studentId:Number(sid),viewType:view,findings,angles,notes,correctivePlan:plan,score})});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||'Falha ao salvar.');return}setMsg('Avaliação postural salva com ângulos e mapa corporal.');setFindings([]);setNotes('');setPlan('');load()};
 const latest=history[0],previous=history[1];
 const comparison=useMemo(()=>{if(!latest||!previous)return[];const a=latest.angles||{},b=previous.angles||{};return (Object.keys(labels) as (keyof Angles)[]).map(k=>({key:k,label:labels[k],now:Number(a[k]||0),before:Number(b[k]||0),delta:Number((Number(a[k]||0)-Number(b[k]||0)).toFixed(1))}))},[latest,previous]);
 const setAngle=(k:keyof Angles,v:string)=>setAngles(a=>({...a,[k]:Math.max(-45,Math.min(45,Number(v)||0))}));
 return <div className="space-y-5"><div><div className="text-[10px] font-mono text-[#DFFF00]">// BIOMECÂNICA APLICADA</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Avaliação Postural 3D</h1><p className="text-xs text-gray-500">Registre observações e medidas angulares; o mapa 3D representa visualmente os dados informados.</p></div>{msg&&<div className="border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}
 <div className="grid xl:grid-cols-[.9fr_1.1fr] gap-4"><section className={`${box} space-y-4`}><h2 className="font-anybody font-black uppercase text-white">Nova avaliação</h2>{userRole==='coach'?<><div className="text-xs text-gray-500">Aluno: <b className="text-white">{selectedStudent.name||'Selecione um aluno'}</b></div><select value={view} onChange={e=>setView(e.target.value)} className={input}><option value="global">Global</option><option value="anterior">Anterior</option><option value="posterior">Posterior</option><option value="lateral_direita">Lateral direita</option><option value="lateral_esquerda">Lateral esquerda</option></select>
 <div><div className="text-[10px] text-[#DFFF00] mb-2">MEDIDAS ANGULARES (°)</div><div className="grid sm:grid-cols-2 gap-2">{(Object.keys(labels) as (keyof Angles)[]).map(k=><label key={k} className="text-[10px] text-gray-500">{labels[k]}<input type="number" min={-45} max={45} step="0.5" value={angles[k]} onChange={e=>setAngle(k,e.target.value)} className={`${input} mt-1`}/></label>)}</div><div className="text-[9px] text-gray-600 mt-2">Use sinal positivo/negativo conforme a convenção adotada pelo profissional e mantenha o mesmo padrão entre avaliações.</div></div>
 <label className="block text-[10px] text-gray-500">Score global 0–100<input type="range" min={0} max={100} value={score} onChange={e=>setScore(Number(e.target.value))} className="w-full"/><b className="text-[#DFFF00] text-xl">{score}/100</b></label><div className="flex gap-2"><input value={finding} onChange={e=>setFinding(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Adicionar achado observacional" className={`flex-1 ${input}`}/><button onClick={add} className="px-4 bg-[#DFFF00] text-black font-black">+</button></div><div className="flex flex-wrap gap-2">{findings.map((f,i)=><button key={i} onClick={()=>setFindings(v=>v.filter((_,x)=>x!==i))} className="border border-[#444] px-3 py-2 text-[10px]">{f} ×</button>)}</div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações da avaliação" className={`${input} min-h-24`}/><textarea value={plan} onChange={e=>setPlan(e.target.value)} placeholder="Plano de acompanhamento / exercícios corretivos" className={`${input} min-h-24`}/><button onClick={save} disabled={!sid} className="w-full bg-[#DFFF00] text-black p-3 text-xs font-black disabled:opacity-40">SALVAR AVALIAÇÃO COMPLETA</button></>:<div className="text-xs text-gray-500">Aqui você acompanha somente as avaliações registradas no seu perfil.</div>}</section>
 <section className={`${box} space-y-3`}><div className="flex items-end justify-between gap-3"><div><div className="text-[10px] text-[#DFFF00]">MAPA CORPORAL 3D</div><h2 className="font-anybody font-black uppercase text-white">Visualização postural</h2></div><button onClick={()=>window.print()} className="border border-[#DFFF00] text-[#DFFF00] px-3 py-2 text-[10px] font-black">SALVAR PDF</button></div><PosturalBody3D angles={userRole==='coach'?angles:(latest?.angles||EMPTY)}/></section></div>
 {comparison.length>0&&<section className={box}><div className="flex justify-between gap-3 items-end"><div><div className="text-[10px] text-[#DFFF00]">COMPARAÇÃO</div><h2 className="font-anybody font-black uppercase text-white">Última avaliação × anterior</h2></div><div className="text-[10px] text-gray-500">Δ em graus</div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-3">{comparison.map(c=><div key={c.key} className="bg-black border border-[#333] p-3"><div className="text-[9px] text-gray-500 uppercase">{c.label}</div><div className="flex items-baseline justify-between mt-1"><b className="text-white">{c.now}°</b><span className={c.delta===0?'text-gray-500':Math.abs(c.delta)<Math.abs(c.before)?'text-green-400':'text-yellow-300'}>{c.delta>0?'+':''}{c.delta}°</span></div><div className="text-[9px] text-gray-600">Anterior: {c.before}°</div></div>)}</div></section>}
 <section className={box}><h2 className="font-anybody font-black uppercase text-white mb-3">Histórico</h2><div className="space-y-2">{history.map(h=><div key={h.id} className="bg-black border border-[#333] p-4"><div className="flex justify-between gap-2"><b className="text-white uppercase">{h.viewType} • {h.score==null?'-':`${h.score}/100`}</b><span className="text-[10px] text-gray-600">{new Date(h.createdAt).toLocaleString('pt-BR')}</span></div><div className="grid sm:grid-cols-3 gap-1 mt-2">{Object.entries(h.angles||{}).map(([k,v])=><div key={k} className="text-[9px] text-gray-500">{labels[k as keyof Angles]||k}: <b className="text-gray-300">{String(v)}°</b></div>)}</div><div className="flex flex-wrap gap-1 mt-2">{(h.findings||[]).map((f:string,i:number)=><span key={i} className="border border-[#444] px-2 py-1 text-[9px] text-gray-400">{f}</span>)}</div>{h.notes&&<p className="text-xs text-gray-400 mt-2">{h.notes}</p>}{h.correctivePlan&&<p className="text-xs text-[#DFFF00] mt-2">Plano: {h.correctivePlan}</p>}</div>)}{!history.length&&<div className="text-xs text-gray-600">Nenhum registro ainda.</div>}</div></section></div>;
};
