import React,{useEffect,useMemo,useState} from 'react';
import {ScreenView,Student,UserRole} from '../../types';
import {api} from '../../api';
import {PosturalBody3D} from '../PosturalBody3D';
const box='bg-[#121414] border border-[#333] p-4';
const input='w-full bg-black border border-[#333] p-2.5 text-xs text-white outline-none focus:border-[#DFFF00]';
type Angles={headTiltDeg:number;shoulderTiltDeg:number;pelvicTiltDeg:number;trunkLeanDeg:number;kneeAlignmentLeftDeg:number;kneeAlignmentRightDeg:number};
type AngleDraft=Record<keyof Angles,string>;
type Mode='assessment'|'viewer'|'history';
const EMPTY:Angles={headTiltDeg:0,shoulderTiltDeg:0,pelvicTiltDeg:0,trunkLeanDeg:0,kneeAlignmentLeftDeg:0,kneeAlignmentRightDeg:0};
const EMPTY_DRAFT:AngleDraft={headTiltDeg:'',shoulderTiltDeg:'',pelvicTiltDeg:'',trunkLeanDeg:'',kneeAlignmentLeftDeg:'',kneeAlignmentRightDeg:''};
const labels:Record<keyof Angles,string>={headTiltDeg:'Inclinação da cabeça',shoulderTiltDeg:'Inclinação dos ombros',pelvicTiltDeg:'Inclinação pélvica',trunkLeanDeg:'Inclinação do tronco',kneeAlignmentLeftDeg:'Alinhamento joelho E',kneeAlignmentRightDeg:'Alinhamento joelho D'};
const normalizeAngle=(raw:string)=>{const clean=raw.trim().replace(',','.');if(clean===''||clean==='-'||clean==='.'||clean==='-.')return 0;const n=Number(clean);if(!Number.isFinite(n))return 0;return Math.max(-45,Math.min(45,Math.round(n*10)/10));};
export const PosturalAssessmentScreen:React.FC<{onNavigate:(s:ScreenView)=>void;selectedStudent:Student;userRole:UserRole}>=({selectedStudent,userRole})=>{
 const [mode,setMode]=useState<Mode>('assessment'),[view,setView]=useState('global'),[score,setScore]=useState(80),[notes,setNotes]=useState(''),[plan,setPlan]=useState(''),[finding,setFinding]=useState(''),[findings,setFindings]=useState<string[]>([]),[angles,setAngles]=useState<Angles>(EMPTY),[angleDraft,setAngleDraft]=useState<AngleDraft>(EMPTY_DRAFT),[history,setHistory]=useState<any[]>([]),[csrf,setCsrf]=useState(''),[msg,setMsg]=useState('');
 const sid=userRole==='coach'?selectedStudent.id:undefined;
 const load=async()=>{try{const q=sid?`?studentId=${encodeURIComponent(String(sid))}`:'';const r=await fetch(`/api/postural-assessments${q}`,{credentials:'include'});if(r.ok){const d=await r.json();setHistory(d.assessments||[])}}catch{}};
 useEffect(()=>{api.me().then(r=>setCsrf(r.csrf||''));load()},[selectedStudent.id]);
 useEffect(()=>{setAngles(EMPTY);setAngleDraft(EMPTY_DRAFT);setFindings([]);setNotes('');setPlan('');setScore(80);setMode('assessment')},[selectedStudent.id]);
 const add=()=>{const f=finding.trim();if(f){setFindings(v=>[...v,f]);setFinding('')}};
 const updateAngleDraft=(k:keyof Angles,raw:string)=>{
   // Permite vazio, negativo e decimal durante a digitação. Nada de inserir zero automaticamente.
   if(!/^-?\d{0,2}([.,]\d?)?$/.test(raw))return;
   setAngleDraft(d=>({...d,[k]:raw}));
   const clean=raw.replace(',','.');
   if(clean!==''&&clean!=='-'&&clean!=='.'&&clean!=='-.'){
     const n=Number(clean);if(Number.isFinite(n)&&n>=-45&&n<=45)setAngles(a=>({...a,[k]:n}));
   }else setAngles(a=>({...a,[k]:0}));
 };
 const commitAngle=(k:keyof Angles)=>{const n=normalizeAngle(angleDraft[k]);setAngles(a=>({...a,[k]:n}));setAngleDraft(d=>({...d,[k]:angleDraft[k].trim()===''?'':String(n)}));};
 const validatedAngles=()=>{const out={...EMPTY};(Object.keys(labels) as (keyof Angles)[]).forEach(k=>out[k]=normalizeAngle(angleDraft[k]));return out;};
 const save=async()=>{if(userRole!=='coach'||!sid)return;const finalAngles=validatedAngles();setAngles(finalAngles);setAngleDraft(Object.fromEntries(Object.entries(finalAngles).map(([k,v])=>[k,String(v)])) as AngleDraft);const r=await fetch('/api/postural-assessments',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({studentId:Number(sid),viewType:view,findings,angles:finalAngles,notes,correctivePlan:plan,score})});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||'Falha ao salvar.');return}setMsg('Avaliação postural salva com sucesso.');setFindings([]);setNotes('');setPlan('');load();setMode('history')};
 const latest=history[0],previous=history[1];
 const comparison=useMemo(()=>{if(!latest||!previous)return[];const a=latest.angles||{},b=previous.angles||{};return (Object.keys(labels) as (keyof Angles)[]).map(k=>({key:k,label:labels[k],now:Number(a[k]||0),before:Number(b[k]||0),delta:Number((Number(a[k]||0)-Number(b[k]||0)).toFixed(1))}))},[latest,previous]);
 const shownAngles=userRole==='coach'?angles:(latest?.angles||EMPTY);
 const tabs:[Mode,string][]=[['assessment','Avaliação'],['viewer','Visualização 3D'],['history','Histórico']];
 return <div className="space-y-5">
  <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4"><div><div className="text-[10px] font-mono text-[#DFFF00]">// BIOMECÂNICA APLICADA</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Avaliação Postural 3D</h1><p className="text-xs text-gray-500 max-w-3xl">Registre medidas e achados com espaço adequado. Use a visualização ampla somente quando precisar analisar o mapa corporal.</p></div><div className="flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setMode(id)} className={`px-4 py-3 border text-[10px] font-black ${mode===id?'bg-[#DFFF00] text-black border-[#DFFF00]':'border-[#444] text-gray-300'}`}>{label.toUpperCase()}</button>)}</div></div>
  {msg&&<div className="border border-[#DFFF00]/40 p-3 text-xs text-[#DFFF00]">{msg}</div>}
  {mode==='assessment'&&<div className="grid 2xl:grid-cols-[minmax(0,1.15fr)_minmax(420px,.85fr)] gap-4">
   <section className={`${box} space-y-5`}><div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><div className="text-[10px] text-[#DFFF00]">NOVA AVALIAÇÃO</div><h2 className="font-anybody font-black uppercase text-white text-2xl">Dados posturais</h2></div>{userRole==='coach'&&<div className="text-xs text-gray-500">Aluno: <b className="text-white">{selectedStudent.name||'Selecione um aluno'}</b></div>}</div>
   {userRole==='coach'?<><div className="grid md:grid-cols-2 gap-3"><label className="text-[10px] text-gray-500">VISTA DA AVALIAÇÃO<select value={view} onChange={e=>setView(e.target.value)} className={`${input} mt-1`}><option value="global">Global</option><option value="anterior">Anterior</option><option value="posterior">Posterior</option><option value="lateral_direita">Lateral direita</option><option value="lateral_esquerda">Lateral esquerda</option></select></label><label className="text-[10px] text-gray-500">SCORE GLOBAL — {score}/100<input type="range" min={0} max={100} value={score} onChange={e=>setScore(Number(e.target.value))} className="w-full mt-3 accent-[#DFFF00]"/></label></div>
   <div><div className="text-[10px] text-[#DFFF00] mb-3">MEDIDAS ANGULARES (°)</div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{(Object.keys(labels) as (keyof Angles)[]).map(k=><label key={k} className="text-[10px] text-gray-500 bg-black border border-[#252525] p-3">{labels[k]}<input inputMode="decimal" value={angleDraft[k]} placeholder="0" onChange={e=>updateAngleDraft(k,e.target.value)} onBlur={()=>commitAngle(k)} onFocus={e=>e.currentTarget.select()} className={`${input} mt-2`}/></label>)}</div><div className="text-[9px] text-gray-600 mt-2">Aceita valores de -45° a 45°. O campo não força mais 0 ou 45 enquanto você digita; a validação ocorre ao sair do campo ou salvar.</div></div>
   <div><div className="text-[10px] text-[#DFFF00] mb-2">ACHADOS OBSERVACIONAIS</div><div className="flex gap-2"><input value={finding} onChange={e=>setFinding(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}} placeholder="Ex.: ombro direito elevado" className={`flex-1 ${input}`}/><button onClick={add} className="px-5 bg-[#DFFF00] text-black font-black">ADICIONAR</button></div><div className="flex flex-wrap gap-2 mt-2">{findings.map((f,i)=><button key={i} onClick={()=>setFindings(v=>v.filter((_,x)=>x!==i))} className="border border-[#444] px-3 py-2 text-[10px]">{f} ×</button>)}</div></div>
   <div className="grid lg:grid-cols-2 gap-3"><label className="text-[10px] text-gray-500">OBSERVAÇÕES<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações clínicas e funcionais" className={`${input} min-h-32 mt-1`}/></label><label className="text-[10px] text-gray-500">PLANO DE ACOMPANHAMENTO<textarea value={plan} onChange={e=>setPlan(e.target.value)} placeholder="Exercícios corretivos e orientações" className={`${input} min-h-32 mt-1`}/></label></div>
   <div className="flex flex-col sm:flex-row gap-2"><button onClick={save} disabled={!sid} className="flex-1 bg-[#DFFF00] text-black p-3 text-xs font-black disabled:opacity-40">SALVAR AVALIAÇÃO</button><button onClick={()=>setMode('viewer')} className="px-5 border border-[#DFFF00] text-[#DFFF00] text-xs font-black">ABRIR 3D EM TELA AMPLA</button></div></>:<div className="text-xs text-gray-500">Você pode visualizar suas avaliações registradas nas abas 3D e Histórico.</div>}</section>
   <aside className={`${box} space-y-3 h-fit 2xl:sticky 2xl:top-24`}><div><div className="text-[10px] text-[#DFFF00]">PREVIEW 3D</div><h2 className="font-anybody font-black uppercase text-white">Mapa corporal</h2><p className="text-[10px] text-gray-500">Prévia compacta durante o preenchimento.</p></div><PosturalBody3D angles={shownAngles}/></aside>
  </div>}
  {mode==='viewer'&&<section className={`${box} space-y-3`}><div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><div className="text-[10px] text-[#DFFF00]">MAPA CORPORAL 3D</div><h2 className="font-anybody font-black uppercase text-white text-2xl">Visualização postural ampla</h2><p className="text-[10px] text-gray-500">Use esta área para girar o modelo e conferir os ângulos com mais espaço.</p></div><div className="flex gap-2"><button onClick={()=>setMode('assessment')} className="border border-[#444] px-3 py-2 text-[10px] font-black">VOLTAR AOS DADOS</button><button onClick={()=>window.print()} className="border border-[#DFFF00] text-[#DFFF00] px-3 py-2 text-[10px] font-black">SALVAR PDF</button></div></div><PosturalBody3D angles={shownAngles} expanded/></section>}
  {mode==='history'&&<div className="space-y-4">{comparison.length>0&&<section className={box}><div className="flex justify-between gap-3 items-end"><div><div className="text-[10px] text-[#DFFF00]">COMPARAÇÃO</div><h2 className="font-anybody font-black uppercase text-white">Última avaliação × anterior</h2></div><div className="text-[10px] text-gray-500">Δ em graus</div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-3">{comparison.map(c=><div key={c.key} className="bg-black border border-[#333] p-3"><div className="text-[9px] text-gray-500 uppercase">{c.label}</div><div className="flex items-baseline justify-between mt-1"><b className="text-white">{c.now}°</b><span className={c.delta===0?'text-gray-500':Math.abs(c.delta)<Math.abs(c.before)?'text-green-400':'text-yellow-300'}>{c.delta>0?'+':''}{c.delta}°</span></div><div className="text-[9px] text-gray-600">Anterior: {c.before}°</div></div>)}</div></section>}
  <section className={box}><div className="flex items-end justify-between gap-3 mb-3"><div><div className="text-[10px] text-[#DFFF00]">HISTÓRICO</div><h2 className="font-anybody font-black uppercase text-white">Avaliações registradas</h2></div>{userRole==='coach'&&<button onClick={()=>setMode('assessment')} className="border border-[#DFFF00] text-[#DFFF00] px-3 py-2 text-[10px] font-black">NOVA AVALIAÇÃO</button>}</div><div className="space-y-2">{history.map(h=><div key={h.id} className="bg-black border border-[#333] p-4"><div className="flex justify-between gap-2"><b className="text-white uppercase">{h.viewType} • {h.score==null?'-':`${h.score}/100`}</b><span className="text-[10px] text-gray-600">{new Date(h.createdAt).toLocaleString('pt-BR')}</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-1 mt-2">{Object.entries(h.angles||{}).map(([k,v])=><div key={k} className="text-[9px] text-gray-500">{labels[k as keyof Angles]||k}: <b className="text-gray-300">{String(v)}°</b></div>)}</div><div className="flex flex-wrap gap-1 mt-2">{(h.findings||[]).map((f:string,i:number)=><span key={i} className="border border-[#444] px-2 py-1 text-[9px] text-gray-400">{f}</span>)}</div>{h.notes&&<p className="text-xs text-gray-400 mt-2">{h.notes}</p>}{h.correctivePlan&&<p className="text-xs text-[#DFFF00] mt-2">Plano: {h.correctivePlan}</p>}</div>)}{!history.length&&<div className="text-xs text-gray-600">Nenhum registro ainda.</div>}</div></section></div>}
 </div>;
};
