import React,{useEffect,useState} from 'react';
import {api} from '../../api';
const input='w-full bg-black border border-[#333] p-3 text-sm text-white outline-none focus:border-[#DFFF00]';
export const PublicCoachScreen:React.FC<{slug:string}>=({slug})=>{
 const [profile,setProfile]=useState<any>(null),[form,setForm]=useState({name:'',email:'',phone:'',goal:''}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api.publicCoach(slug).then(r=>setProfile(r.profile)).catch((e:any)=>setMsg(e.message))},[slug]);
 const send=async()=>{setBusy(true);setMsg('');try{await api.createPublicLead(slug,form);setMsg('Interesse enviado. O treinador recebeu seu contato.');setForm({name:'',email:'',phone:'',goal:''})}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 if(!profile)return <div className="min-h-screen bg-[#0A0A0A] text-white grid place-items-center p-6"><div className="text-sm text-gray-400">{msg||'Carregando perfil...'}</div></div>;
 return <div className="min-h-screen bg-[#0A0A0A] text-white"><div className="max-w-6xl mx-auto p-5 lg:p-10"><div className="grid lg:grid-cols-[1.15fr_.85fr] gap-8 items-start"><section className="pt-8"><div className="text-[10px] font-mono text-[#DFFF00]">// PULSEFIT PROFESSIONAL</div><h1 className="font-anybody text-5xl lg:text-7xl font-black uppercase mt-3">{profile.name}</h1><p className="text-xl text-[#DFFF00] font-bold mt-3">{profile.headline||profile.specialty||'Treinamento personalizado'}</p><p className="max-w-2xl text-gray-400 mt-6 leading-relaxed">{profile.bio||'Acompanhamento profissional com treinos organizados e evolução acompanhada pelo PulseFit.'}</p><div className="flex flex-wrap gap-2 mt-6">{(profile.services||[]).map((x:string)=><span key={x} className="border border-[#333] bg-[#121414] px-3 py-2 text-xs">{x}</span>)}</div><div className="mt-8 text-xs text-gray-500">{profile.cref&&`CREF ${profile.cref} • `}{profile.city}{profile.state&&` - ${profile.state}`}</div></section><section className="bg-[#121414] border-2 border-[#DFFF00] p-6 space-y-3"><div><div className="text-[10px] font-mono text-[#DFFF00]">QUERO COMEÇAR</div><h2 className="font-anybody text-2xl font-black uppercase">Fale com o treinador</h2><p className="text-xs text-gray-500 mt-1">Envie seu objetivo e seus dados de contato.</p></div>{msg&&<div className="border border-[#DFFF00]/40 bg-black p-3 text-xs text-[#DFFF00]">{msg}</div>}<input className={input} placeholder="Seu nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={input} placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className={input} placeholder="WhatsApp / telefone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea className={`${input} min-h-28`} placeholder="Qual é seu objetivo?" value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/><button disabled={busy} onClick={send} className="w-full bg-[#DFFF00] text-black py-4 font-anybody font-black uppercase">{busy?'ENVIANDO...':'QUERO TREINAR COM ESTE PROFISSIONAL'}</button></section></div></div></div>;
};
