import React,{useEffect,useState} from 'react';
import {api} from '../../api';
const input='w-full bg-black border border-[#333] p-3 text-sm text-white outline-none';
export const PublicCoachScreen:React.FC<{slug:string}>=({slug})=>{
 const [profile,setProfile]=useState<any>(null),[brand,setBrand]=useState<any>(null),[form,setForm]=useState({name:'',email:'',phone:'',goal:''}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([api.publicCoach(slug),fetch(`/api/public/brand/${encodeURIComponent(slug)}`).then(r=>r.json())]).then(([p,b])=>{setProfile(p.profile);setBrand(b.brand)}).catch((e:any)=>setMsg(e.message))},[slug]);
 const send=async()=>{setBusy(true);setMsg('');try{await api.createPublicLead(slug,form);setMsg('Interesse enviado. O treinador recebeu seu contato.');setForm({name:'',email:'',phone:'',goal:''})}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 if(!profile)return <div className="min-h-screen bg-[#0A0A0A] text-white grid place-items-center p-6"><div className="text-sm text-gray-400">{msg||'Carregando perfil...'}</div></div>;
 const primary=brand?.primaryColor||'#DFFF00',secondary=brand?.secondaryColor||'#121414',display=brand?.displayName||profile.name;
 return <div className="min-h-screen bg-[#0A0A0A] text-white"><div className="max-w-6xl mx-auto p-5 lg:p-10">{brand?.bannerUrl&&<div className="h-48 lg:h-72 bg-cover bg-center border border-[#333] mb-8" style={{backgroundImage:`url(${brand.bannerUrl})`}}/>}<div className="grid lg:grid-cols-[1.15fr_.85fr] gap-8 items-start"><section className="pt-8">{brand?.logoUrl&&<img src={brand.logoUrl} className="w-24 h-24 object-contain bg-black border p-2 mb-5" style={{borderColor:primary}}/>}<div className="text-[10px] font-mono" style={{color:primary}}>// {display.toUpperCase()}</div><h1 className="font-anybody text-5xl lg:text-7xl font-black uppercase mt-3">{display}</h1><p className="text-xl font-bold mt-3" style={{color:primary}}>{brand?.slogan||profile.headline||profile.specialty||'Treinamento personalizado'}</p><p className="max-w-2xl text-gray-400 mt-6 leading-relaxed">{profile.bio||'Acompanhamento profissional com treinos organizados e evolução acompanhada pelo PulseFit.'}</p><div className="flex flex-wrap gap-2 mt-6">{(profile.services||[]).map((x:string)=><span key={x} className="border border-[#333] px-3 py-2 text-xs" style={{backgroundColor:secondary}}>{x}</span>)}</div><div className="mt-8 text-xs text-gray-500">{profile.cref&&`CREF ${profile.cref} • `}{profile.city}{profile.state&&` - ${profile.state}`}</div>{(brand?.instagram||brand?.website||brand?.whatsapp)&&<div className="flex flex-wrap gap-3 mt-4 text-xs" style={{color:primary}}>{brand?.instagram&&<span>{brand.instagram}</span>}{brand?.website&&<span>{brand.website}</span>}{brand?.whatsapp&&<span>{brand.whatsapp}</span>}</div>}</section><section className="border-2 p-6 space-y-3" style={{backgroundColor:secondary,borderColor:primary}}><div><div className="text-[10px] font-mono" style={{color:primary}}>QUERO COMEÇAR</div><h2 className="font-anybody text-2xl font-black uppercase">Fale com o treinador</h2><p className="text-xs text-gray-500 mt-1">Envie seu objetivo e seus dados de contato.</p></div>{msg&&<div className="border bg-black p-3 text-xs" style={{borderColor:primary,color:primary}}>{msg}</div>}<input className={input} placeholder="Seu nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={input} placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className={input} placeholder="WhatsApp / telefone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea className={`${input} min-h-28`} placeholder="Qual é seu objetivo?" value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/><button disabled={busy} onClick={send} className="w-full text-black py-4 font-anybody font-black uppercase" style={{backgroundColor:primary}}>{busy?'ENVIANDO...':'QUERO TREINAR COM ESTE PROFISSIONAL'}</button></section></div></div></div>;
};
