import React,{useEffect,useState} from 'react';
import {api} from '../../api';

const Stat=({label,value}:{label:string;value:any})=><div className="bg-black border border-[#333] p-3"><div className="text-[9px] uppercase text-gray-500">{label}</div><b className="text-xl text-[#DFFF00]">{value}</b></div>;
export const StudentReportProPanel:React.FC<{studentId:string|number}>=({studentId})=>{
 const [days,setDays]=useState(30),[report,setReport]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[summary,setSummary]=useState(''),[provider,setProvider]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async(d=days)=>{if(!studentId)return;setBusy(true);setError('');try{const [r,h]=await Promise.all([api.reportStudent(studentId,d),api.reportHistory(studentId)]);setReport(r.report);setHistory(h.reports||[])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load(days)},[studentId]);
 const historyAI=async()=>{setBusy(true);setError('');try{const r=await api.aiStudentHistory(studentId);setSummary(r.summary||'');setProvider(r.provider||'local');setReport(r.report||report)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const generate=async(d:number)=>{setDays(d);setBusy(true);setError('');try{const r=await api.createReport(studentId,d);setReport(r.report);const h=await api.reportHistory(studentId);setHistory(h.reports||[])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!studentId)return null;
 const cmp=report?.comparison||{},tr=report?.trends||{};
 return <section className="mt-5 bg-[#121414] border border-[#333] p-4 space-y-4 print:bg-white print:text-black"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><div className="text-[10px] font-mono text-[#DFFF00] print:text-black">// RELATÓRIO PRO</div><h2 className="font-anybody text-xl font-black uppercase text-white print:text-black">Evolução e inteligência</h2></div><div className="flex flex-wrap gap-2">{[7,30,90].map(d=><button key={d} disabled={busy} onClick={()=>generate(d)} className={`px-3 py-2 text-[10px] border ${days===d?'bg-[#DFFF00] text-black border-[#DFFF00]':'border-[#444]'}`}>{d} DIAS</button>)}<button disabled={busy} onClick={historyAI} className="px-3 py-2 text-[10px] border border-[#DFFF00] text-[#DFFF00]">IA 90 DIAS</button><button onClick={()=>window.print()} className="px-3 py-2 text-[10px] border border-[#444]">SALVAR PDF</button></div></div>{error&&<div className="border border-red-900 p-3 text-xs text-red-300">{error}</div>}{report&&<><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-2"><Stat label="Aderência" value={`${report.adherence||0}%`}/><Stat label="Treinos" value={report.workouts||0}/><Stat label="Δ treinos" value={cmp.workoutsDelta??0}/><Stat label="Volume" value={Math.round(report.volume||0)}/><Stat label="Δ volume" value={Math.round(cmp.volumeDelta||0)}/><Stat label="Peso Δ" value={tr.weightDelta==null?'-':`${tr.weightDelta} kg`}/><Stat label="Gordura Δ" value={tr.bodyFatDelta==null?'-':`${tr.bodyFatDelta} p.p.`}/><Stat label="Cintura Δ" value={tr.waistDelta==null?'-':`${tr.waistDelta} cm`}/></div>{(report.alerts||[]).length>0&&<div className="grid md:grid-cols-2 gap-2">{report.alerts.map((a:any,i:number)=><div key={i} className={`p-3 border text-xs ${a.severity==='high'?'border-red-800 text-red-300':'border-yellow-700 text-yellow-300'}`}>{a.message}</div>)}</div>}{(report.records||[]).length>0&&<div><h3 className="text-xs font-black uppercase text-white mb-2 print:text-black">Recordes do período</h3><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-2">{report.records.map((x:any)=><div key={x.exerciseName} className="bg-black border border-[#333] p-3 print:bg-white"><b className="text-xs text-white print:text-black">{x.exerciseName}</b><div className="text-[10px] text-gray-500">Carga máx. {x.maxLoad} • reps máx. {x.maxReps}</div></div>)}</div></div>}</>}{summary&&<div className="border border-[#DFFF00]/40 p-4"><div className="text-[10px] text-[#DFFF00]">COPILOTO HISTÓRICO • {provider==='gemini'?'GEMINI':'LOCAL'}</div><p className="text-sm mt-2 leading-relaxed text-gray-300 print:text-black">{summary}</p></div>}<div className="text-[10px] text-gray-500">Relatórios salvos: {history.length}. O PDF usa a impressão do navegador com layout preparado para exportação.</div></section>;
};
