import React,{useEffect,useState} from 'react';
import {api} from '../../api';
import {ScreenView} from '../../types';
export const StudentCheckinScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=()=>{
 const [form,setForm]=useState({weight:'',sleepHours:'',painLevel:'0',fatigueLevel:'0',energyLevel:'5',notes:''}),[history,setHistory]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api.checkins().then(r=>setHistory(r.checkins||[])).catch((e:any)=>setMsg(e.message));useEffect(()=>{load()},[]);
 const submit=async()=>{setBusy(true);setMsg('');try{await api.createCheckin(form);setMsg('Check-in enviado ao treinador.');setForm({...form,notes:''});await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 return <div className="space-y-5">{msg&&<div className="border border-[#DFFF00]/40 bg-black p-3 text-xs text-[#DFFF00]">{msg}</div>}<div><div className="text-[10px] font-mono text-[#DFFF00]">// CHECK-IN SEMANAL</div><h1 className="font-anybody text-3xl font-black uppercase text-white">Como foi sua semana?</h1><p className="text-xs text-gray-500">Esses dados ajudam seu treinador a ajustar carga, volume e recuperação.</p></div><div className="bg-[#121414] border border-[#333] p-5 grid sm:grid-cols-2 gap-4"><Field label="Peso (kg)"><input value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})} type="number" step="0.1" className="input"/></Field><Field label="Sono médio (horas)"><input value={form.sleepHours} onChange={e=>setForm({...form,sleepHours:e.target.value})} type="number" step="0.5" className="input"/></Field>{[['painLevel','Dor'],['fatigueLevel','Fadiga'],['energyLevel','Disposição']].map(([k,l])=><Field key={k} label={`${l}: ${(form as any)[k]}/10`}><input type="range" min="0" max="10" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full"/></Field>)}<Field label="Observações"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="input min-h-24" placeholder="Dores, dificuldades, evolução, alimentação, rotina..."/></Field><div className="sm:col-span-2"><button disabled={busy} onClick={submit} className="px-5 py-3 bg-[#DFFF00] text-black font-black text-xs">{busy?'ENVIANDO...':'ENVIAR CHECK-IN'}</button></div></div><div className="bg-[#121414] border border-[#333] p-4"><h2 className="font-anybody font-black uppercase text-white mb-3">Histórico</h2><div className="space-y-2">{history.map(x=><div key={x.id} className="bg-black border border-[#2a2a2a] p-3 text-xs"><b>{new Date(x.createdAt).toLocaleDateString('pt-BR')}</b><div className="text-gray-500">Sono {x.sleepHours}h • dor {x.painLevel}/10 • fadiga {x.fatigueLevel}/10 • disposição {x.energyLevel}/10</div><div className="mt-1">{x.notes||'Sem observações.'}</div></div>)}{!history.length&&<div className="text-xs text-gray-500">Nenhum check-in enviado ainda.</div>}</div></div></div>;
};
const Field:React.FC<{label:string;children:React.ReactNode}>=({label,children})=><label className="text-[10px] font-mono text-gray-500 uppercase">{label}<div className="mt-2">{children}</div></label>;
