import React,{useEffect,useState} from 'react';
import {ScreenView} from '../../types'; import {api} from '../../api'; import {ExerciseThumbnail} from '../ExerciseThumbnail';
export const StudentDailyScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=({onNavigate})=>{
 const [portal,setPortal]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{api.portal().then(setPortal).catch((e:any)=>setError(e.message))},[]);
 const workout=portal?.workouts?.[0], exercises=workout?.exercises||[];
 return <div className="w-full space-y-6">{error&&<div className="border border-red-500/40 p-3 text-red-300 text-xs">{error}</div>}
 <div className="bg-[#121414] border border-[#333535] p-5 flex justify-between"><div><div className="text-[10px] font-mono text-[#DFFF00]">// TREINO PUBLICADO</div><h1 className="font-anybody text-3xl font-black uppercase text-white">Treino de Hoje</h1><p className="text-xs font-mono text-gray-400">{portal?.student?.programName||'Carregando...'} • {portal?.student?.phase||''}</p></div><div className="text-right"><div className="text-xs font-mono text-gray-500">FICHAS DISPONÍVEIS</div><div className="text-3xl text-[#DFFF00] font-black">{portal?.workouts?.length||0}</div></div></div>
 {workout?<><div className="bg-[#121414] border-2 border-[#DFFF00] p-6 flex flex-col md:flex-row justify-between gap-4"><div><span className="bg-[#DFFF00] text-black px-2 py-1 text-[10px] font-black font-mono">ATIVO</span><h2 className="mt-3 font-anybody text-3xl font-black uppercase text-white">{workout.title}</h2><p className="text-xs font-mono text-gray-400 mt-1">{exercises.length} exercícios prescritos pelo treinador</p></div><button onClick={()=>onNavigate('workout_execution')} className="self-start md:self-center px-8 py-4 bg-[#DFFF00] text-black font-anybody font-black uppercase text-sm shadow-[4px_4px_0_#fff]">Iniciar Treino</button></div>
 <div className="bg-[#121414] border border-[#333535] p-5 space-y-2"><h3 className="font-anybody font-bold uppercase text-white mb-4">Roteiro de Execução</h3>{exercises.map((x:any,i:number)=><div key={x.id||i} className="flex items-center gap-3 p-3 bg-[#181a1a] border border-[#333]"><div className="w-16 h-14 bg-black overflow-hidden"><ExerciseThumbnail name={x.name} category={x.category} equipment={x.equipment} src={x.thumbnail||''} mediaType={x.mediaType==='video'?'video':'image'}/></div><div className="flex-1"><div className="font-anybody font-bold uppercase text-white text-sm">{String(i+1).padStart(2,'0')}. {x.name}</div><div className="text-[10px] font-mono text-gray-400">{x.sets} séries • {x.reps} reps • {x.load||'carga livre'} • descanso {x.rest}s</div></div><span className="text-[10px] font-mono text-[#DFFF00]">RPE {x.rpe||8}</span></div>)}</div></>:<div className="border border-dashed border-[#333] p-12 text-center text-sm font-mono text-gray-500">Seu treinador ainda não publicou uma ficha.</div>}
 </div>
}
