import React,{useEffect,useState} from 'react';
import {ScreenView} from '../../types';
import {api} from '../../api';

export const StudentProfileScreen:React.FC<{onNavigate:(s:ScreenView)=>void;onOpenMetricsModal:()=>void}>=({onNavigate,onOpenMetricsModal})=>{
 const [portal,setPortal]=useState<any>(null),[progress,setProgress]=useState<any>(null),[notifications,setNotifications]=useState<any[]>([]),[msg,setMsg]=useState(''),[passwords,setPasswords]=useState({currentPassword:'',newPassword:''});
 const load=()=>Promise.all([api.portal(),api.progress(),api.notifications()]).then(([p,g,n])=>{setPortal(p);setProgress(g);setNotifications(n.notifications||[])}).catch((e:any)=>setMsg(e.message));useEffect(()=>{load()},[]);
 const upload=async(f?:File)=>{if(!f)return;try{await api.uploadProgressPhoto(f,'Foto de evolução');setMsg('Foto enviada.');await load()}catch(e:any){setMsg(e.message)}};
 const change=async()=>{try{await api.changePassword(passwords.currentPassword,passwords.newPassword);setPasswords({currentPassword:'',newPassword:''});setMsg('Senha alterada com sucesso.')}catch(e:any){setMsg(e.message)}};
 const s=portal?.student;const initials=(s?.name||'PF').split(' ').slice(0,2).map((x:string)=>x[0]).join('').toUpperCase();
 return <div className="space-y-6">{msg&&<div className="border border-[#DFFF00]/40 bg-black p-3 text-[#DFFF00] text-xs font-mono">{msg}</div>}
 <div className="bg-[#121414] border border-[#333] p-6 flex flex-col sm:flex-row gap-5 items-start sm:items-center"><div className="w-24 h-24 border-2 border-[#DFFF00] bg-black overflow-hidden flex items-center justify-center text-2xl font-black text-[#DFFF00]">{s?.avatar?<img src={s.avatar} className="w-full h-full object-cover"/>:initials}</div><div className="flex-1"><div className="text-[10px] font-mono text-[#DFFF00]">// PERFIL DO ATLETA</div><h1 className="font-anybody text-3xl font-black uppercase text-white">{s?.name||'Carregando...'}</h1><p className="text-xs font-mono text-gray-400">{s?.programName} • {s?.phase} • {s?.planName}</p></div><button onClick={onOpenMetricsModal} className="px-4 py-2 border border-[#DFFF00] text-[#DFFF00] text-xs font-mono">Atualizar medidas</button></div>
 <div className="grid sm:grid-cols-4 gap-3">{[['Idade',s?.age,'anos'],['Altura',s?.height,'cm'],['Peso',s?.weight,'kg'],['Gordura',s?.bodyFat,'%']].map((x:any)=><div key={x[0]} className="bg-[#121414] border border-[#333] p-4"><div className="text-[10px] font-mono text-gray-500">{x[0]}</div><div className="text-2xl font-anybody font-black text-white">{x[1]||0} <span className="text-xs text-[#DFFF00]">{x[2]}</span></div></div>)}</div>
 <div className="grid lg:grid-cols-[1fr_340px] gap-5"><div className="bg-[#121414] border border-[#333] p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-anybody font-bold uppercase text-white">Galeria de Evolução</h2><label className="px-4 py-2 bg-[#DFFF00] text-black text-xs font-black cursor-pointer">ENVIAR FOTO<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{(progress?.photos||[]).map((p:any)=><div key={p.id}><img src={p.url} className="w-full aspect-[3/4] object-cover border border-[#333]"/><div className="text-[9px] font-mono text-gray-500 mt-1">{new Date(p.createdAt).toLocaleDateString('pt-BR')}</div></div>)}{!(progress?.photos||[]).length&&<div className="col-span-full border border-dashed border-[#333] p-8 text-center text-xs text-gray-500 font-mono">Nenhuma foto enviada ainda.</div>}</div><button onClick={()=>onNavigate('student_progress')} className="mt-4 text-xs font-mono text-[#DFFF00]">Ver histórico completo →</button></div>
 <aside className="space-y-4"><section className="bg-[#121414] border border-[#333] p-4"><h2 className="font-anybody font-bold uppercase text-white mb-3">Segurança da conta</h2><input type="password" value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})} placeholder="Senha atual" className="w-full bg-black border border-[#333] p-3 text-xs mb-2"/><input type="password" value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})} placeholder="Nova senha (12+ caracteres)" className="w-full bg-black border border-[#333] p-3 text-xs mb-2"/><button onClick={change} className="w-full py-2 bg-[#DFFF00] text-black text-xs font-black">ALTERAR SENHA</button></section><section className="bg-[#121414] border border-[#333] p-4"><div className="flex justify-between"><h2 className="font-anybody font-bold uppercase text-white">Notificações</h2>{notifications.some(n=>!n.readAt)&&<button onClick={async()=>{await api.markAllNotificationsRead();await load()}} className="text-[9px] text-[#DFFF00]">MARCAR LIDAS</button>}</div><div className="space-y-2 mt-3 max-h-64 overflow-auto">{notifications.slice(0,12).map(n=><button key={n.id} onClick={async()=>{if(!n.readAt){await api.markNotificationRead(n.id);await load()}}} className={`w-full text-left p-2 border ${n.readAt?'border-[#222] text-gray-600':'border-[#DFFF00]/30 text-white'}`}><div className="text-xs font-bold">{n.title}</div><div className="text-[10px] text-gray-500">{n.body}</div></button>)}{!notifications.length&&<div className="text-xs text-gray-500">Nenhuma notificação.</div>}</div></section></aside></div></div>;
};
