import React,{useEffect,useState} from 'react';
import {Student,ScreenView} from '../../types';
import {api} from '../../api';

type Tab='resumo'|'treinos'|'metas'|'avaliacao'|'relatorio'|'evolucao'|'anamnese'|'fotos'|'agenda'|'financeiro'|'checkins'|'historico';
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((c||0)/100);
const input='bg-black border border-[#333] p-2.5 text-xs text-white outline-none focus:border-[#DFFF00]';
export const StudentDetailScreen:React.FC<{student:Student;onNavigate:(s:ScreenView)=>void}>=({student,onNavigate})=>{
 const [data,setData]=useState<any>(null),[goals,setGoals]=useState<any[]>([]),[assessments,setAssessments]=useState<any[]>([]),[report,setReport]=useState<any>(null),[aiSummary,setAiSummary]=useState(''),[aiProvider,setAiProvider]=useState(''),[tab,setTab]=useState<Tab>('resumo'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const [goal,setGoal]=useState<any>({goalType:'weight',targetValue:'',unit:'kg',dueAt:''});const [assessment,setAssessment]=useState<any>({weight:'',bodyFat:'',waist:'',chest:'',abdomen:'',hip:'',notes:''});
 const load=async()=>{if(!student.id)return;try{const [full,g,a]=await Promise.all([api.studentFull(student.id),api.goals(student.id),api.assessments(student.id)]);setData(full);setGoals(g.goals||[]);setAssessments(a.assessments||[])}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[student.id]);
 if(!student.id)return <div className="p-8 text-gray-500">Selecione um aluno.</div>;
 const s=data?.student||student;const tabs:[Tab,string][]=[['resumo','Resumo'],['treinos','Treinos'],['metas','Metas'],['avaliacao','Avaliação Física'],['relatorio','Relatório & IA'],['evolucao','Evolução'],['anamnese','Anamnese'],['fotos','Fotos'],['agenda','Agenda'],['financeiro','Financeiro'],['checkins','Check-ins'],['historico','Histórico']];
 const createGoal=async()=>{try{await api.createGoal({...goal,studentId:student.id,targetValue:Number(goal.targetValue||0)});setGoal({goalType:'weight',targetValue:'',unit:'kg',dueAt:''});setMsg('Meta criada.');await load()}catch(e:any){setMsg(e.message)}};
 const createAssessment=async()=>{try{await api.createAssessment({...assessment,studentId:student.id,weight:Number(assessment.weight||0),bodyFat:Number(assessment.bodyFat||0),waist:Number(assessment.waist||0),chest:Number(assessment.chest||0),abdomen:Number(assessment.abdomen||0),hip:Number(assessment.hip||0)});setMsg('Avaliação física salva.');await load()}catch(e:any){setMsg(e.message)}};
 const generateReport=async()=>{setBusy(true);setMsg('');try{const r=await api.createReport(student.id,30);setReport(r.report);setMsg('Relatório de 30 dias atualizado.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const generateAI=async()=>{setBusy(true);setMsg('');try{const r=await api.aiStudentSummary(student.id,30);setReport(r.report);setAiSummary(r.summary||'');setAiProvider(r.provider||'local')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 return <div className="space-y-5">{msg&&<div className="border border-[#DFFF00]/40 p-3 text-[#DFFF00] text-xs">{msg}</div>}<button onClick={()=>onNavigate('coach_dashboard')} className="text-[10px] font-mono text-[#DFFF00]">← VOLTAR</button><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[10px] font-mono text-[#DFFF00]">// FICHA 360º DO ALUNO</div><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><h1 className="font-anybody text-3xl font-black uppercase text-white">{s.name}</h1><p className="text-xs text-gray-500">{s.email} • {s.program_name||student.programName} • {s.phase} • treinador: {student.assignedCoachName||'-'}</p></div><div className="flex gap-2"><button onClick={()=>onNavigate('prescription')} className="px-3 py-2 bg-[#DFFF00] text-black text-[10px] font-bold">PRESCREVER</button><button onClick={()=>onNavigate('chat')} className="px-3 py-2 border border-[#333] text-[10px]">CHAT</button></div></div></div><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 px-3 py-2 text-[10px] font-mono border ${tab===id?'bg-[#DFFF00] text-black border-[#DFFF00]':'border-[#333] text-gray-400'}`}>{l}</button>)}</div>
 {tab==='resumo'&&<div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{[['Peso',s.weight+' kg'],['Gordura',(s.body_fat??student.bodyFat)+'%'],['Metas ativas',goals.filter(x=>x.status==='active').length],['Check-ins',data?.checkins?.length||0]].map(([l,v])=><div key={l} className="bg-[#121414] border border-[#333] p-5"><div className="text-[9px] font-mono text-gray-500">{l}</div><b className="text-2xl text-white">{v}</b></div>)}</div>}
 {tab==='treinos'&&<List rows={data?.workouts||[]} render={(x:any)=><><b>{x.title}</b><span>{x.status} • {x.publishedAt?new Date(x.publishedAt).toLocaleDateString('pt-BR'):'não publicado'}</span></>}/>} 
 {tab==='metas'&&<div className="space-y-3"><div className="bg-[#121414] border border-[#333] p-4 grid md:grid-cols-5 gap-2"><select className={input} value={goal.goalType} onChange={e=>setGoal({...goal,goalType:e.target.value})}><option value="weight">Peso</option><option value="body_fat">Gordura corporal</option><option value="frequency">Frequência semanal</option><option value="load">Carga</option><option value="measure">Medida</option></select><input className={input} type="number" placeholder="Valor-alvo" value={goal.targetValue} onChange={e=>setGoal({...goal,targetValue:e.target.value})}/><input className={input} placeholder="Unidade" value={goal.unit} onChange={e=>setGoal({...goal,unit:e.target.value})}/><input className={input} type="date" value={goal.dueAt} onChange={e=>setGoal({...goal,dueAt:e.target.value})}/><button onClick={createGoal} className="bg-[#DFFF00] text-black text-xs font-black">CRIAR META</button></div><List rows={goals} render={(x:any)=><div className="flex justify-between gap-3"><div><b>{x.goalType}: {x.targetValue||x.targetText} {x.unit}</b><span>{x.dueAt?`até ${x.dueAt}`:'sem prazo'} • {x.status}</span></div>{x.status==='active'&&<button onClick={()=>api.updateGoal(x.id,'completed').then(load)} className="px-2 py-1 border border-green-700 text-green-400 text-[9px]">CONCLUIR</button>}</div>}/></div>}
 {tab==='avaliacao'&&<div className="space-y-3"><div className="bg-[#121414] border border-[#333] p-4 grid md:grid-cols-4 gap-2">{[['weight','Peso'],['bodyFat','% gordura'],['waist','Cintura'],['chest','Peito'],['abdomen','Abdômen'],['hip','Quadril']].map(([k,l])=><input key={k} className={input} type="number" placeholder={l} value={assessment[k]} onChange={e=>setAssessment({...assessment,[k]:e.target.value})}/>) }<input className={`${input} md:col-span-2`} placeholder="Observações" value={assessment.notes} onChange={e=>setAssessment({...assessment,notes:e.target.value})}/><button onClick={createAssessment} className="md:col-span-4 bg-[#DFFF00] text-black p-3 text-xs font-black">SALVAR AVALIAÇÃO</button></div><List rows={assessments} render={(x:any)=><><b>{x.weight} kg • {x.bodyFat}% gordura</b><span>Cintura {x.waist} cm • Peito {x.chest} cm • {new Date(x.createdAt).toLocaleDateString('pt-BR')}</span></>}/></div>}
 {tab==='relatorio'&&<div className="space-y-3"><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={generateReport} className="px-4 py-3 bg-[#DFFF00] text-black text-xs font-black">GERAR RELATÓRIO 30 DIAS</button><button disabled={busy} onClick={generateAI} className="px-4 py-3 border border-[#DFFF00] text-[#DFFF00] text-xs font-black">RESUMIR COM COPILOTO</button>{report&&<button onClick={()=>window.print()} className="px-4 py-3 border border-[#333] text-xs">IMPRIMIR / SALVAR PDF</button>}</div>{aiSummary&&<section className="bg-[#121414] border border-[#DFFF00]/40 p-5"><div className="text-[10px] font-mono text-[#DFFF00]">COPILOTO • {aiProvider==='gemini'?'GEMINI':'RESUMO LOCAL'}</div><p className="text-sm text-gray-300 mt-3 leading-relaxed">{aiSummary}</p><div className="text-[9px] text-gray-600 mt-3">Apoio à análise do treinador; não substitui avaliação profissional.</div></section>}{report&&<div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><ReportCard l="Aderência" v={`${report.adherence||0}%`}/><ReportCard l="Treinos" v={report.workouts||0}/><ReportCard l="Volume" v={Math.round(report.volume||0)}/><ReportCard l="Pendências" v={report.overduePayments||0}/></div>}{report&&<section className="bg-[#121414] border border-[#333] p-5 grid sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs"><Metric l="Sono médio" v={report.averages?.sleep!=null?`${report.averages.sleep} h`:'-'}/><Metric l="Dor média" v={report.averages?.pain!=null?`${report.averages.pain}/10`:'-'}/><Metric l="Fadiga média" v={report.averages?.fatigue!=null?`${report.averages.fatigue}/10`:'-'}/><Metric l="Energia média" v={report.averages?.energy!=null?`${report.averages.energy}/10`:'-'}/></section>}</div>}
 {tab==='evolucao'&&<List rows={data?.metrics||[]} render={(x:any)=><><b>{x.weight} kg • {x.bodyFat}% gordura</b><span>Cintura {x.waist} cm • {new Date(x.createdAt).toLocaleDateString('pt-BR')}</span></>}/>} 
 {tab==='anamnese'&&<div className="bg-[#121414] border border-[#333] p-5 text-sm space-y-2"><p><b>Objetivo:</b> {data?.anamnese?.objective||'-'}</p><p><b>Lesões:</b> {data?.anamnese?.injuries||'-'}</p><p><b>Experiência:</b> {data?.anamnese?.experience||'-'}</p><p><b>Disponibilidade:</b> {data?.anamnese?.availability||'-'}</p><p><b>Observações:</b> {data?.anamnese?.notes||'-'}</p></div>}
 {tab==='fotos'&&<div className="grid grid-cols-2 md:grid-cols-4 gap-3">{(data?.photos||[]).map((x:any)=><div key={x.id}><img src={x.url} className="aspect-[3/4] w-full object-cover border border-[#333]"/><div className="text-[9px] text-gray-500 mt-1">{x.caption||''}</div></div>)}</div>}
 {tab==='agenda'&&<List rows={data?.appointments||[]} render={(x:any)=><><b>{x.title}</b><span>{new Date(x.startsAt).toLocaleString('pt-BR')} • {x.status}</span></>}/>} 
 {tab==='financeiro'&&<List rows={data?.payments||[]} render={(x:any)=><><b>{money(Number(x.amountCents||0))} • {x.description||'Cobrança'}</b><span>Venc. {x.dueDate} • {x.status}</span></>}/>} 
 {tab==='checkins'&&<List rows={data?.checkins||[]} render={(x:any)=><><b>Sono {x.sleepHours}h • dor {x.painLevel}/10 • fadiga {x.fatigueLevel}/10 • energia {x.energyLevel}/10</b><span>{x.notes||'Sem observação'} • {new Date(x.createdAt).toLocaleString('pt-BR')}</span></>}/>} 
 {tab==='historico'&&<List rows={data?.history||[]} render={(x:any)=><><b>{x.actorName}: {x.action}</b><span>{x.details||'-'} • {new Date(x.createdAt).toLocaleString('pt-BR')}</span></>}/>} 
 </div>;
};
const List:React.FC<{rows:any[];render:(x:any)=>React.ReactNode}>=({rows,render})=><div className="bg-[#121414] border border-[#333] p-4 space-y-2">{rows.length?rows.map((x:any)=><div key={x.id} className="bg-black border border-[#2a2a2a] p-3 flex flex-col gap-1 text-xs">{render(x)}</div>):<div className="p-8 text-center text-xs text-gray-500">Nenhum registro.</div>}</div>;
const ReportCard=({l,v}:{l:string;v:any})=><div className="bg-[#121414] border border-[#333] p-5"><div className="text-[9px] text-gray-500 uppercase">{l}</div><b className="text-3xl text-[#DFFF00]">{v}</b></div>;
const Metric=({l,v}:{l:string;v:any})=><div><div className="text-[9px] text-gray-500 uppercase">{l}</div><b className="text-white">{v}</b></div>;
