import React,{useEffect,useState} from 'react';
import {ScreenView} from '../../types'; import {api} from '../../api';
export const StudentHubScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=({onNavigate})=>{
 const [c,setC]=useState<any>(null),[n,setN]=useState<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api.studentCentral(),api.notifications()]).then(([central,notes])=>{setC(central);setN(notes.notifications||[])}).catch((e:any)=>setError(e.message))},[]);
 const s=c?.student,w=c?.todayWorkout;
 return <div className="space-y-6">{error&&<div className="border border-red-500/40 p-3 text-red-300 text-xs">{error}</div>}<div className="bg-[#121414] border border-[#333] p-6"><div className="text-[10px] font-mono text-[#DFFF00]">// CENTRAL DO ALUNO</div><h1 className="font-anybody text-4xl font-black uppercase text-white">Olá, {s?.name||'atleta'}</h1><p className="text-xs font-mono text-gray-500 mt-1">{s?.programName||'Programa'} • {s?.phase||'Fase atual'}</p></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat l="Treinos 7 dias" v={c?.weekWorkouts||0}/><Stat l="Sequência" v={`${c?.streak||0} dia(s)`}/><Stat l="Metas ativas" v={c?.goals?.length||0}/><Stat l="Pendências" v={c?.pendingPayments||0}/></div>
 <section className="bg-[#121414] border border-[#333] p-4"><div className="flex justify-between items-end gap-3"><div><div className="text-[10px] font-mono text-[#DFFF00]">META SEMANAL</div><b className="text-white text-sm">{c?.weekWorkouts||0} de {c?.weeklyTarget||3} treinos</b></div><b className="text-[#DFFF00] text-2xl">{c?.weeklyProgress||0}%</b></div><div className="h-2 bg-black border border-[#333] mt-3 overflow-hidden"><div className="h-full bg-[#DFFF00] transition-all" style={{width:`${Math.min(100,Number(c?.weeklyProgress||0))}%`}}/></div></section>
 <div className="grid md:grid-cols-3 gap-3"><button onClick={()=>onNavigate('student_daily')} className="md:col-span-2 bg-[#DFFF00] text-black p-6 text-left"><div className="text-[10px] font-mono font-bold">TREINO ATUAL</div><div className="font-anybody text-3xl font-black uppercase mt-3">{w?.title||'Aguardando prescrição'}</div><div className="text-xs font-mono mt-2">abrir treino →</div></button><button onClick={()=>onNavigate('student_progress')} className="bg-[#121414] border border-[#333] hover:border-[#DFFF00] p-6 text-left"><span className="material-symbols-outlined text-[#DFFF00] text-4xl">monitoring</span><div className="font-anybody font-black uppercase text-white mt-4">Minha evolução</div><div className="text-[10px] font-mono text-gray-500 mt-2">Métricas e histórico</div></button></div>
 {(c?.goals?.length>0||c?.nextAppointment||c?.lastCoachMessage)&&<div className="grid lg:grid-cols-3 gap-3">{c?.goals?.length>0&&<section className="bg-[#121414] border border-[#333] p-4"><div className="text-[10px] font-mono text-[#DFFF00] mb-2">MINHAS METAS</div>{c.goals.map((g:any)=><div key={g.id} className="border-b border-[#222] py-2 text-xs"><b className="text-white">{g.goalType}</b><div className="text-gray-500">{g.targetValue||g.targetText} {g.unit} {g.dueAt&&`• até ${g.dueAt}`}</div></div>)}</section>}{c?.nextAppointment&&<section className="bg-[#121414] border border-[#333] p-4"><div className="text-[10px] font-mono text-[#DFFF00]">PRÓXIMO COMPROMISSO</div><b className="block text-white mt-2">{c.nextAppointment.title}</b><span className="text-xs text-gray-500">{new Date(c.nextAppointment.startsAt).toLocaleString('pt-BR')}</span></section>}{c?.lastCoachMessage&&<button onClick={()=>onNavigate('chat')} className="bg-[#121414] border border-[#333] p-4 text-left hover:border-[#DFFF00]"><div className="text-[10px] font-mono text-[#DFFF00]">MENSAGEM DO TREINADOR</div><b className="block text-white mt-2">{c.lastCoachMessage.senderName}</b><span className="text-xs text-gray-500">{c.lastCoachMessage.text}</span></button>}</div>}
 {(c?.achievements||[]).length>0&&<section className="bg-[#121414] border border-[#333] p-5"><h2 className="font-anybody font-black uppercase text-white mb-3">Conquistas</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">{c.achievements.map((a:any)=><div key={a.id} className="bg-black border border-[#333] p-3"><span className="material-symbols-outlined text-[#DFFF00]">workspace_premium</span><b className="block text-xs text-white mt-1">{a.title}</b><span className="text-[10px] text-gray-500">{a.description}</span></div>)}</div></section>}
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[['assignment','Minha anamnese','anamnese'],['chat','Meu treinador','chat'],['calendar_month','Minha agenda','agenda'],['account_circle','Meu perfil','student_profile']].map(([icon,label,screen])=><button key={label} onClick={()=>onNavigate(screen as ScreenView)} className="bg-[#121414] border border-[#333] hover:border-[#DFFF00] p-5 text-left"><span className="material-symbols-outlined text-[#DFFF00]">{icon}</span><div className="font-anybody font-bold uppercase text-white mt-2">{label}</div></button>)}</div>
 <div className="bg-[#121414] border border-[#333] p-5"><h2 className="font-anybody font-black uppercase text-white mb-4">Notificações</h2>{n.length===0?<div className="text-xs font-mono text-gray-500">Nenhuma notificação.</div>:n.slice(0,8).map(x=><div key={x.id} className="border-b border-[#222] py-3"><div className="text-xs text-white font-bold">{x.title}</div><div className="text-[10px] font-mono text-gray-500">{x.body}</div></div>)}</div></div>;
};
const Stat=({l,v}:{l:string;v:any})=><div className="bg-[#121414] border border-[#333] p-4"><div className="text-[9px] text-gray-500 uppercase">{l}</div><b className="text-2xl text-[#DFFF00]">{v}</b></div>;