import React,{useEffect,useRef,useState} from 'react';
import confetti from 'canvas-confetti';
import {ScreenView} from '../../types';
import {api} from '../../api';
import {ExerciseThumbnail} from '../ExerciseThumbnail';

export const WorkoutExecutionScreen:React.FC<{onNavigate:(s:ScreenView)=>void}>=({onNavigate})=>{
 const [workout,setWorkout]=useState<any>(null),[idx,setIdx]=useState(0),[setNum,setSetNum]=useState(1),[reps,setReps]=useState(10),[load,setLoad]=useState(0),[sessionId,setSessionId]=useState<number|null>(null),[error,setError]=useState('');
 const started=useRef(Date.now());
 useEffect(()=>{api.portal().then(async p=>{const w=p.workouts?.[0];if(!w)return setError('Nenhum treino publicado.');setWorkout(w);setLoad(Number(w.exercises?.[0]?.load)||0);const s=await api.startWorkout(w.id);setSessionId(s.sessionId)}).catch((e:any)=>setError(e.message))},[]);
 const ex=workout?.exercises?.[idx];
 const completeSet=async()=>{if(!ex||!sessionId)return;try{await api.logSet(sessionId,{exerciseId:ex.id,exerciseName:ex.name,setNumber:setNum,reps,load,rpe:ex.rpe||8});confetti({particleCount:35,spread:55,origin:{y:.8},colors:['#DFFF00','#ffffff']});if(setNum<Number(ex.sets||1)){setSetNum(n=>n+1)}else if(idx<(workout.exercises.length-1)){const next=workout.exercises[idx+1];setIdx(i=>i+1);setSetNum(1);setLoad(Number(next.load)||0);setReps(parseInt(String(next.reps))||10)}else{await api.completeSession(sessionId,Math.floor((Date.now()-started.current)/1000));onNavigate('student_progress')}}catch(e:any){setError(e.message)}};
 if(error)return <div className="p-8 border border-red-500/40 bg-[#121414] text-red-300 text-sm">{error}</div>;
 if(!ex)return <div className="p-8 text-gray-400 font-mono">Preparando treino...</div>;
 return <div className="w-full max-w-4xl mx-auto space-y-5"><div className="bg-[#121414] border border-[#333] p-4 flex justify-between"><button onClick={()=>onNavigate('student_daily')} className="text-xs font-mono text-gray-400">✕ SAIR</button><div className="text-center"><div className="text-[10px] text-[#DFFF00] font-mono">EXERCÍCIO {idx+1}/{workout.exercises.length}</div><div className="font-anybody font-bold uppercase text-white">{ex.name}</div></div><span className="text-xs font-mono text-gray-500">SÉRIE {setNum}/{ex.sets}</span></div>
 <div className="bg-[#121414] border border-[#333] overflow-hidden"><div className="aspect-video bg-black relative"><ExerciseThumbnail name={ex.name} category={ex.category||''} equipment={ex.equipment||''} src={ex.thumbnail||''} mediaType={ex.mediaType==='video'?'video':'image'}/><div className="absolute bottom-3 left-3 bg-black/80 border border-[#333] px-3 py-2 text-xs font-mono"><span className="text-[#DFFF00]">ALVO:</span> {ex.reps} reps • descanso {ex.rest}s • {ex.tempo}</div></div>
 <div className="p-6 space-y-5"><div className="grid sm:grid-cols-2 gap-4"><div className="bg-[#181a1a] border border-[#333] p-4 text-center"><div className="text-[10px] font-mono text-gray-500">REPETIÇÕES</div><div className="flex justify-center items-center gap-5 mt-2"><button onClick={()=>setReps(Math.max(1,reps-1))} className="w-10 h-10 bg-black border border-[#444]">-</button><b className="text-4xl text-white">{reps}</b><button onClick={()=>setReps(reps+1)} className="w-10 h-10 bg-black border border-[#444]">+</button></div></div><div className="bg-[#181a1a] border border-[#333] p-4 text-center"><div className="text-[10px] font-mono text-gray-500">CARGA KG</div><div className="flex justify-center items-center gap-5 mt-2"><button onClick={()=>setLoad(Math.max(0,load-2.5))} className="w-12 h-10 bg-black border border-[#444]">-2.5</button><b className="text-4xl text-[#DFFF00]">{load}</b><button onClick={()=>setLoad(load+2.5)} className="w-12 h-10 bg-black border border-[#444]">+2.5</button></div></div></div>{ex.instructions&&<div className="border-l-2 border-[#DFFF00] bg-[#181a1a] p-3 text-xs font-mono text-gray-300"><b className="text-[#DFFF00]">DICA DO COACH:</b> {ex.instructions}</div>}<button onClick={completeSet} className="w-full py-4 bg-[#DFFF00] text-black font-anybody font-black uppercase shadow-[4px_4px_0_#fff]">Concluir Série</button></div></div></div>;
};
