import React from 'react';
import { ScreenView, UserRole } from '../../types';
import { APP_IMAGES } from '../../data/mockData';
interface SidebarProps { currentScreen: ScreenView; onNavigate:(screen:ScreenView)=>void; userRole:UserRole; }
export const Sidebar:React.FC<SidebarProps>=({currentScreen,onNavigate,userRole})=>{
 const coachNavItems=[{id:'coach_dashboard' as ScreenView,label:'Dashboard Coach',icon:'dashboard'},{id:'prescription' as ScreenView,label:'Prescrição RX',icon:'edit_note'},{id:'agenda' as ScreenView,label:'Agenda & Aulas',icon:'calendar_month'},{id:'chat' as ScreenView,label:'Mensagens / Chat',icon:'chat'},{id:'student_progress' as ScreenView,label:'Progresso Alunos',icon:'monitoring'},{id:'admin_system' as ScreenView,label:'Telemetria Admin',icon:'terminal'}];
 const adminNavItems=[{id:'admin_system' as ScreenView,label:'Painel Admin Master',icon:'admin_panel_settings'},{id:'coach_dashboard' as ScreenView,label:'Gestão de Treinadores',icon:'badge'},{id:'student_progress' as ScreenView,label:'Auditoria de Alunos',icon:'group'},{id:'assinatura' as ScreenView,label:'Financeiro & MRR',icon:'payments'},{id:'agenda' as ScreenView,label:'Escala Studio & Aulas',icon:'calendar_month'}];
 const studentNavItems=[{id:'student_hub' as ScreenView,label:'Portal do Aluno',icon:'person'},{id:'student_daily' as ScreenView,label:'Treino de Hoje',icon:'fitness_center'},{id:'workout_execution' as ScreenView,label:'Executar Treino',icon:'play_circle'},{id:'student_progress' as ScreenView,label:'Meu Progresso',icon:'analytics'},{id:'student_profile' as ScreenView,label:'Perfil & Fotos',icon:'account_circle'},{id:'anamnese' as ScreenView,label:'Anamnese Digital',icon:'assignment'},{id:'chat' as ScreenView,label:'Chat com Personal',icon:'chat'},{id:'agenda' as ScreenView,label:'Reservar Aulas',icon:'calendar_month'},{id:'assinatura' as ScreenView,label:'Minha Assinatura',icon:'credit_card'}];
 const navItems=userRole==='admin'?adminNavItems:userRole==='coach'?coachNavItems:studentNavItems;
 const avatar=userRole==='coach'?APP_IMAGES.coachAlexMercer:userRole==='admin'?APP_IMAGES.adminUserAvatar:APP_IMAGES.studentAvatar;
 return <aside className="hidden lg:flex flex-col w-64 bg-[#0a0a0a] border-r border-[#222222] min-h-[calc(100vh-4rem)] p-4 justify-between select-none"><div className="space-y-6"><div className="p-3 bg-[#121414] border border-[#333535] flex items-center gap-3"><div className="w-11 h-11 border border-[#DFFF00] overflow-hidden shrink-0"><img src={avatar} alt="Avatar" referrerPolicy="no-referrer" className="w-full h-full object-cover"/></div><div className="overflow-hidden"><h4 className="font-anybody text-sm font-bold uppercase text-white truncate">{userRole==='coach'?'Treinador':userRole==='admin'?'Administrador':'Aluno'}</h4><span className="text-[10px] font-mono text-[#DFFF00] uppercase block">PULSEFIT.PRO</span></div></div><button onClick={()=>onNavigate(userRole==='coach'?'prescription':'workout_execution')} className="w-full py-2.5 bg-[#DFFF00] text-black font-anybody font-bold text-xs uppercase flex items-center justify-center gap-2 hover:bg-white transition-all shadow-[2px_2px_0px_0px_#ffffff]"><span className="material-symbols-outlined text-base">{userRole==='coach'?'add':'play_arrow'}</span>{userRole==='coach'?'Prescrever Treino':'Iniciar Treino'}</button><nav className="space-y-1"><div className="text-[10px] font-mono uppercase text-[#909378] tracking-widest px-2 py-1">Menu de Controle</div>{navItems.map(item=>{const active=currentScreen===item.id;return <button key={item.id} onClick={()=>onNavigate(item.id)} className={`w-full flex items-center gap-3 px-3 py-2 text-xs font-anybody uppercase font-semibold transition-all text-left ${active?'bg-[#181a1a] text-[#DFFF00] border-l-2 border-[#DFFF00]':'text-[#c6c9ab] hover:text-white hover:bg-[#121414]'}`}><span className="material-symbols-outlined text-lg">{item.icon}</span><span>{item.label}</span></button>})}</nav></div><div className="pt-4 border-t border-[#222222] text-[11px] font-mono text-[#909378] space-y-2"><div className="flex items-center justify-between"><span>SISTEMA:</span><span className="text-[#DFFF00] font-bold">● OPERACIONAL</span></div><button onClick={()=>onNavigate('auth_login')} className="w-full py-1.5 px-2 bg-[#141616] border border-[#333] hover:border-[#DFFF00] text-[10px] text-[#DFFF00] uppercase font-bold">Trocar Conta / Login</button><button onClick={()=>onNavigate('landing')} className="w-full text-left text-[10px] text-gray-500 hover:text-gray-300 uppercase">← Voltar para Landing Page</button></div></aside>;
};
