import React from 'react';
import { ScreenView } from '../../types';
import { ApiUser } from '../../api';
interface SidebarProps { currentScreen: ScreenView; onNavigate:(screen:ScreenView)=>void; user:ApiUser; onLogout:()=>void; }
export const Sidebar:React.FC<SidebarProps>=({currentScreen,onNavigate,user,onLogout})=>{
 const coachNavItems=[{id:'coach_dashboard' as ScreenView,label:'Dashboard',icon:'dashboard'},{id:'prescription' as ScreenView,label:'Alunos & Prescrição',icon:'edit_note'},{id:'fitness_tools' as ScreenView,label:'1RM & Anilhas',icon:'calculate'},{id:'postural_assessment' as ScreenView,label:'Avaliação Postural',icon:'accessibility_new'},{id:'gamification_ranking' as ScreenView,label:'Ranking & Gamificação',icon:'leaderboard'},{id:'student_progress' as ScreenView,label:'Evolução dos Alunos',icon:'monitoring'},{id:'anamnese' as ScreenView,label:'Anamnese',icon:'assignment'},{id:'agenda' as ScreenView,label:'Agenda',icon:'calendar_month'},{id:'chat' as ScreenView,label:'Mensagens',icon:'chat'},{id:'coach_growth' as ScreenView,label:'Crescimento & Leads',icon:'trending_up'},{id:'assinatura' as ScreenView,label:'Plano & Financeiro',icon:'payments'}];
 const adminNavItems=[{id:'admin_system' as ScreenView,label:'Administração Geral',icon:'admin_panel_settings'},{id:'assinatura' as ScreenView,label:'Planos & Receita',icon:'payments'}];
 const studentNavItems=[{id:'student_hub' as ScreenView,label:'Meu Painel',icon:'person'},{id:'student_daily' as ScreenView,label:'Treino de Hoje',icon:'fitness_center'},{id:'workout_execution' as ScreenView,label:'Executar Treino',icon:'play_circle'},{id:'fitness_tools' as ScreenView,label:'1RM & Anilhas',icon:'calculate'},{id:'postural_assessment' as ScreenView,label:'Minha Postura',icon:'accessibility_new'},{id:'gamification_ranking' as ScreenView,label:'Ranking & Conquistas',icon:'leaderboard'},{id:'student_checkin' as ScreenView,label:'Check-in Semanal',icon:'fact_check'},{id:'student_progress' as ScreenView,label:'Minha Evolução',icon:'analytics'},{id:'student_profile' as ScreenView,label:'Perfil',icon:'account_circle'},{id:'anamnese' as ScreenView,label:'Anamnese',icon:'assignment'},{id:'chat' as ScreenView,label:'Meu Treinador',icon:'chat'},{id:'agenda' as ScreenView,label:'Agenda',icon:'calendar_month'},{id:'assinatura' as ScreenView,label:'Financeiro',icon:'credit_card'}];
 const navItems=user.role==='admin'?adminNavItems:user.role==='coach'?coachNavItems:studentNavItems;const initials=user.name.split(' ').slice(0,2).map(n=>n[0]).join('').toUpperCase();const role=user.role==='coach'?'Treinador':user.role==='admin'?'Administrador':'Aluno';
 return <aside className="hidden lg:flex flex-col w-64 bg-[#0a0a0a] border-r border-[#222222] min-h-[calc(100vh-4rem)] p-4 justify-between select-none"><div className="space-y-6"><div className="p-3 bg-[#121414] border border-[#333535] flex items-center gap-3"><div className="w-11 h-11 border border-[#DFFF00] bg-black text-[#DFFF00] grid place-items-center font-anybody font-black text-xs shrink-0">{initials}</div><div className="overflow-hidden"><h4 className="font-anybody text-sm font-bold uppercase text-white truncate">{user.name}</h4><span className="text-[10px] font-mono text-[#DFFF00] uppercase block">{role}</span><span className="text-[9px] font-mono text-gray-600 truncate block">{user.email}</span></div></div>{user.role==='coach'&&<button onClick={()=>onNavigate('prescription')} className="w-full py-2.5 bg-[#DFFF00] text-black font-anybody font-bold text-xs uppercase">+ Nova prescrição</button>}{user.role==='student'&&<button onClick={()=>onNavigate('student_daily')} className="w-full py-2.5 bg-[#DFFF00] text-black font-anybody font-bold text-xs uppercase">Ver treino de hoje</button>}<nav className="space-y-1">{navItems.map(item=>{const active=currentScreen===item.id;return <button key={item.id} onClick={()=>onNavigate(item.id)} className={`w-full flex items-center gap-3 px-3 py-2 text-xs font-anybody uppercase font-semibold text-left ${active?'bg-[#181a1a] text-[#DFFF00] border-l-2 border-[#DFFF00]':'text-[#c6c9ab] hover:text-white hover:bg-[#121414]'}`}><span className="material-symbols-outlined text-lg">{item.icon}</span><span>{item.label}</span></button>})}</nav></div><div className="pt-4 border-t border-[#222222]"><button onClick={onLogout} className="w-full py-2 border border-[#333] hover:border-red-500 text-[10px] text-gray-400 hover:text-red-400 uppercase font-bold">Sair da conta</button></div></aside>;
};
