import React,{useState} from 'react';
import {ScreenView,UserRole} from '../../types';
import {APP_IMAGES} from '../../data/mockData';
interface Props{currentScreen:ScreenView;onNavigate:(s:ScreenView)=>void;userRole:UserRole;onRoleChange:(r:UserRole)=>void;onOpenImageGallery:()=>void;}
export const TopBar:React.FC<Props>=({currentScreen,onNavigate,userRole,onRoleChange,onOpenImageGallery})=>{
 const [open,setOpen]=useState(false);const screens:[ScreenView,string,string][]=[['landing','Landing & Planos','public'],['auth_login','Login / Autenticação','login'],['coach_dashboard','Coach Dashboard','dashboard'],['prescription','Prescrição de Treino','edit_note'],['student_hub','Hub Central do Aluno','person'],['student_daily','Treino de Hoje','fitness_center'],['workout_execution','Execução Ativa','play_circle'],['student_progress','Dashboard de Progresso','analytics'],['student_profile','Perfil & Transformação','account_circle'],['anamnese','Anamnese Digital','assignment'],['chat','Chat com Personal','chat'],['agenda','Agenda & Aulas','calendar_month'],['assinatura','Assinatura & Planos','credit_card'],['admin_system','Diretoria & Admin Geral','terminal']];
 const avatar=userRole==='coach'?APP_IMAGES.coachAlexMercer:userRole==='admin'?APP_IMAGES.adminUserAvatar:APP_IMAGES.studentAvatar;
 return <header className="sticky top-0 z-40 bg-[#0a0a0a]/95 backdrop-blur border-b border-[#222222]"><div className="max-w-7xl mx-auto px-3 sm:px-6 h-16 flex items-center justify-between gap-3"><button onClick={()=>onNavigate('landing')} className="flex items-center gap-2"><div className="w-8 h-8 bg-[#DFFF00] text-black font-black font-anybody flex items-center justify-center text-lg">⚡</div><div className="text-left"><span className="font-anybody font-black text-lg tracking-tight uppercase text-white">PULSEFIT<span className="text-[#DFFF00]">.PRO</span></span><span className="text-[9px] font-mono tracking-widest text-[#909378] uppercase block">ELITE PERFORMANCE LAB</span></div></button><div className="relative"><button onClick={()=>setOpen(!open)} className="flex items-center gap-2 px-3 py-1.5 bg-[#141616] border border-[#333535] hover:border-[#DFFF00] text-xs font-anybody font-bold uppercase"><span className="material-symbols-outlined text-[#DFFF00] text-base">apps</span><span className="hidden md:inline text-[#DFFF00]">Telas</span></button>{open&&<div className="absolute top-full mt-2 left-1/2 -translate-x-1/2 w-72 bg-[#121414] border-2 border-[#DFFF00] shadow-2xl z-50 p-2 max-h-[75vh] overflow-y-auto">{screens.map(([id,label,icon])=><button key={id} onClick={()=>{onNavigate(id);setOpen(false)}} className={`w-full flex items-center gap-2 p-2 text-left text-xs font-anybody uppercase ${currentScreen===id?'bg-[#DFFF00] text-black font-bold':'text-gray-300 hover:bg-[#1f2121]'}`}><span className="material-symbols-outlined text-sm">{icon}</span>{label}</button>)}</div>}</div><div className="flex items-center gap-2"><button onClick={onOpenImageGallery} className="hidden md:flex items-center gap-1 px-2 py-1 border border-[#333] hover:border-[#DFFF00] text-[10px] uppercase text-[#DFFF00]"><span className="material-symbols-outlined text-sm">image</span>Galeria</button><button onClick={()=>onNavigate('auth_login')} className="px-2 py-1 border border-[#333535] hover:border-[#DFFF00] text-[11px] font-bold uppercase">Login</button><div className="hidden sm:flex bg-[#121212] border border-[#333333] p-0.5 text-[10px] font-mono">{(['coach','student','admin'] as UserRole[]).map(r=><button key={r} onClick={()=>onRoleChange(r)} className={`px-2 py-1 uppercase font-bold ${userRole===r?'bg-[#DFFF00] text-black':'text-gray-400'}`}>{r}</button>)}</div><button onClick={()=>onNavigate('student_profile')} className="w-9 h-9 overflow-hidden border border-[#333] hover:border-[#DFFF00]"><img src={avatar} alt="Perfil" className="w-full h-full object-cover"/></button></div></div></header>;
};
