<?php
// PulseFit V15 — Admin Master + IA assistiva.
function pf_v15_local_summary(array $r):string{
    $name=$r['student']['name']??'Aluno';$parts=[];$parts[]=$name.' realizou '.($r['workouts']??0).' treino(s) nos últimos '.($r['periodDays']??30).' dias, com aderência estimada de '.($r['adherence']??0).'%. ';$a=$r['averages']??[];if(($a['pain']??0)>=6)$parts[]='A média de dor está elevada e merece revisão do treinador. ';if(($a['fatigue']??0)>=7)$parts[]='A fadiga média está alta. ';if(($r['overduePayments']??0)>0)$parts[]='Existe pendência financeira. ';if(($r['workouts']??0)===0)$parts[]='Não há treino concluído no período. ';if(empty($parts[1]))$parts[]='Os indicadores não mostram alerta crítico automático neste período. ';return trim(implode('',$parts));
}
function pf_v15_gemini(string $prompt):?string{
    $key=trim((string)getenv('GEMINI_API_KEY'));if($key==='')return null;$model=trim((string)getenv('GEMINI_MODEL'))?:'gemini-flash-latest';$url='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode($model).':generateContent?key='.rawurlencode($key);$payload=json_encode(['contents'=>[['parts'=>[['text'=>$prompt]]]],'generationConfig'=>['temperature'=>0.2,'maxOutputTokens'=>500]],JSON_UNESCAPED_UNICODE);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>$payload,CURLOPT_TIMEOUT=>15]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($code<200||$code>=300||!is_string($raw))return null;$d=json_decode($raw,true);$text=$d['candidates'][0]['content']['parts'][0]['text']??null;return is_string($text)&&trim($text)!==''?trim($text):null;
}

if($method==='GET'&&$route==='/admin/master-metrics'){
    pf_require_admin_level('super_admin','finance','read_only');
    $out=[];$out['coachesTotal']=(int)$pdo->query('SELECT COUNT(*) FROM users WHERE role="coach" AND archived_at IS NULL')->fetchColumn();$out['coachesActive']=(int)$pdo->query('SELECT COUNT(*) FROM users WHERE role="coach" AND status="active" AND archived_at IS NULL')->fetchColumn();$out['studentsTotal']=(int)$pdo->query('SELECT COUNT(*) FROM students WHERE archived_at IS NULL')->fetchColumn();$out['studentsActive']=(int)$pdo->query('SELECT COUNT(*) FROM students WHERE status="active" AND archived_at IS NULL')->fetchColumn();$out['trials']=(int)$pdo->query('SELECT COUNT(*) FROM coach_profiles WHERE subscription_status="trialing"')->fetchColumn();$out['paidSubscriptions']=(int)$pdo->query('SELECT COUNT(*) FROM coach_profiles WHERE subscription_status="active" AND plan_code!="trial"')->fetchColumn();$out['paidCents30d']=(int)$pdo->query('SELECT COALESCE(SUM(amount_cents),0) FROM payments WHERE status="paid" AND paid_at>=datetime("now","-30 days")')->fetchColumn();$out['pendingCents']=(int)$pdo->query('SELECT COALESCE(SUM(amount_cents),0) FROM payments WHERE status="pending"')->fetchColumn();$out['workouts30d']=(int)$pdo->query('SELECT COUNT(*) FROM workout_sessions WHERE completed_at IS NOT NULL AND started_at>=datetime("now","-30 days")')->fetchColumn();$out['leads30d']=(int)$pdo->query('SELECT COUNT(*) FROM coach_leads WHERE created_at>=datetime("now","-30 days")')->fetchColumn();$out['wonLeads30d']=(int)$pdo->query('SELECT COUNT(*) FROM coach_leads WHERE status="won" AND updated_at>=datetime("now","-30 days")')->fetchColumn();json_response(['metrics'=>$out]);
}
if($method==='POST'&&$route==='/ai/student-summary'){
    verify_csrf();$u=require_role('coach','admin');$in=body();$sid=(int)($in['studentId']??0);$days=max(7,min(90,(int)($in['days']??30)));$report=pf_v13_report($pdo,$u,$sid,$days);$local=pf_v15_local_summary($report);$prompt="Você é um copiloto para personal trainer. Resuma os dados abaixo em português do Brasil, em até 6 frases, sem diagnóstico médico e sem prescrever tratamento. Destaque aderência, evolução e pontos que o treinador deve revisar. Dados: ".json_encode($report,JSON_UNESCAPED_UNICODE);$ai=pf_v15_gemini($prompt);audit($pdo,(int)$u['id'],'generate','ai_summary',$sid,['days'=>$days,'provider'=>$ai?'gemini':'local']);json_response(['summary'=>$ai?:$local,'provider'=>$ai?'gemini':'local','report'=>$report]);
}
