<?php
// Biblioteca-base PulseFit. Idempotente: exercícios de sistema não são duplicados.
function pf_seed_exercise_library(PDO $pdo): void {
    $items = [
      // Peito
      ['Supino reto com barra','PEITO','COMPOSTO','BARRA'],['Supino inclinado com barra','PEITO','COMPOSTO','BARRA'],['Supino declinado com barra','PEITO','COMPOSTO','BARRA'],['Supino reto com halteres','PEITO','COMPOSTO','HALTERES'],['Supino inclinado com halteres','PEITO','COMPOSTO','HALTERES'],['Supino máquina','PEITO','COMPOSTO','MÁQUINA'],['Chest press convergente','PEITO','COMPOSTO','MÁQUINA'],['Crucifixo reto com halteres','PEITO','ISOLADO','HALTERES'],['Crucifixo inclinado com halteres','PEITO','ISOLADO','HALTERES'],['Crossover alto','PEITO','ISOLADO','CABO'],['Crossover médio','PEITO','ISOLADO','CABO'],['Crossover baixo','PEITO','ISOLADO','CABO'],['Peck deck','PEITO','ISOLADO','MÁQUINA'],['Flexão de braços','PEITO','COMPOSTO','PESO CORPORAL'],['Flexão declinada','PEITO','COMPOSTO','PESO CORPORAL'],
      // Costas
      ['Barra fixa pronada','COSTAS','COMPOSTO','PESO CORPORAL'],['Barra fixa supinada','COSTAS','COMPOSTO','PESO CORPORAL'],['Puxada frente pronada','COSTAS','COMPOSTO','CABO'],['Puxada frente neutra','COSTAS','COMPOSTO','CABO'],['Puxada frente supinada','COSTAS','COMPOSTO','CABO'],['Remada curvada com barra','COSTAS','COMPOSTO','BARRA'],['Remada cavalinho','COSTAS','COMPOSTO','BARRA'],['Remada unilateral com halter','COSTAS','COMPOSTO','HALTERES'],['Remada baixa triangulo','COSTAS','COMPOSTO','CABO'],['Remada baixa pronada','COSTAS','COMPOSTO','CABO'],['Remada articulada','COSTAS','COMPOSTO','MÁQUINA'],['Pulldown unilateral','COSTAS','ISOLADO','CABO'],['Pullover no cabo','COSTAS','ISOLADO','CABO'],['Pullover com halter','COSTAS','ISOLADO','HALTERES'],['Face pull','COSTAS','ISOLADO','CABO'],
      // Ombros
      ['Desenvolvimento militar com barra','OMBROS','COMPOSTO','BARRA'],['Desenvolvimento com halteres','OMBROS','COMPOSTO','HALTERES'],['Desenvolvimento máquina','OMBROS','COMPOSTO','MÁQUINA'],['Arnold press','OMBROS','COMPOSTO','HALTERES'],['Elevação lateral com halteres','OMBROS','ISOLADO','HALTERES'],['Elevação lateral no cabo','OMBROS','ISOLADO','CABO'],['Elevação lateral máquina','OMBROS','ISOLADO','MÁQUINA'],['Elevação frontal com halteres','OMBROS','ISOLADO','HALTERES'],['Elevação frontal com barra','OMBROS','ISOLADO','BARRA'],['Crucifixo inverso máquina','OMBROS','ISOLADO','MÁQUINA'],['Crucifixo inverso com halteres','OMBROS','ISOLADO','HALTERES'],['Remada alta com barra','OMBROS','COMPOSTO','BARRA'],
      // Bíceps
      ['Rosca direta com barra','BÍCEPS','ISOLADO','BARRA'],['Rosca direta barra W','BÍCEPS','ISOLADO','BARRA'],['Rosca alternada','BÍCEPS','ISOLADO','HALTERES'],['Rosca martelo','BÍCEPS','ISOLADO','HALTERES'],['Rosca inclinada','BÍCEPS','ISOLADO','HALTERES'],['Rosca Scott com barra W','BÍCEPS','ISOLADO','BARRA'],['Rosca Scott máquina','BÍCEPS','ISOLADO','MÁQUINA'],['Rosca no cabo','BÍCEPS','ISOLADO','CABO'],['Rosca Bayesian','BÍCEPS','ISOLADO','CABO'],['Rosca concentrada','BÍCEPS','ISOLADO','HALTERES'],['Rosca inversa','BÍCEPS','ISOLADO','BARRA'],
      // Tríceps
      ['Tríceps pulley barra reta','TRÍCEPS','ISOLADO','CABO'],['Tríceps corda','TRÍCEPS','ISOLADO','CABO'],['Tríceps francês unilateral','TRÍCEPS','ISOLADO','HALTERES'],['Tríceps francês bilateral','TRÍCEPS','ISOLADO','HALTERES'],['Tríceps testa barra W','TRÍCEPS','ISOLADO','BARRA'],['Tríceps coice','TRÍCEPS','ISOLADO','HALTERES'],['Supino fechado','TRÍCEPS','COMPOSTO','BARRA'],['Mergulho em paralelas','TRÍCEPS','COMPOSTO','PESO CORPORAL'],['Tríceps máquina','TRÍCEPS','ISOLADO','MÁQUINA'],
      // Quadríceps
      ['Agachamento livre','QUADRÍCEPS','COMPOSTO','BARRA'],['Agachamento frontal','QUADRÍCEPS','COMPOSTO','BARRA'],['Agachamento goblet','QUADRÍCEPS','COMPOSTO','HALTERES'],['Hack squat','QUADRÍCEPS','COMPOSTO','MÁQUINA'],['Leg press 45°','QUADRÍCEPS','COMPOSTO','MÁQUINA'],['Leg press horizontal','QUADRÍCEPS','COMPOSTO','MÁQUINA'],['Cadeira extensora','QUADRÍCEPS','ISOLADO','MÁQUINA'],['Afundo com halteres','QUADRÍCEPS','COMPOSTO','HALTERES'],['Passada caminhando','QUADRÍCEPS','COMPOSTO','HALTERES'],['Agachamento búlgaro','QUADRÍCEPS','COMPOSTO','HALTERES'],['Step-up','QUADRÍCEPS','COMPOSTO','HALTERES'],['Sissy squat','QUADRÍCEPS','ISOLADO','PESO CORPORAL'],
      // Posteriores
      ['Levantamento terra romeno','POSTERIOR','COMPOSTO','BARRA'],['Stiff com barra','POSTERIOR','COMPOSTO','BARRA'],['Stiff com halteres','POSTERIOR','COMPOSTO','HALTERES'],['Mesa flexora','POSTERIOR','ISOLADO','MÁQUINA'],['Cadeira flexora','POSTERIOR','ISOLADO','MÁQUINA'],['Flexora em pé unilateral','POSTERIOR','ISOLADO','MÁQUINA'],['Nordic curl','POSTERIOR','COMPOSTO','PESO CORPORAL'],['Good morning','POSTERIOR','COMPOSTO','BARRA'],['Glute ham raise','POSTERIOR','COMPOSTO','MÁQUINA'],
      // Glúteos
      ['Hip thrust com barra','GLÚTEO','COMPOSTO','BARRA'],['Elevação pélvica máquina','GLÚTEO','COMPOSTO','MÁQUINA'],['Elevação pélvica unilateral','GLÚTEO','COMPOSTO','PESO CORPORAL'],['Coice no cabo','GLÚTEO','ISOLADO','CABO'],['Coice máquina','GLÚTEO','ISOLADO','MÁQUINA'],['Abdução de quadril máquina','GLÚTEO','ISOLADO','MÁQUINA'],['Abdução de quadril no cabo','GLÚTEO','ISOLADO','CABO'],['Pull through','GLÚTEO','COMPOSTO','CABO'],['Frog pump','GLÚTEO','ISOLADO','PESO CORPORAL'],
      // Panturrilhas
      ['Panturrilha em pé máquina','PANTURRILHA','ISOLADO','MÁQUINA'],['Panturrilha sentado','PANTURRILHA','ISOLADO','MÁQUINA'],['Panturrilha no leg press','PANTURRILHA','ISOLADO','MÁQUINA'],['Panturrilha unilateral em pé','PANTURRILHA','ISOLADO','PESO CORPORAL'],['Panturrilha donkey','PANTURRILHA','ISOLADO','MÁQUINA'],
      // Core
      ['Prancha frontal','CORE','ISOMÉTRICO','PESO CORPORAL'],['Prancha lateral','CORE','ISOMÉTRICO','PESO CORPORAL'],['Abdominal crunch','CORE','ISOLADO','PESO CORPORAL'],['Crunch no cabo','CORE','ISOLADO','CABO'],['Elevação de pernas suspenso','CORE','COMPOSTO','PESO CORPORAL'],['Elevação de pernas no banco','CORE','COMPOSTO','PESO CORPORAL'],['Ab wheel','CORE','COMPOSTO','RODA ABDOMINAL'],['Dead bug','CORE','CONTROLE MOTOR','PESO CORPORAL'],['Bird dog','CORE','CONTROLE MOTOR','PESO CORPORAL'],['Pallof press','CORE','ANTI-ROTAÇÃO','CABO'],['Russian twist','CORE','ROTAÇÃO','PESO CORPORAL'],['Farmer walk','CORE','ESTABILIZAÇÃO','HALTERES'],
      // Trapézio / antebraço
      ['Encolhimento com barra','TRAPÉZIO','ISOLADO','BARRA'],['Encolhimento com halteres','TRAPÉZIO','ISOLADO','HALTERES'],['Rosca de punho','ANTEBRAÇO','ISOLADO','BARRA'],['Rosca de punho inversa','ANTEBRAÇO','ISOLADO','BARRA'],['Farmer carry','ANTEBRAÇO','FUNCIONAL','HALTERES'],
      // Adutores / quadril
      ['Adutora máquina','ADUTORES','ISOLADO','MÁQUINA'],['Adução de quadril no cabo','ADUTORES','ISOLADO','CABO'],['Copenhagen plank','ADUTORES','ISOMÉTRICO','PESO CORPORAL'],
      // Levantamentos / potência
      ['Levantamento terra convencional','CORPO TODO','COMPOSTO','BARRA'],['Levantamento terra sumô','CORPO TODO','COMPOSTO','BARRA'],['Power clean','CORPO TODO','POTÊNCIA','BARRA'],['Hang clean','CORPO TODO','POTÊNCIA','BARRA'],['Push press','CORPO TODO','POTÊNCIA','BARRA'],['Thruster','CORPO TODO','POTÊNCIA','BARRA'],['Kettlebell swing','CORPO TODO','POTÊNCIA','KETTLEBELL'],['Turkish get-up','CORPO TODO','FUNCIONAL','KETTLEBELL'],
      // Funcional / condicionamento
      ['Burpee','FUNCIONAL','CONDICIONAMENTO','PESO CORPORAL'],['Mountain climber','FUNCIONAL','CONDICIONAMENTO','PESO CORPORAL'],['Battle rope ondas alternadas','FUNCIONAL','CONDICIONAMENTO','CORDA NAVAL'],['Sled push','FUNCIONAL','CONDICIONAMENTO','SLED'],['Sled pull','FUNCIONAL','CONDICIONAMENTO','SLED'],['Box jump','FUNCIONAL','PLIOMETRIA','CAIXA'],['Salto vertical','FUNCIONAL','PLIOMETRIA','PESO CORPORAL'],['Medicine ball slam','FUNCIONAL','POTÊNCIA','MEDICINE BALL'],['Wall ball','FUNCIONAL','CONDICIONAMENTO','MEDICINE BALL'],['Bear crawl','FUNCIONAL','CONDICIONAMENTO','PESO CORPORAL'],
      // Cardio
      ['Caminhada na esteira','CARDIO','AERÓBIO','ESTEIRA'],['Corrida na esteira','CARDIO','AERÓBIO','ESTEIRA'],['Bicicleta ergométrica','CARDIO','AERÓBIO','BIKE'],['Air bike','CARDIO','CONDICIONAMENTO','AIR BIKE'],['Remo ergômetro','CARDIO','AERÓBIO','REMO'],['Elíptico','CARDIO','AERÓBIO','ELÍPTICO'],['Escada ergométrica','CARDIO','AERÓBIO','ESCADA'],['Pular corda','CARDIO','CONDICIONAMENTO','CORDA'],
      // Mobilidade / ativação
      ['Mobilidade de tornozelo','MOBILIDADE','MOBILIDADE','PESO CORPORAL'],['Mobilidade de quadril 90/90','MOBILIDADE','MOBILIDADE','PESO CORPORAL'],['Alongamento flexor de quadril','MOBILIDADE','MOBILIDADE','PESO CORPORAL'],['Rotação torácica','MOBILIDADE','MOBILIDADE','PESO CORPORAL'],['Wall slide','MOBILIDADE','MOBILIDADE','PESO CORPORAL'],['Band pull-apart','MOBILIDADE','ATIVAÇÃO','ELÁSTICO'],['Monster walk','GLÚTEO','ATIVAÇÃO','ELÁSTICO'],['Caminhada lateral com miniband','GLÚTEO','ATIVAÇÃO','ELÁSTICO'],['Rotação externa de ombro','OMBROS','ATIVAÇÃO','ELÁSTICO'],['Scapular push-up','MOBILIDADE','ATIVAÇÃO','PESO CORPORAL']
    ];
    $exists=$pdo->prepare('SELECT 1 FROM exercise_library WHERE is_system=1 AND lower(name)=lower(:name) LIMIT 1');
    $insert=$pdo->prepare('INSERT INTO exercise_library(coach_id,name,category,exercise_type,equipment,media_url,media_type,instructions,default_sets,default_reps,default_rest,default_rpe,default_tempo,is_system) VALUES(NULL,:name,:category,:type,:equipment,NULL,"image",:instructions,:sets,:reps,:rest,:rpe,:tempo,1)');
    foreach($items as [$name,$category,$type,$equipment]){
        $exists->execute(['name'=>$name]); if($exists->fetchColumn()) continue;
        $sets=in_array($category,['CARDIO','MOBILIDADE'],true)?1:3;
        $reps=$category==='CARDIO'?'10-30 min':($category==='MOBILIDADE'?'8-12':'8-12');
        $rest=$category==='CARDIO'?0:($category==='MOBILIDADE'?30:60);
        $instructions='Ajuste amplitude, carga e execução conforme objetivo, nível e condição do aluno.';
        $insert->execute(['name'=>$name,'category'=>$category,'type'=>$type,'equipment'=>$equipment,'instructions'=>$instructions,'sets'=>$sets,'reps'=>$reps,'rest'=>$rest,'rpe'=>8,'tempo'=>'2-0-2-0']);
    }
}
