<?php
// PulseFit V14 — crescimento: página pública do treinador, leads e CRM.
function pf_v14_migrate(PDO $pdo):void{
    $pdo->exec('CREATE TABLE IF NOT EXISTS coach_public_profiles(coach_id INTEGER PRIMARY KEY,slug TEXT UNIQUE,bio TEXT,headline TEXT,photo_url TEXT,whatsapp TEXT,city TEXT,state TEXT,services_json TEXT,public_enabled INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
    $pdo->exec('CREATE TABLE IF NOT EXISTS coach_leads(id INTEGER PRIMARY KEY AUTOINCREMENT,coach_id INTEGER NOT NULL,name TEXT NOT NULL,email TEXT,phone TEXT,goal TEXT,source TEXT NOT NULL DEFAULT "public_profile",status TEXT NOT NULL DEFAULT "new",notes TEXT,converted_student_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(converted_student_id) REFERENCES students(id) ON DELETE SET NULL)');
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_coach_leads ON coach_leads(coach_id,status,created_at)');
}
pf_v14_migrate($pdo);
function pf_v14_slug(string $s):string{$s=iconv('UTF-8','ASCII//TRANSLIT',$s)?:$s;$s=strtolower(preg_replace('/[^a-zA-Z0-9]+/','-',trim($s)));return trim($s,'-')?:'treinador';}

if($method==='GET'&&$route==='/coach/public-profile'){$u=require_role('coach');$q=$pdo->prepare('SELECT slug,bio,headline,photo_url AS photoUrl,whatsapp,city,state,services_json AS servicesJson,public_enabled AS publicEnabled,updated_at AS updatedAt FROM coach_public_profiles WHERE coach_id=:id');$q->execute(['id'=>$u['id']]);$p=$q->fetch()?:[];if(isset($p['servicesJson'])){$p['services']=json_decode((string)$p['servicesJson'],true)?:[];unset($p['servicesJson']);}json_response(['profile'=>$p]);}
if($method==='PUT'&&$route==='/coach/public-profile'){
    verify_csrf();$u=require_role('coach');$in=body();$slug=pf_v14_slug((string)($in['slug']??$u['name']));$q=$pdo->prepare('INSERT INTO coach_public_profiles(coach_id,slug,bio,headline,photo_url,whatsapp,city,state,services_json,public_enabled,updated_at) VALUES(:id,:slug,:bio,:headline,:photo,:whatsapp,:city,:state,:services,:enabled,CURRENT_TIMESTAMP) ON CONFLICT(coach_id) DO UPDATE SET slug=:slug,bio=:bio,headline=:headline,photo_url=:photo,whatsapp=:whatsapp,city=:city,state=:state,services_json=:services,public_enabled=:enabled,updated_at=CURRENT_TIMESTAMP');$q->execute(['id'=>$u['id'],'slug'=>$slug,'bio'=>trim((string)($in['bio']??'')),'headline'=>trim((string)($in['headline']??'')),'photo'=>trim((string)($in['photoUrl']??'')),'whatsapp'=>trim((string)($in['whatsapp']??'')),'city'=>trim((string)($in['city']??'')),'state'=>trim((string)($in['state']??'')),'services'=>json_encode($in['services']??[],JSON_UNESCAPED_UNICODE),'enabled'=>!empty($in['publicEnabled'])?1:0]);audit($pdo,(int)$u['id'],'update','public_profile',(int)$u['id']);json_response(['ok'=>true,'slug'=>$slug]);
}
if($method==='GET'&&preg_match('#^/public/coach/([a-z0-9-]+)$#',$route,$m)){
    $q=$pdo->prepare('SELECT u.id,u.name,u.cref,cp.specialty,pp.slug,pp.bio,pp.headline,pp.photo_url AS photoUrl,pp.whatsapp,pp.city,pp.state,pp.services_json AS servicesJson FROM coach_public_profiles pp JOIN users u ON u.id=pp.coach_id LEFT JOIN coach_profiles cp ON cp.user_id=u.id WHERE pp.slug=:slug AND pp.public_enabled=1 AND u.status="active" AND u.archived_at IS NULL');$q->execute(['slug'=>$m[1]]);$p=$q->fetch();if(!$p)json_response(['error'=>'Perfil não encontrado.'],404);$p['services']=json_decode((string)$p['servicesJson'],true)?:[];unset($p['servicesJson']);json_response(['profile'=>$p]);
}
if($method==='POST'&&preg_match('#^/public/coach/([a-z0-9-]+)/lead$#',$route,$m)){
    $in=body();$name=trim((string)($in['name']??''));if(mb_strlen($name)<2)json_response(['error'=>'Informe seu nome.'],422);$q=$pdo->prepare('SELECT coach_id FROM coach_public_profiles WHERE slug=:slug AND public_enabled=1');$q->execute(['slug'=>$m[1]]);$coach=(int)$q->fetchColumn();if(!$coach)json_response(['error'=>'Perfil indisponível.'],404);$email=trim((string)($in['email']??''));if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))json_response(['error'=>'E-mail inválido.'],422);$q=$pdo->prepare('INSERT INTO coach_leads(coach_id,name,email,phone,goal,source) VALUES(:coach,:name,:email,:phone,:goal,:source)');$q->execute(['coach'=>$coach,'name'=>$name,'email'=>$email,'phone'=>trim((string)($in['phone']??'')),'goal'=>trim((string)($in['goal']??'')),'source'=>trim((string)($in['source']??'public_profile'))]);db()->prepare('INSERT INTO notifications(user_id,title,body) VALUES(:u,"Novo lead",:b)')->execute(['u'=>$coach,'b'=>$name.' demonstrou interesse no seu acompanhamento.']);json_response(['ok'=>true],201);
}
if($method==='GET'&&$route==='/coach/leads'){$u=require_role('coach');$status=trim((string)($_GET['status']??''));$sql='SELECT id,name,email,phone,goal,source,status,notes,converted_student_id AS convertedStudentId,created_at AS createdAt,updated_at AS updatedAt FROM coach_leads WHERE coach_id=:coach';$args=['coach'=>$u['id']];if($status!==''){$sql.=' AND status=:status';$args['status']=$status;}$sql.=' ORDER BY id DESC';$q=$pdo->prepare($sql);$q->execute($args);json_response(['leads'=>$q->fetchAll()]);}
if($method==='PATCH'&&preg_match('#^/coach/leads/(\d+)$#',$route,$m)){$u=require_role('coach');verify_csrf();$in=body();$status=in_array(($in['status']??''),['new','contacted','qualified','won','lost'],true)?$in['status']:'new';$q=$pdo->prepare('UPDATE coach_leads SET status=:s,notes=:n,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND coach_id=:coach');$q->execute(['s'=>$status,'n'=>trim((string)($in['notes']??'')),'id'=>(int)$m[1],'coach'=>$u['id']]);if(!$q->rowCount())json_response(['error'=>'Lead não encontrado.'],404);json_response(['ok'=>true]);}

// Status de infraestrutura móvel. O envio Web Push remoto depende de HTTPS + VAPID configurado na VPS.
if($method==='GET'&&$route==='/pwa/status')json_response(['installable'=>true,'pushConfigured'=>trim((string)getenv('VAPID_PUBLIC_KEY'))!=='','requiresHttps'=>true]);

require __DIR__.'/admin_ai.php';
