<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';

$method=$_SERVER['REQUEST_METHOD']??'GET';
$route=route_path();
$pdo=db();
require __DIR__.'/migrations.php';
require __DIR__.'/security.php';

if($method==='GET'&&$route==='/health')json_response(['ok'=>true,'installed'=>is_file(PF_DB),'sqlite'=>extension_loaded('pdo_sqlite')]);

if($method==='POST'&&$route==='/auth/login'){
  $in=body();$email=clean_email($in['email']??'');$password=(string)($in['password']??'');
  $q=$pdo->prepare('SELECT id,name,email,password_hash,role,code,cref,status,must_change_password AS mustChangePassword FROM users WHERE email=:email LIMIT 1');$q->execute(['email'=>$email]);$u=$q->fetch();
  if(!$u||$u['status']!=='active'||!password_verify($password,(string)$u['password_hash']))json_response(['error'=>'E-mail ou senha incorretos.'],401);
  start_secure_session();session_regenerate_id(true);unset($u['password_hash']);$_SESSION['user']=$u;$_SESSION['csrf']=bin2hex(random_bytes(32));$pdo->prepare('UPDATE users SET last_login_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$u['id']]);audit($pdo,(int)$u['id'],'login','user',(int)$u['id']);json_response(['user'=>$u,'csrf'=>$_SESSION['csrf']]);
}
if($method==='GET'&&$route==='/auth/me')json_response(['user'=>current_user(),'csrf'=>csrf_token()]);
if($method==='POST'&&$route==='/auth/logout'){verify_csrf();start_secure_session();$_SESSION=[];session_destroy();json_response(['ok'=>true]);}
if($method==='POST'&&$route==='/auth/forgot-password'){
  $in=body();$email=strtolower(trim((string)($in['email']??'')));if(filter_var($email,FILTER_VALIDATE_EMAIL)){$q=$pdo->prepare('SELECT id,name,email FROM users WHERE email=:email AND status="active" AND role IN("admin","coach")');$q->execute(['email'=>$email]);if($u=$q->fetch()){$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$pdo->prepare('DELETE FROM password_reset_tokens WHERE user_id=:id')->execute(['id'=>$u['id']]);$pdo->prepare('INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES(:id,:hash,datetime("now","+1 hour"))')->execute(['id'=>$u['id'],'hash'=>$hash]);send_reset_email($u['email'],$u['name'],$token);}}json_response(['ok'=>true,'message'=>'Se a conta existir, o e-mail será enviado.']);
}
if($method==='POST'&&$route==='/auth/reset-password'){
  $in=body();$token=(string)($in['token']??'');$password=(string)($in['password']??'');if(strlen($token)!==64||strlen($password)<12)json_response(['error'=>'Link inválido ou senha muito curta.'],422);$q=$pdo->prepare('SELECT id,user_id FROM password_reset_tokens WHERE token_hash=:hash AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP');$q->execute(['hash'=>hash('sha256',$token)]);$r=$q->fetch();if(!$r)json_response(['error'=>'Link expirado ou já utilizado.'],422);$pdo->beginTransaction();try{$pdo->prepare('UPDATE users SET password_hash=:hash,must_change_password=0 WHERE id=:id')->execute(['hash'=>password_hash($password,PASSWORD_DEFAULT),'id'=>$r['user_id']]);$pdo->prepare('UPDATE password_reset_tokens SET used_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$r['id']]);$pdo->commit();json_response(['ok'=>true]);}catch(Throwable $e){$pdo->rollBack();json_response(['error'=>'Falha ao redefinir senha.'],500);}
}

if($method==='GET'&&$route==='/students'){
  $u=require_role('admin','coach');$sql='SELECT s.id,s.name,s.email,s.status,s.program_name AS programName,s.phase,s.last_check_in AS lastCheckIn,s.age,s.height,s.weight,s.body_fat AS bodyFat,s.coach_id AS assignedCoachId,c.name AS assignedCoachName,s.plan_name AS planName,s.joined_at AS joinedDate,COALESCE(s.avatar,"") AS avatar FROM students s JOIN users c ON c.id=s.coach_id';$args=[];if($u['role']==='coach'){$sql.=' WHERE s.coach_id=:coach';$args['coach']=$u['id'];}$sql.=' ORDER BY s.name';$q=$pdo->prepare($sql);$q->execute($args);json_response(['students'=>$q->fetchAll()]);
}
if($method==='POST'&&$route==='/students'){
  verify_csrf();$actor=require_role('admin','coach');$in=body();$name=trim((string)($in['name']??''));$email=clean_email($in['email']??'');if(mb_strlen($name)<3)json_response(['error'=>'Nome inválido.'],422);$coach=$actor['role']==='coach'?(int)$actor['id']:(int)($in['coachId']??0);if(!$coach)json_response(['error'=>'Selecione o treinador.'],422);$pass=(string)($in['password']??'');if($pass==='' )$pass=temporary_password();if(strlen($pass)<12)json_response(['error'=>'Senha inicial precisa ter 12 caracteres.'],422);$pdo->beginTransaction();try{$q=$pdo->prepare('INSERT INTO users(name,email,password_hash,role,code,status,must_change_password) VALUES(:name,:email,:hash,"student",:code,"active",1)');$q->execute(['name'=>$name,'email'=>$email,'hash'=>password_hash($pass,PASSWORD_DEFAULT),'code'=>'PF-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6))]);$uid=(int)$pdo->lastInsertId();$q=$pdo->prepare('INSERT INTO students(user_id,coach_id,name,email,status,program_name,phase,age,height,weight,body_fat,plan_name) VALUES(:uid,:coach,:name,:email,"active",:program,:phase,:age,:height,:weight,:bf,:plan)');$q->execute(['uid'=>$uid,'coach'=>$coach,'name'=>$name,'email'=>$email,'program'=>trim((string)($in['programName']??'Programa inicial')),'phase'=>trim((string)($in['phase']??'Fase 1')),'age'=>(int)($in['age']??0),'height'=>(float)($in['height']??0),'weight'=>(float)($in['weight']??0),'bf'=>(float)($in['bodyFat']??0),'plan'=>trim((string)($in['planName']??''))]);$sid=(int)$pdo->lastInsertId();$pdo->commit();$sent=send_access_email($email,$name,$pass,'student');audit($pdo,(int)$actor['id'],'create','student',$sid);json_response(['ok'=>true,'id'=>$sid,'temporaryPassword'=>$pass,'emailSent'=>$sent],201);}catch(Throwable $e){$pdo->rollBack();json_response(['error'=>str_contains($e->getMessage(),'UNIQUE')?'Este e-mail já está cadastrado.':'Não foi possível cadastrar o aluno.'],str_contains($e->getMessage(),'UNIQUE')?409:500);}
}
if($method==='PATCH'&&preg_match('#^/students/(\d+)/status$#',$route,$m)){
  verify_csrf();$actor=require_role('admin','coach');$id=(int)$m[1];$in=body();$status=($in['status']??'')==='active'?'active':'inactive';$sql='SELECT user_id FROM students WHERE id=:id'.($actor['role']==='coach'?' AND coach_id=:coach':'');$args=['id'=>$id];if($actor['role']==='coach')$args['coach']=$actor['id'];$q=$pdo->prepare($sql);$q->execute($args);$s=$q->fetch();if(!$s)json_response(['error'=>'Aluno não encontrado.'],404);$pdo->prepare('UPDATE users SET status=:s WHERE id=:id')->execute(['s'=>$status,'id'=>$s['user_id']]);$pdo->prepare('UPDATE students SET status=:s WHERE id=:id')->execute(['s'=>$status,'id'=>$id]);json_response(['ok'=>true]);
}

if($method==='GET'&&$route==='/coaches'){
  require_role('admin');$rows=$pdo->query('SELECT u.id,u.code,u.name,u.email,COALESCE(u.cref,"") AS cref,COALESCE(cp.specialty,"") AS specialty,COUNT(s.id) AS studentsCount,u.status,COALESCE(cp.unit,"") AS unit,"" AS avatar FROM users u LEFT JOIN coach_profiles cp ON cp.user_id=u.id LEFT JOIN students s ON s.coach_id=u.id WHERE u.role="coach" GROUP BY u.id ORDER BY u.name')->fetchAll();json_response(['coaches'=>$rows]);
}
if($method==='POST'&&$route==='/coaches'){
  verify_csrf();$actor=require_role('admin');$in=body();$name=trim((string)($in['name']??''));$email=clean_email($in['email']??'');if(mb_strlen($name)<3)json_response(['error'=>'Nome inválido.'],422);$pass=(string)($in['password']??'');if($pass==='')$pass=temporary_password();if(strlen($pass)<12)json_response(['error'=>'Senha inicial precisa ter 12 caracteres.'],422);$pdo->beginTransaction();try{$q=$pdo->prepare('INSERT INTO users(name,email,password_hash,role,code,cref,status,must_change_password) VALUES(:name,:email,:hash,"coach",:code,:cref,"active",1)');$q->execute(['name'=>$name,'email'=>$email,'hash'=>password_hash($pass,PASSWORD_DEFAULT),'code'=>'TR-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6)),'cref'=>trim((string)($in['cref']??''))]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO coach_profiles(user_id,specialty,unit) VALUES(:id,:specialty,:unit)')->execute(['id'=>$id,'specialty'=>trim((string)($in['specialty']??'')),'unit'=>trim((string)($in['unit']??''))]);$pdo->commit();$sent=send_access_email($email,$name,$pass,'coach');audit($pdo,(int)$actor['id'],'create','coach',$id);json_response(['ok'=>true,'id'=>$id,'temporaryPassword'=>$pass,'emailSent'=>$sent],201);}catch(Throwable $e){$pdo->rollBack();json_response(['error'=>'Não foi possível cadastrar o treinador.'],500);}
}
if($method==='PATCH'&&preg_match('#^/coaches/(\d+)/status$#',$route,$m)){verify_csrf();require_role('admin');$in=body();$status=($in['status']??'')==='active'?'active':'inactive';$pdo->prepare('UPDATE users SET status=:s WHERE id=:id AND role="coach"')->execute(['s'=>$status,'id'=>(int)$m[1]]);json_response(['ok'=>true]);}

if($method==='GET'&&$route==='/workouts'){
  $u=require_role('admin','coach');$sql='SELECT w.id,w.student_id AS studentId,s.name AS studentName,w.title,w.status,w.created_at AS createdAt,w.published_at AS publishedAt,w.archived_at AS archivedAt FROM workouts w JOIN students s ON s.id=w.student_id';$args=[];if($u['role']==='coach'){$sql.=' WHERE w.coach_id=:coach';$args['coach']=$u['id'];}$sql.=' ORDER BY w.id DESC';$q=$pdo->prepare($sql);$q->execute($args);json_response(['workouts'=>$q->fetchAll()]);
}
if($method==='POST'&&$route==='/workouts'){
  verify_csrf();$u=require_role('coach');$in=body();$sid=(int)($in['studentId']??0);$title=trim((string)($in['title']??''));$status=($in['status']??'draft')==='published'?'published':'draft';$xs=$in['exercises']??[];if(mb_strlen($title)<3||!is_array($xs)||!count($xs))json_response(['error'=>'Informe título e exercícios.'],422);$check=$pdo->prepare('SELECT id FROM students WHERE id=:id AND coach_id=:coach');$check->execute(['id'=>$sid,'coach'=>$u['id']]);if(!$check->fetch())json_response(['error'=>'Aluno não encontrado.'],404);$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO workouts(student_id,coach_id,title,status,published_at) VALUES(:student,:coach,:title,:status,'.($status==='published'?'CURRENT_TIMESTAMP':'NULL').')')->execute(['student'=>$sid,'coach'=>$u['id'],'title'=>$title,'status'=>$status]);$wid=(int)$pdo->lastInsertId();$add=$pdo->prepare('INSERT INTO exercises(workout_id,position,library_exercise_id,name,sets,reps,load,rest_seconds,notes,thumbnail,category,exercise_type,equipment,rpe,tempo,instructions) VALUES(:w,:p,:lib,:name,:sets,:reps,:load,:rest,:notes,:thumb,:cat,:type,:eq,:rpe,:tempo,:instructions)');foreach(array_slice($xs,0,60) as $i=>$x){$add->execute(['w'=>$wid,'p'=>$i,'lib'=>isset($x['libraryExerciseId'])?(int)$x['libraryExerciseId']:null,'name'=>trim((string)($x['name']??'')),'sets'=>max(1,(int)($x['sets']??1)),'reps'=>trim((string)($x['reps']??'')),'load'=>trim((string)($x['load']??'')),'rest'=>max(0,(int)($x['rest']??60)),'notes'=>trim((string)($x['notes']??'')),'thumb'=>trim((string)($x['thumbnail']??'')),'cat'=>trim((string)($x['category']??'')),'type'=>trim((string)($x['type']??'')),'eq'=>trim((string)($x['equipment']??'')),'rpe'=>max(1,min(10,(int)($x['rpe']??8))),'tempo'=>trim((string)($x['tempo']??'2-0-2-0')),'instructions'=>trim((string)($x['instructions']??''))]);}$pdo->commit();json_response(['ok'=>true,'id'=>$wid],201);}catch(Throwable $e){$pdo->rollBack();json_response(['error'=>'Falha ao salvar ficha.'],500);}
}
if($method==='POST'&&preg_match('#^/workouts/(\d+)/duplicate$#',$route,$m)){
  verify_csrf();$u=require_role('coach');$id=(int)$m[1];$q=$pdo->prepare('SELECT * FROM workouts WHERE id=:id AND coach_id=:coach');$q->execute(['id'=>$id,'coach'=>$u['id']]);$w=$q->fetch();if(!$w)json_response(['error'=>'Ficha não encontrada.'],404);$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO workouts(student_id,coach_id,title,status) VALUES(:student,:coach,:title,"draft")')->execute(['student'=>$w['student_id'],'coach'=>$u['id'],'title'=>$w['title'].' — cópia']);$new=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO exercises(workout_id,position,library_exercise_id,name,sets,reps,load,rest_seconds,notes,thumbnail,category,exercise_type,equipment,rpe,tempo,instructions) SELECT :new,position,library_exercise_id,name,sets,reps,load,rest_seconds,notes,thumbnail,category,exercise_type,equipment,rpe,tempo,instructions FROM exercises WHERE workout_id=:old')->execute(['new'=>$new,'old'=>$id]);$pdo->commit();json_response(['ok'=>true,'id'=>$new],201);}catch(Throwable $e){$pdo->rollBack();json_response(['error'=>'Falha ao duplicar ficha.'],500);}
}
if($method==='PATCH'&&preg_match('#^/workouts/(\d+)/(archive|publish)$#',$route,$m)){verify_csrf();$u=require_role('coach');$sql=$m[2]==='archive'?'UPDATE workouts SET archived_at=CURRENT_TIMESTAMP,status="draft" WHERE id=:id AND coach_id=:coach':'UPDATE workouts SET archived_at=NULL,status="published",published_at=CURRENT_TIMESTAMP WHERE id=:id AND coach_id=:coach';$q=$pdo->prepare($sql);$q->execute(['id'=>(int)$m[1],'coach'=>$u['id']]);json_response(['ok'=>true]);}

if($method==='GET'&&$route==='/dashboard'){
  $u=require_role('coach');$q=$pdo->prepare('SELECT COUNT(*) FROM students WHERE coach_id=:id AND status="active"');$q->execute(['id'=>$u['id']]);$active=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT COUNT(*) FROM students WHERE coach_id=:id');$q->execute(['id'=>$u['id']]);$total=(int)$q->fetchColumn();json_response(['activeStudents'=>$active,'totalStudents'=>$total]);
}
if($method==='GET'&&$route==='/student/portal'){
  $u=require_role('student');$q=$pdo->prepare('SELECT s.* FROM students s WHERE s.user_id=:uid');$q->execute(['uid'=>$u['id']]);$s=$q->fetch();if(!$s)json_response(['error'=>'Aluno não encontrado.'],404);$q=$pdo->prepare('SELECT id,title,status,published_at AS publishedAt FROM workouts WHERE student_id=:id AND status="published" AND archived_at IS NULL ORDER BY id DESC');$q->execute(['id'=>$s['id']]);$rows=$q->fetchAll();$ex=$pdo->prepare('SELECT id,library_exercise_id AS libraryExerciseId,name,sets,reps,load,rest_seconds AS rest,COALESCE(thumbnail,"") AS thumbnail,COALESCE(category,"") AS category,COALESCE(exercise_type,"") AS type,COALESCE(equipment,"") AS equipment,COALESCE(rpe,8) AS rpe,COALESCE(tempo,"2-0-2-0") AS tempo,COALESCE(instructions,COALESCE(notes,"")) AS instructions FROM exercises WHERE workout_id=:id ORDER BY position');foreach($rows as &$w){$ex->execute(['id'=>$w['id']]);$w['exercises']=$ex->fetchAll();}json_response(['student'=>$s,'workouts'=>$rows]);
}

if($method==='GET'&&$route==='/appointments'){$u=current_user();$sql='SELECT a.id,a.student_id AS studentId,s.name AS studentName,a.title,a.starts_at AS startsAt,a.ends_at AS endsAt,a.status,a.notes FROM appointments a LEFT JOIN students s ON s.id=a.student_id';$args=[];if($u['role']==='coach'){$sql.=' WHERE a.coach_id=:id';$args['id']=$u['id'];}elseif($u['role']==='student'){$sql.=' WHERE s.user_id=:id';$args['id']=$u['id'];}$sql.=' ORDER BY a.starts_at';$q=$pdo->prepare($sql);$q->execute($args);json_response(['appointments'=>$q->fetchAll()]);}
if($method==='POST'&&$route==='/appointments'){verify_csrf();$u=require_role('coach');$in=body();$sid=(int)($in['studentId']??0);$title=trim((string)($in['title']??'Compromisso'));$start=(string)($in['startsAt']??'');$end=(string)($in['endsAt']??'');$pdo->prepare('INSERT INTO appointments(coach_id,student_id,title,starts_at,ends_at,notes) VALUES(:coach,:student,:title,:start,:end,:notes)')->execute(['coach'=>$u['id'],'student'=>$sid,'title'=>$title,'start'=>$start,'end'=>$end,'notes'=>trim((string)($in['notes']??''))]);json_response(['ok'=>true],201);}
if($method==='GET'&&$route==='/payments'){$u=current_user();$sql='SELECT p.id,p.student_id AS studentId,s.name AS studentName,p.amount_cents AS amountCents,p.due_date AS dueDate,p.paid_at AS paidAt,p.status,p.description FROM payments p JOIN students s ON s.id=p.student_id';$args=[];if($u['role']==='coach'){$sql.=' WHERE p.coach_id=:id';$args['id']=$u['id'];}elseif($u['role']==='student'){$sql.=' WHERE s.user_id=:id';$args['id']=$u['id'];}$sql.=' ORDER BY p.due_date DESC';$q=$pdo->prepare($sql);$q->execute($args);json_response(['payments'=>$q->fetchAll()]);}
if($method==='POST'&&$route==='/payments'){verify_csrf();$u=require_role('coach');$in=body();$pdo->prepare('INSERT INTO payments(coach_id,student_id,amount_cents,due_date,description) VALUES(:coach,:student,:amount,:due,:description)')->execute(['coach'=>$u['id'],'student'=>(int)($in['studentId']??0),'amount'=>max(0,(int)round(((float)($in['amount']??0))*100)),'due'=>(string)($in['dueDate']??''),'description'=>trim((string)($in['description']??''))]);json_response(['ok'=>true],201);}
if($method==='GET'&&$route==='/notifications'){$u=current_user();$q=$pdo->prepare('SELECT id,title,body,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=:id ORDER BY id DESC LIMIT 100');$q->execute(['id'=>$u['id']]);json_response(['notifications'=>$q->fetchAll()]);}
if($method==='GET'&&preg_match('#^/students/(\d+)/metrics$#',$route,$m)){$u=require_role('admin','coach','student');$q=$pdo->prepare('SELECT id,weight,body_fat AS bodyFat,chest,waist,biceps,thighs,created_at AS createdAt FROM metrics WHERE student_id=:id ORDER BY id DESC');$q->execute(['id'=>(int)$m[1]]);json_response(['metrics'=>$q->fetchAll()]);}
if($method==='POST'&&preg_match('#^/students/(\d+)/metrics$#',$route,$m)){verify_csrf();$u=current_user();$in=body();$sid=(int)$m[1];$pdo->prepare('INSERT INTO metrics(student_id,weight,body_fat,chest,waist,biceps,thighs) VALUES(:id,:weight,:bf,:chest,:waist,:biceps,:thighs)')->execute(['id'=>$sid,'weight'=>(float)($in['weight']??0),'bf'=>(float)($in['bodyFat']??0),'chest'=>(float)($in['chest']??0),'waist'=>(float)($in['waist']??0),'biceps'=>(float)($in['biceps']??0),'thighs'=>(float)($in['thighs']??0)]);$pdo->prepare('UPDATE students SET weight=:w,body_fat=:bf WHERE id=:id')->execute(['w'=>(float)($in['weight']??0),'bf'=>(float)($in['bodyFat']??0),'id'=>$sid]);json_response(['ok'=>true],201);}

require __DIR__.'/features.php';
json_response(['error'=>'Rota não encontrada.'],404);