<?php
// Migrações de performance executadas explicitamente no deploy.
$pdo->exec('CREATE TABLE IF NOT EXISTS strength_tests(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,coach_id INTEGER NOT NULL,exercise_name TEXT NOT NULL,load_kg REAL NOT NULL,reps INTEGER NOT NULL,formula TEXT NOT NULL,estimated_1rm REAL NOT NULL,notes TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
$pdo->exec('CREATE INDEX IF NOT EXISTS idx_strength_tests_student ON strength_tests(student_id,created_at)');
$pdo->exec('CREATE TABLE IF NOT EXISTS physical_tests(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,coach_id INTEGER NOT NULL,test_name TEXT NOT NULL,result_value REAL,result_unit TEXT,classification TEXT,notes TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
$pdo->exec('CREATE INDEX IF NOT EXISTS idx_physical_tests_student ON physical_tests(student_id,created_at)');
$pdo->exec('CREATE TABLE IF NOT EXISTS postural_assessments(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,coach_id INTEGER NOT NULL,view_type TEXT NOT NULL DEFAULT "global",findings_json TEXT NOT NULL DEFAULT "[]",angles_json TEXT NOT NULL DEFAULT "{}",notes TEXT,corrective_plan TEXT,score INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
$pdo->exec('CREATE INDEX IF NOT EXISTS idx_postural_student ON postural_assessments(student_id,created_at)');
$pdo->exec('CREATE TABLE IF NOT EXISTS ranking_settings(coach_id INTEGER PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 0,metric TEXT NOT NULL DEFAULT "xp",updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
