<?php
// PulseFit — ferramentas de performance, avaliação postural e ranking opcional.
function pf_perf_migrate(PDO $pdo):void{
  $pdo->exec('CREATE TABLE IF NOT EXISTS strength_tests(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,coach_id INTEGER NOT NULL,exercise_name TEXT NOT NULL,load_kg REAL NOT NULL,reps INTEGER NOT NULL,formula TEXT NOT NULL,estimated_1rm REAL NOT NULL,notes TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_strength_tests_student ON strength_tests(student_id,created_at)');
  $pdo->exec('CREATE TABLE IF NOT EXISTS physical_tests(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,coach_id INTEGER NOT NULL,test_name TEXT NOT NULL,result_value REAL,result_unit TEXT,classification TEXT,notes TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_physical_tests_student ON physical_tests(student_id,created_at)');
  $pdo->exec('CREATE TABLE IF NOT EXISTS postural_assessments(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,coach_id INTEGER NOT NULL,view_type TEXT NOT NULL DEFAULT "global",findings_json TEXT NOT NULL DEFAULT "[]",angles_json TEXT NOT NULL DEFAULT "{}",notes TEXT,corrective_plan TEXT,score INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
  $pdo->exec('CREATE INDEX IF NOT EXISTS idx_postural_student ON postural_assessments(student_id,created_at)');
  $pdo->exec('CREATE TABLE IF NOT EXISTS ranking_settings(coach_id INTEGER PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 0,metric TEXT NOT NULL DEFAULT "xp",updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(coach_id) REFERENCES users(id) ON DELETE CASCADE)');
}
pf_perf_migrate($pdo);
function pf_perf_student(PDO $pdo,array $u,?int $sid=null):array{
  if($u['role']==='student'){$q=$pdo->prepare('SELECT * FROM students WHERE user_id=:uid AND archived_at IS NULL');$q->execute(['uid'=>$u['id']]);}
  elseif($u['role']==='coach'){$q=$pdo->prepare('SELECT * FROM students WHERE id=:id AND coach_id=:coach AND archived_at IS NULL');$q->execute(['id'=>$sid,'coach'=>$u['id']]);}
  else{$q=$pdo->prepare('SELECT * FROM students WHERE id=:id');$q->execute(['id'=>$sid]);}
  $s=$q->fetch();if(!$s)json_response(['error'=>'Aluno não encontrado.'],404);return $s;
}
function pf_1rm(float $load,int $reps,string $formula):float{
  if($load<=0||$reps<1)return 0;if($reps===1)return round($load,1);$r=min(20,$reps);
  $v=match($formula){'brzycki'=>$load*(36/(37-$r)),'lander'=>$load/(1.013-0.0267123*$r),'lombardi'=>$load*pow($r,0.10),default=>$load*(1+$r/30)};
  return round($v,1);
}
if($method==='POST'&&$route==='/fitness/1rm/calculate'){
  $u=current_user();$in=body();$load=max(0,(float)($in['loadKg']??0));$reps=max(1,min(20,(int)($in['reps']??1)));$formula=in_array(($in['formula']??''),['epley','brzycki','lander','lombardi'],true)?$in['formula']:'epley';$one=pf_1rm($load,$reps,$formula);$zones=[];foreach([100,95,90,85,80,75,70,65,60,55,50] as $p)$zones[]=['percent'=>$p,'loadKg'=>round($one*$p/100,1)];json_response(['estimated1rm'=>$one,'formula'=>$formula,'zones'=>$zones]);
}
if($method==='GET'&&$route==='/fitness/strength-tests'){
  $u=current_user();$sid=(int)($_GET['studentId']??0);$s=pf_perf_student($pdo,$u,$sid?:null);$q=$pdo->prepare('SELECT id,exercise_name AS exerciseName,load_kg AS loadKg,reps,formula,estimated_1rm AS estimated1rm,notes,created_at AS createdAt FROM strength_tests WHERE student_id=:sid ORDER BY id DESC LIMIT 100');$q->execute(['sid'=>$s['id']]);json_response(['tests'=>$q->fetchAll(),'student'=>['id'=>$s['id'],'name'=>$s['name']]]);
}
if($method==='POST'&&$route==='/fitness/strength-tests'){
  verify_csrf();$u=require_role('coach');$in=body();$s=pf_perf_student($pdo,$u,(int)($in['studentId']??0));$exercise=trim((string)($in['exerciseName']??''));$load=max(0,(float)($in['loadKg']??0));$reps=max(1,min(20,(int)($in['reps']??1)));$formula=in_array(($in['formula']??''),['epley','brzycki','lander','lombardi'],true)?$in['formula']:'epley';if(mb_strlen($exercise)<2||$load<=0)json_response(['error'=>'Informe exercício e carga válidos.'],422);$one=pf_1rm($load,$reps,$formula);$q=$pdo->prepare('INSERT INTO strength_tests(student_id,coach_id,exercise_name,load_kg,reps,formula,estimated_1rm,notes) VALUES(:sid,:coach,:ex,:load,:reps,:formula,:one,:notes)');$q->execute(['sid'=>$s['id'],'coach'=>$u['id'],'ex'=>$exercise,'load'=>$load,'reps'=>$reps,'formula'=>$formula,'one'=>$one,'notes'=>trim((string)($in['notes']??''))]);audit($pdo,(int)$u['id'],'create','strength_test',(int)$pdo->lastInsertId(),['studentId'=>$s['id'],'estimated1rm'=>$one]);json_response(['ok'=>true,'id'=>(int)$pdo->lastInsertId(),'estimated1rm'=>$one],201);
}
if($method==='GET'&&$route==='/fitness/physical-tests'){
  $u=current_user();$s=pf_perf_student($pdo,$u,(int)($_GET['studentId']??0)?:null);$q=$pdo->prepare('SELECT id,test_name AS testName,result_value AS resultValue,result_unit AS resultUnit,classification,notes,created_at AS createdAt FROM physical_tests WHERE student_id=:sid ORDER BY id DESC LIMIT 100');$q->execute(['sid'=>$s['id']]);json_response(['tests'=>$q->fetchAll()]);
}
if($method==='POST'&&$route==='/fitness/physical-tests'){
  verify_csrf();$u=require_role('coach');$in=body();$s=pf_perf_student($pdo,$u,(int)($in['studentId']??0));$name=trim((string)($in['testName']??''));if(mb_strlen($name)<2)json_response(['error'=>'Informe o teste.'],422);$q=$pdo->prepare('INSERT INTO physical_tests(student_id,coach_id,test_name,result_value,result_unit,classification,notes) VALUES(:sid,:coach,:name,:value,:unit,:class,:notes)');$q->execute(['sid'=>$s['id'],'coach'=>$u['id'],'name'=>$name,'value'=>isset($in['resultValue'])?(float)$in['resultValue']:null,'unit'=>trim((string)($in['resultUnit']??'')),'class'=>trim((string)($in['classification']??'')),'notes'=>trim((string)($in['notes']??''))]);audit($pdo,(int)$u['id'],'create','physical_test',(int)$pdo->lastInsertId(),['studentId'=>$s['id']]);json_response(['ok'=>true,'id'=>(int)$pdo->lastInsertId()],201);
}
if($method==='GET'&&$route==='/postural-assessments'){
  $u=current_user();$s=pf_perf_student($pdo,$u,(int)($_GET['studentId']??0)?:null);$q=$pdo->prepare('SELECT id,view_type AS viewType,findings_json AS findingsJson,angles_json AS anglesJson,notes,corrective_plan AS correctivePlan,score,created_at AS createdAt FROM postural_assessments WHERE student_id=:sid ORDER BY id DESC LIMIT 50');$q->execute(['sid'=>$s['id']]);$rows=$q->fetchAll();foreach($rows as &$r){$r['findings']=json_decode((string)$r['findingsJson'],true)?:[];$r['angles']=json_decode((string)$r['anglesJson'],true)?:[];unset($r['findingsJson'],$r['anglesJson']);}json_response(['assessments'=>$rows,'student'=>['id'=>$s['id'],'name'=>$s['name']]]);
}
if($method==='POST'&&$route==='/postural-assessments'){
  verify_csrf();$u=require_role('coach');$in=body();$s=pf_perf_student($pdo,$u,(int)($in['studentId']??0));$view=in_array(($in['viewType']??''),['global','anterior','posterior','lateral_direita','lateral_esquerda'],true)?$in['viewType']:'global';$score=isset($in['score'])?max(0,min(100,(int)$in['score'])):null;$q=$pdo->prepare('INSERT INTO postural_assessments(student_id,coach_id,view_type,findings_json,angles_json,notes,corrective_plan,score) VALUES(:sid,:coach,:view,:findings,:angles,:notes,:plan,:score)');$q->execute(['sid'=>$s['id'],'coach'=>$u['id'],'view'=>$view,'findings'=>json_encode($in['findings']??[],JSON_UNESCAPED_UNICODE),'angles'=>json_encode($in['angles']??[],JSON_UNESCAPED_UNICODE),'notes'=>trim((string)($in['notes']??'')),'plan'=>trim((string)($in['correctivePlan']??'')),'score'=>$score]);audit($pdo,(int)$u['id'],'create','postural_assessment',(int)$pdo->lastInsertId(),['studentId'=>$s['id']]);json_response(['ok'=>true,'id'=>(int)$pdo->lastInsertId()],201);
}
if($method==='GET'&&$route==='/ranking'){
  $u=current_user();$coachId=0;if($u['role']==='coach')$coachId=(int)$u['id'];elseif($u['role']==='student'){$s=pf_perf_student($pdo,$u);$coachId=(int)$s['coach_id'];}elseif($u['role']==='admin')$coachId=(int)($_GET['coachId']??0);if(!$coachId)json_response(['enabled'=>false,'ranking'=>[]]);$q=$pdo->prepare('SELECT enabled,metric FROM ranking_settings WHERE coach_id=:id');$q->execute(['id'=>$coachId]);$set=$q->fetch()?:['enabled'=>0,'metric'=>'xp'];if($u['role']==='student'&&!$set['enabled'])json_response(['enabled'=>false,'metric'=>$set['metric'],'ranking'=>[]]);$metric=(string)$set['metric'];$order=$metric==='tonnage'?'volume DESC':($metric==='frequency'?'sessions DESC':'xp DESC');$sql='SELECT s.id,s.name,COUNT(ws.id) sessions,COALESCE(SUM(ws.total_volume),0) volume,(COUNT(ws.id)*100 + COALESCE(SUM(ws.total_volume),0)/1000) xp FROM students s LEFT JOIN workout_sessions ws ON ws.student_id=s.id AND ws.completed_at IS NOT NULL AND ws.started_at>=datetime("now","-30 days") WHERE s.coach_id=:coach AND s.archived_at IS NULL GROUP BY s.id ORDER BY '.$order.',s.name LIMIT 50';$q=$pdo->prepare($sql);$q->execute(['coach'=>$coachId]);json_response(['enabled'=>(bool)$set['enabled'],'metric'=>$metric,'ranking'=>$q->fetchAll()]);
}
if($method==='PUT'&&$route==='/ranking/settings'){
  verify_csrf();$u=require_role('coach');$in=body();$metric=in_array(($in['metric']??''),['xp','frequency','tonnage'],true)?$in['metric']:'xp';$enabled=!empty($in['enabled'])?1:0;$q=$pdo->prepare('INSERT INTO ranking_settings(coach_id,enabled,metric,updated_at) VALUES(:id,:enabled,:metric,CURRENT_TIMESTAMP) ON CONFLICT(coach_id) DO UPDATE SET enabled=:enabled,metric=:metric,updated_at=CURRENT_TIMESTAMP');$q->execute(['id'=>$u['id'],'enabled'=>$enabled,'metric'=>$metric]);audit($pdo,(int)$u['id'],'update','ranking_settings',(int)$u['id'],['enabled'=>$enabled,'metric'=>$metric]);json_response(['ok'=>true]);
}
