<?php
// PulseFit — prontidão operacional, risco global e histórico assistido por IA.
function pf_prod_count(PDO $pdo,string $sql,array $args=[]):int{$q=$pdo->prepare($sql);$q->execute($args);return (int)$q->fetchColumn();}
function pf_prod_latest_backup():?array{
    $files=glob(PF_STORAGE.'/backups/pulsefit-*.sqlite')?:[];if(!$files)return null;usort($files,fn($a,$b)=>filemtime($b)<=>filemtime($a));$f=$files[0];return ['name'=>basename($f),'createdAt'=>gmdate('c',filemtime($f)),'size'=>(int)filesize($f)];
}
function pf_prod_risks(PDO $pdo,?int $coachId=null):array{
    $coachFilter=$coachId?' AND s.coach_id=:coach':'';$args=$coachId?['coach'=>$coachId]:[];
    $inactive7d=pf_prod_count($pdo,'SELECT COUNT(*) FROM students s WHERE s.archived_at IS NULL'.$coachFilter.' AND NOT EXISTS(SELECT 1 FROM workout_sessions ws WHERE ws.student_id=s.id AND ws.completed_at IS NOT NULL AND ws.started_at>=datetime("now","-7 days"))',$args);
    $overdue=pf_prod_count($pdo,'SELECT COUNT(*) FROM payments p JOIN students s ON s.id=p.student_id WHERE p.status="pending" AND date(p.due_date)<date("now") AND s.archived_at IS NULL'.$coachFilter,$args);
    $pain=pf_prod_count($pdo,'SELECT COUNT(DISTINCT c.student_id) FROM checkins c JOIN students s ON s.id=c.student_id WHERE c.created_at>=datetime("now","-7 days") AND c.pain_level>=6 AND s.archived_at IS NULL'.$coachFilter,$args);
    $fatigue=pf_prod_count($pdo,'SELECT COUNT(DISTINCT c.student_id) FROM checkins c JOIN students s ON s.id=c.student_id WHERE c.created_at>=datetime("now","-7 days") AND c.fatigue_level>=7 AND s.archived_at IS NULL'.$coachFilter,$args);
    $lowEnergy=pf_prod_count($pdo,'SELECT COUNT(DISTINCT c.student_id) FROM checkins c JOIN students s ON s.id=c.student_id WHERE c.created_at>=datetime("now","-7 days") AND c.energy_level<=3 AND s.archived_at IS NULL'.$coachFilter,$args);
    return ['inactive7d'=>$inactive7d,'overduePayments'=>$overdue,'highPain'=>$pain,'highFatigue'=>$fatigue,'lowEnergy'=>$lowEnergy,'attentionTotal'=>$inactive7d+$overdue+$pain+$fatigue+$lowEnergy];
}
if($method==='GET'&&$route==='/coach/risk-summary'){$u=require_role('coach');json_response(['risks'=>pf_prod_risks($pdo,(int)$u['id'])]);}
if($method==='GET'&&$route==='/admin/risk-dashboard'){$u=pf_require_admin_level('super_admin','support','finance','read_only');$risks=pf_prod_risks($pdo);$risks['trialsExpiring7d']=pf_prod_count($pdo,'SELECT COUNT(*) FROM coach_profiles WHERE subscription_status="trialing" AND trial_ends_at IS NOT NULL AND datetime(trial_ends_at)>=datetime("now") AND datetime(trial_ends_at)<=datetime("now","+7 days")');$risks['trialsExpired']=pf_prod_count($pdo,'SELECT COUNT(*) FROM coach_profiles WHERE subscription_status="trialing" AND trial_ends_at IS NOT NULL AND datetime(trial_ends_at)<datetime("now")');$risks['subscriptionsPastDue']=pf_prod_count($pdo,'SELECT COUNT(*) FROM coach_profiles WHERE subscription_status="past_due"');json_response(['risks'=>$risks]);}
if($method==='GET'&&$route==='/admin/readiness'){$u=pf_require_admin_level('super_admin','support','finance','read_only');$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$backup=pf_prod_latest_backup();$integrations=['mercadoPago'=>trim((string)getenv('MERCADOPAGO_ACCESS_TOKEN'))!=='','stripe'=>trim((string)getenv('STRIPE_SECRET_KEY'))!=='','stripeWebhook'=>trim((string)getenv('STRIPE_WEBHOOK_SECRET'))!=='','gemini'=>trim((string)getenv('GEMINI_API_KEY'))!=='','vapidPublic'=>trim((string)getenv('VAPID_PUBLIC_KEY'))!=='','vapidPrivate'=>trim((string)getenv('VAPID_PRIVATE_KEY'))!=='','https'=>$https];$checks=['storageWritable'=>is_writable(PF_STORAGE),'databaseExists'=>is_file(PF_DB),'databaseWritable'=>is_file(PF_DB)&&is_writable(PF_DB),'recentBackup'=>$backup&&strtotime((string)$backup['createdAt'])>=time()-172800,'paymentsConfigured'=>$integrations['mercadoPago']||$integrations['stripe'],'pushReady'=>$https&&$integrations['vapidPublic']&&$integrations['vapidPrivate'],'aiExternalReady'=>$integrations['gemini']];$critical=array_values(array_keys(array_filter($checks,fn($v)=>$v===false)));json_response(['ready'=>!in_array('storageWritable',$critical,true)&&!in_array('databaseWritable',$critical,true),'checks'=>$checks,'integrations'=>$integrations,'latestBackup'=>$backup,'risks'=>pf_prod_risks($pdo),'missing'=>$critical]);}
if($method==='GET'&&$route==='/reports/student/history'){$u=current_user();$sid=(int)($_GET['studentId']??0);if($u['role']==='student'){$s=pf_v11_resolve_student($u);$sid=(int)$s['id'];}else pf_v11_resolve_student($u,$sid);$q=$pdo->prepare('SELECT id,period_days AS periodDays,payload_json AS payloadJson,created_at AS createdAt FROM report_snapshots WHERE student_id=:sid ORDER BY id DESC LIMIT 24');$q->execute(['sid'=>$sid]);$rows=$q->fetchAll();foreach($rows as &$r){$r['payload']=json_decode((string)$r['payloadJson'],true)?:[];unset($r['payloadJson']);}json_response(['reports'=>$rows]);}
if($method==='POST'&&$route==='/ai/student-history'){verify_csrf();$u=require_role('coach','admin');$in=body();$sid=(int)($in['studentId']??0);$report=pf_v13_report($pdo,$u,$sid,90);$base=pf_v15_local_summary($report);$tr=$report['trends']??[];$cmp=$report['comparison']??[];$extra=' Tendência em 90 dias: peso '.(($tr['weightDelta']??null)===null?'sem dados':$tr['weightDelta'].' kg').', gordura '.(($tr['bodyFatDelta']??null)===null?'sem dados':$tr['bodyFatDelta'].' p.p.').'. Variação de treinos contra período anterior: '.($cmp['workoutsDelta']??0).'.';$prompt='Você é um copiloto para personal trainer. Analise o histórico de 90 dias abaixo em português do Brasil. Não faça diagnóstico médico nem prescreva tratamento. Em até 8 frases, destaque aderência, tendências, recordes, alertas e o que o treinador deve revisar. Dados: '.json_encode($report,JSON_UNESCAPED_UNICODE);$ai=pf_v15_gemini($prompt);audit($pdo,(int)$u['id'],'generate','ai_history',$sid,['provider'=>$ai?'gemini':'local']);json_response(['summary'=>$ai?:trim($base.$extra),'provider'=>$ai?'gemini':'local','report'=>$report]);}

require __DIR__.'/performance_tools.php';
require __DIR__.'/admin_master_ops.php';
